In [1]:
import requests
import pandas as pd 
import numpy as np
import time
import re
import json
import warnings
import matplotlib.pyplot as plt

In [2]:
from dotenv import load_dotenv
import os

load_dotenv()

api = os.getenv("api")

print(api)

e38740552c6c2dc3885e682a3490f19b10f1491ea14ba87d43f6ed397c42b382

In [3]:
keywords = [
    "laptop",
    "television",
    "phone",
    "washing machine",
    "microwave",
    "fridge",
    "tablet",
    "chair",
    "camera",
    "printer"
]

In [ ]:
url = "https://serpapi.com/search.json"

api_data = []

for keyword in keywords:
    print(f"Searching: {keyword}")
    keyword_count = 0
    start = 0

    while keyword_count < 100:
        params = {
            "engine": "google_shopping",
            "q": keyword,
            "location": "India",
            "api_key": api,
            "start": start,
            "num": 40
        }

        response = requests.get(url,params=params)
        data = response.json()

        results = data.get(
            "shopping_results",
            []
        )

        if not results:
            print(f"No more results at start={start}")
            break

        for item in results:

            record = {
                "Keyword": keyword,
                "title": item.get("title"),
                "price": item.get("extracted_price"),
                "raw_price": item.get("price"),
                "rating": item.get("rating"),
                "reviews": item.get("reviews"),
                "platform": item.get("source"),
                "position": item.get("position"),
                "delivery": item.get("delivery"),
                "link": item.get("link"),
                "thumbnail": item.get("thumbnail")
            }

            api_data.append(record)

        keyword_count += len(results)
        start += len(results)
        print(f"Page fetched | start = {start - len(results)} | Got {len(results)} results | Total: {keyword_count}")

        time.sleep(1)
 
    print(f"{keyword}: {keyword_count} results collected")

api_df = pd.DataFrame(api_data)
print(f"\n{'='*50}")
print(f"Total results collected: {len(api_df)}")
print(api_df.groupby("Keyword").size())

In [ ]:
api_df.shape

In [ ]:
api_df.head(10)

In [ ]:
api_df.tail(10)

In [ ]:
api_df.info()

In [ ]:
api_df.isnull().sum()

In [ ]:
api_df.to_csv("api.csv")

In [4]:
api_df = pd.read_csv("api.csv")

In [5]:
csv_df = pd.read_csv("brand_dirty_dataset.csv")

csv_df

,keyword,title,price,rating,reviews,platform,delivery
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,3.7,3241,croma,2 Days
1,microwave oven convection,Samsung microwave oven convection Model 524 !!!,NaN,4.7,1294,amazon,Free Delivery
2,power bank fast charging,Samsung power bank fast charging Model 402,Not Available,NaN,3070,CROMA,Free Delivery
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,4.7,3446,flipkart,Free Delivery
4,men running shoes,Dell men running shoes Model 536,2176.0,3.8,2031,croma,5 Days
...,...,...,...,...,...,...,...
1315,office chair ergonomic,HP office chair ergonomic Model 168,20097.0,3.5,2880,CROMA,2 Days
1316,office chair ergonomic,Nike office chair ergonomic Model 138,33684.0,4.1,4006,croma,5 Days
1317,power bank fast charging,HP power bank fast charging Model 250,38959.0,4.6,579,RELIANCE DIGITAL,2 Days
1318,power bank fast charging,Samsung power bank fast charging Model 407,NaN,3.0,384,reliance digital,5 Days
1319,microwave oven convection,Philips microwave oven convection Model 322,Not Available,4.2,3643,croma,Free Delivery

In [6]:
csv_df.shape

(1320, 7)

In [7]:
csv_df.head(10)

,keyword,title,price,rating,reviews,platform,delivery
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,3.7,3241,croma,2 Days
1,microwave oven convection,Samsung microwave oven convection Model 524 !!!,NaN,4.7,1294,amazon,Free Delivery
2,power bank fast charging,Samsung power bank fast charging Model 402,Not Available,NaN,3070,CROMA,Free Delivery
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,4.7,3446,flipkart,Free Delivery
4,men running shoes,Dell men running shoes Model 536,2176.0,3.8,2031,croma,5 Days
5,power bank fast charging,Samsung power bank fast charging Model 562,5331.0,NaN,4124,RELIANCE DIGITAL,5 Days
6,air fryer India,Philips air fryer India Model 259,Not Available,2.8,1761,CROMA,5 Days
7,office chair ergonomic,Philips office chair ergonomic Model 836,4564.0,3.0,1540,AMAZON,Free Delivery
8,microwave oven convection,Boat microwave oven convection Model 588,21830.0,4.0,126,croma,Free Delivery
9,office chair ergonomic,Puma office chair ergonomic Model 591,19233.0,4.6,3911,RELIANCE DIGITAL,5 Days

In [8]:
csv_df.tail(10)

,keyword,title,price,rating,reviews,platform,delivery
1310,microwave oven convection,Boat microwave oven convection Model 727,16473.0,NaN,4296,CROMA,Free Delivery
1311,air fryer India,LG air fryer India Model 363,10393.0,3.5,many,CROMA,2 Days
1312,air fryer India,Sony air fryer India Model 915,21233.0,4.6,57,CROMA,2 Days
1313,microwave oven convection,Nike microwave oven convection Model 392,18929.0,3.7,4407,AMAZON,Free Delivery
1314,microwave oven convection,Samsung microwave oven convection Model 524,NaN,4.7,1294,AMAZON,Free Delivery
1315,office chair ergonomic,HP office chair ergonomic Model 168,20097.0,3.5,2880,CROMA,2 Days
1316,office chair ergonomic,Nike office chair ergonomic Model 138,33684.0,4.1,4006,croma,5 Days
1317,power bank fast charging,HP power bank fast charging Model 250,38959.0,4.6,579,RELIANCE DIGITAL,2 Days
1318,power bank fast charging,Samsung power bank fast charging Model 407,NaN,3.0,384,reliance digital,5 Days
1319,microwave oven convection,Philips microwave oven convection Model 322,Not Available,4.2,3643,croma,Free Delivery

In [9]:
csv_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1320 entries, 0 to 1319
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   keyword   1320 non-null   str
 1   title     1320 non-null   str
 2   price     1194 non-null   str
 3   rating    1189 non-null   float64
 4   reviews   1320 non-null   str
 5   platform  1320 non-null   str
 6   delivery  1320 non-null   str
dtypes: float64(1), str(6)
memory usage: 181.3 KB

In [10]:
csv_df.isnull().sum()

keyword       0
title         0
price       126
rating      131
reviews       0
platform      0
delivery      0
dtype: int64

In [11]:
print(csv_df.columns.tolist())

['keyword', 'title', 'price', 'rating', 'reviews', 'platform', 'delivery']

In [12]:
def standardize_columns(df):

    df = df.copy()

    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("-", "_")
    )

    return df

In [13]:
rename_columns = {

    "keyword": "Keyword",
    "title": "title",

    "price": "price",
    "raw_price": "raw_price",

    "rating": "rating",

    "reviews": "Reviews",
    "review": "Reviews",

    "platform": "platform",
    "source": "platform",

    "position": "position",
    "rank": "position",

    "delivery": "Delivery",

    "link": "Link",
    "product_link": "Link",

    "thumbnail": "thumbnail"
}

In [14]:
csv_df = standardize_columns(csv_df)

api_df = standardize_columns(api_df)

print("CSV Columns:")
print(csv_df.columns.tolist())

print("\nAPI Columns:")
print(api_df.columns.tolist())

CSV Columns:
['keyword', 'title', 'price', 'rating', 'reviews', 'platform', 'delivery']

API Columns:
['unnamed:_0', 'keyword', 'title', 'price', 'raw_price', 'rating', 'reviews', 'platform', 'position', 'delivery', 'link', 'thumbnail']

In [15]:
csv_df = csv_df.rename(
    columns=rename_columns
)

api_df = api_df.rename(
    columns=rename_columns
)

In [16]:
rename_columns = {

    "keyword": "Keyword",
    "title": "title",

    "price": "price",
    "raw_price": "raw_price",

    "rating": "rating",

    "reviews": "Reviews",
    "review": "Reviews",

    "platform": "platform",
    "source": "platform",

    "position": "position",
    "rank": "position",

    "delivery": "Delivery",

    "link": "Link",
    "product_link": "Link",

    "thumbnail": "thumbnail"
}

In [17]:
required_columns = [
    "Keyword",
    "title",
    "price",
    "raw_price",
    "rating",
    "Reviews",
    "platform",
    "position",
    "Delivery",
    "Link",
    "thumbnail"
]

In [18]:
for column in required_columns:

    if column not in csv_df.columns:
        csv_df[column] = np.nan

    if column not in api_df.columns:
        api_df[column] = np.nan

In [19]:
csv_df = csv_df[
    required_columns
]

api_df = api_df[
    required_columns
]

In [20]:
combined_df = pd.concat(
    [
        csv_df,
        api_df
    ],
    ignore_index=True
)

In [21]:
combined_df.to_csv(
    "merged_data.csv",
    index=False
)

In [22]:
combined_df.head()

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,NaN,3.7,3241,croma,NaN,2 Days,NaN,NaN
1,microwave oven convection,Samsung microwave oven convection Model 524 !!!,NaN,NaN,4.7,1294,amazon,NaN,Free Delivery,NaN,NaN
2,power bank fast charging,Samsung power bank fast charging Model 402,Not Available,NaN,NaN,3070,CROMA,NaN,Free Delivery,NaN,NaN
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,NaN,4.7,3446,flipkart,NaN,Free Delivery,NaN,NaN
4,men running shoes,Dell men running shoes Model 536,2176.0,NaN,3.8,2031,croma,NaN,5 Days,NaN,NaN

In [23]:
missing_count = combined_df.isnull().sum()

missing_percentage = (
    combined_df.isnull().mean() * 100
).round(2)

missing_report = pd.DataFrame({

    "Missing Count": missing_count,

    "Missing Percentage":
        missing_percentage
})

missing_report

           Missing Count  Missing Percentage
Keyword                0                0.00
title                  0                0.00
price                126                5.17
raw_price           1320               54.12
rating               398               16.32
Reviews              267               10.95
platform              14                0.57
position            1320               54.12
Delivery             469               19.23
Link                2439              100.00
thumbnail           1320               54.12

In [24]:
pd.read_csv("merged_data.csv")

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,NaN,3.7,3241,croma,NaN,2 Days,NaN,NaN
1,microwave oven convection,Samsung microwave oven convection Model 524 !!!,NaN,NaN,4.7,1294,amazon,NaN,Free Delivery,NaN,NaN
2,power bank fast charging,Samsung power bank fast charging Model 402,Not Available,NaN,NaN,3070,CROMA,NaN,Free Delivery,NaN,NaN
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,NaN,4.7,3446,flipkart,NaN,Free Delivery,NaN,NaN
4,men running shoes,Dell men running shoes Model 536,2176.0,NaN,3.8,2031,croma,NaN,5 Days,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2434,printer,Canon PIXMA MG2541S AiO Colour printer,49.0,$49.00,4.0,34.0,Abed Tahan,36.0,NaN,NaN,https://encrypted-tbn2.gstatic.com/shopping?q=...
2435,printer,HP LaserJet Pro MFP 3101fdw Multifunction Lase...,279.0,$279.00,4.3,311.0,Office Depot,37.0,Free delivery,NaN,https://encrypted-tbn1.gstatic.com/shopping?q=...
2436,printer,Canon PIXMA G3270 Wireless MegaTank All-in-One...,159.99,$159.99,4.1,849.0,Canon,38.0,NaN,NaN,https://encrypted-tbn1.gstatic.com/shopping?q=...
2437,printer,Brother HL-L2325DW Monochrome Laser Printer,339.99,$339.99,4.2,705.0,Walmart - Daily Spirit Deals,39.0,Free delivery,NaN,https://encrypted-tbn3.gstatic.com/shopping?q=...
2438,printer,"Munbyn 941AP Airprint Thermal Label Printer, W...",199.99,$199.99,NaN,NaN,Munbyn,40.0,Free delivery,NaN,https://encrypted-tbn0.gstatic.com/shopping?q=...

In [25]:
merged_df = pd.read_csv("merged_data.csv")

In [26]:
merged_df.shape

(2439, 11)

In [27]:
merged_df.head(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,NaN,3.7,3241,croma,NaN,2 Days,NaN,NaN
1,microwave oven convection,Samsung microwave oven convection Model 524 !!!,NaN,NaN,4.7,1294,amazon,NaN,Free Delivery,NaN,NaN
2,power bank fast charging,Samsung power bank fast charging Model 402,Not Available,NaN,NaN,3070,CROMA,NaN,Free Delivery,NaN,NaN
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,NaN,4.7,3446,flipkart,NaN,Free Delivery,NaN,NaN
4,men running shoes,Dell men running shoes Model 536,2176.0,NaN,3.8,2031,croma,NaN,5 Days,NaN,NaN
5,power bank fast charging,Samsung power bank fast charging Model 562,5331.0,NaN,NaN,4124,RELIANCE DIGITAL,NaN,5 Days,NaN,NaN
6,air fryer India,Philips air fryer India Model 259,Not Available,NaN,2.8,1761,CROMA,NaN,5 Days,NaN,NaN
7,office chair ergonomic,Philips office chair ergonomic Model 836,4564.0,NaN,3.0,1540,AMAZON,NaN,Free Delivery,NaN,NaN
8,microwave oven convection,Boat microwave oven convection Model 588,21830.0,NaN,4.0,126,croma,NaN,Free Delivery,NaN,NaN
9,office chair ergonomic,Puma office chair ergonomic Model 591,19233.0,NaN,4.6,3911,RELIANCE DIGITAL,NaN,5 Days,NaN,NaN

In [28]:
merged_df.tail(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail
2429,printer,Canon imageCLASS MF751Cdw II Wireless Multifun...,432.2,$432.20,4.4,11.0,Best Buy,31.0,NaN,NaN,https://encrypted-tbn0.gstatic.com/shopping?q=...
2430,printer,Brother Mfc-l2760dw Wireless Compact Monochrom...,199.99,$199.99,4.2,628.0,Walmart,32.0,Free delivery,NaN,https://encrypted-tbn0.gstatic.com/shopping?q=...
2431,printer,HP LaserJet MFP M140we,149.99,$149.99,3.9,519.0,Newegg.com - America's Best Supplies,33.0,NaN,NaN,https://encrypted-tbn0.gstatic.com/shopping?q=...
2432,printer,HP OfficeJet Pro 8125 All-in-One Printer,109.99,$109.99,4.2,277.0,Staples,34.0,Free delivery by Tue,NaN,https://encrypted-tbn0.gstatic.com/shopping?q=...
2433,printer,HP Smart Tank 5100 All-in-One Printer,189.99,$189.99,4.1,323.0,Best Buy,35.0,Free delivery by Tue,NaN,https://encrypted-tbn1.gstatic.com/shopping?q=...
2434,printer,Canon PIXMA MG2541S AiO Colour printer,49.0,$49.00,4.0,34.0,Abed Tahan,36.0,NaN,NaN,https://encrypted-tbn2.gstatic.com/shopping?q=...
2435,printer,HP LaserJet Pro MFP 3101fdw Multifunction Lase...,279.0,$279.00,4.3,311.0,Office Depot,37.0,Free delivery,NaN,https://encrypted-tbn1.gstatic.com/shopping?q=...
2436,printer,Canon PIXMA G3270 Wireless MegaTank All-in-One...,159.99,$159.99,4.1,849.0,Canon,38.0,NaN,NaN,https://encrypted-tbn1.gstatic.com/shopping?q=...
2437,printer,Brother HL-L2325DW Monochrome Laser Printer,339.99,$339.99,4.2,705.0,Walmart - Daily Spirit Deals,39.0,Free delivery,NaN,https://encrypted-tbn3.gstatic.com/shopping?q=...
2438,printer,"Munbyn 941AP Airprint Thermal Label Printer, W...",199.99,$199.99,NaN,NaN,Munbyn,40.0,Free delivery,NaN,https://encrypted-tbn0.gstatic.com/shopping?q=...

In [29]:
many_count = (merged_df["Reviews"] == "many").sum()

print("Records with 'many':", many_count)
print(merged_df[merged_df["Reviews"] == "many"])

Records with 'many': 26
                        Keyword                                       title  \
56    microwave oven convection    Puma microwave oven convection Model 583
117      office chair ergonomic         LG office chair ergonomic Model 655
127    power bank fast charging       HP power bank fast charging Model 469
226           men running shoes              HP men running shoes Model 182
427      office chair ergonomic    Philips office chair ergonomic Model 733
476      office chair ergonomic       Boat office chair ergonomic Model 922
582   microwave oven convection    Sony microwave oven convection Model 900
672      office chair ergonomic    Philips office chair ergonomic Model 798
685    power bank fast charging     Dell power bank fast charging Model 817
722           men running shoes            Sony men running shoes Model 587
811             air fryer India           Samsung air fryer India Model 295
830             air fryer India           Samsung air fryer India Model 811
831   microwave oven convection    Boat microwave oven convection Model 555
858      office chair ergonomic       Nike office chair ergonomic Model 852
946   microwave oven convection    Boat microwave oven convection Model 156
964           men running shoes              HP men running shoes Model 481
1050   power bank fast charging  Philips power bank fast charging Model 373
1073  microwave oven convection      HP microwave oven convection Model 455
1163            air fryer India              Nike air fryer India Model 396
1213            air fryer India           Philips air fryer India Model 269
1229            air fryer India                HP air fryer India Model 947
1240   power bank fast charging     Boat power bank fast charging Model 295
1279          men running shoes            Sony men running shoes Model 584
1287     office chair ergonomic    Philips office chair ergonomic Model 414
1309     office chair ergonomic         LG office chair ergonomic Model 829
1311            air fryer India                LG air fryer India Model 363

         price raw_price  rating Reviews          platform  position  \
56     33632.0       NaN     4.5    many  reliance digital       NaN
117    41827.0       NaN     4.1    many          FLIPKART       NaN
127    23432.0       NaN     3.3    many             croma       NaN
226    47672.0       NaN     3.9    many  RELIANCE DIGITAL       NaN
427     2022.0       NaN     3.7    many          FLIPKART       NaN
476    11394.0       NaN     3.7    many  reliance digital       NaN
582        NaN       NaN     NaN    many  reliance digital       NaN
672        NaN       NaN     3.6    many          FLIPKART       NaN
685     8299.0       NaN     3.7    many          FLIPKART       NaN
722    44061.0       NaN     NaN    many            AMAZON       NaN
811        NaN       NaN     NaN    many  RELIANCE DIGITAL       NaN
830     8748.0       NaN     3.9    many            amazon       NaN
831    40310.0       NaN     3.7    many             croma       NaN
858       -999       NaN     2.6    many  reliance digital       NaN
946    22013.0       NaN     4.8    many             CROMA       NaN
964        NaN       NaN     3.4    many             CROMA       NaN
1050   31026.0       NaN     4.5    many  reliance digital       NaN
1073    1099.0       NaN     2.6    many  RELIANCE DIGITAL       NaN
1163       NaN       NaN     2.6    many  RELIANCE DIGITAL       NaN
1213       NaN       NaN     3.6    many          flipkart       NaN
1229   26570.0       NaN     4.9    many             croma       NaN
1240  171520.0       NaN     3.9    many          FLIPKART       NaN
1279       NaN       NaN     4.1    many             croma       NaN
1287   12081.0       NaN     3.2    many            AMAZON       NaN
1309   48662.0       NaN     4.2    many            amazon       NaN
1311   10393.0       NaN     3.5    many             CROMA       NaN

           Delivery  Link thumbnail
56    Free Delivery   NaN       NaN
117   Free Delivery   NaN       NaN
127          2 Days   NaN       NaN
226          2 Days   NaN       NaN
427          2 Days   NaN       NaN
476          5 Days   NaN       NaN
582   Free Delivery   NaN       NaN
672          5 Days   NaN       NaN
685          5 Days   NaN       NaN
722          2 Days   NaN       NaN
811          2 Days   NaN       NaN
830          2 Days   NaN       NaN
831          5 Days   NaN       NaN
858          2 Days   NaN       NaN
946          2 Days   NaN       NaN
964          2 Days   NaN       NaN
1050         2 Days   NaN       NaN
1073         2 Days   NaN       NaN
1163         5 Days   NaN       NaN
1213         5 Days   NaN       NaN
1229         2 Days   NaN       NaN
1240  Free Delivery   NaN       NaN
1279         5 Days   NaN       NaN
1287  Free Delivery   NaN       NaN
1309         2 Days   NaN       NaN
1311         2 Days   NaN       NaN

In [30]:
print("CSV shape:", csv_df.shape)
print("API shape:", api_df.shape)

print("\nCSV missing values:")
print(csv_df.isnull().sum())

print("\nAPI missing values:")
print(api_df.isnull().sum())

CSV shape: (1320, 11)
API shape: (1119, 11)

CSV missing values:
Keyword         0
title           0
price         126
raw_price    1320
rating        131
Reviews         0
platform        0
position     1320
Delivery        0
Link         1320
thumbnail    1320
dtype: int64

API missing values:
Keyword         0
title           0
price           0
raw_price       0
rating        267
Reviews       267
platform       14
position        0
Delivery      469
Link         1119
thumbnail       0
dtype: int64

In [31]:
print("CSV Position missing:")
print(csv_df["position"].isnull().sum())

print("API Position missing:")
print(api_df["position"].isnull().sum())

CSV Position missing:
1320
API Position missing:
0

In [32]:
print("CSV Platform values:")
print(csv_df["platform"].value_counts(dropna=False))

print("\nAPI Platform values:")
print(api_df["platform"].value_counts(dropna=False))

CSV Platform values:
platform
reliance digital    193
amazon              182
flipkart            168
CROMA               164
croma               162
RELIANCE DIGITAL    160
AMAZON              155
FLIPKART            136
Name: count, dtype: int64

API Platform values:
platform
Best Buy                                138
Walmart                                  81
Target                                   62
Home Depot                               33
eBay                                     28
                                       ...
eBay - remsenway70                        1
Newegg.com - America's Best Supplies      1
Abed Tahan                                1
Walmart - Daily Spirit Deals              1
Munbyn                                    1
Name: count, Length: 313, dtype: int64

In [33]:
print(merged_df.dtypes)

Keyword          str
title            str
price            str
raw_price        str
rating       float64
Reviews          str
platform         str
position     float64
Delivery         str
Link         float64
thumbnail        str
dtype: object

In [34]:
clean_df = merged_df.copy()

In [35]:
clean_df.shape

(2439, 11)

In [36]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2439 entries, 0 to 2438
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Keyword    2439 non-null   str
 1   title      2439 non-null   str
 2   price      2313 non-null   str
 3   raw_price  1119 non-null   str
 4   rating     2041 non-null   float64
 5   Reviews    2172 non-null   str
 6   platform   2425 non-null   str
 7   position   1119 non-null   float64
 8   Delivery   1970 non-null   str
 9   Link       0 non-null      float64
 10  thumbnail  1119 non-null   str
dtypes: float64(3), str(8)
memory usage: 618.7 KB

In [37]:
text_columns = [
    "Keyword",
    "title",
    "platform",
    "Delivery",
    "Link",
    "thumbnail"
]

for column in text_columns:
    clean_df[column] = (
        clean_df[column]
        .astype("string")
        .str.strip()
    )

In [38]:
clean_df["platform"] = (
    clean_df["platform"]
    .str.lower()
    .str.strip()
)

In [39]:
clean_df.head(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,NaN,3.7,3241,croma,NaN,2 Days,<NA>,<NA>
1,microwave oven convection,Samsung microwave oven convection Model 524 !!!,NaN,NaN,4.7,1294,amazon,NaN,Free Delivery,<NA>,<NA>
2,power bank fast charging,Samsung power bank fast charging Model 402,Not Available,NaN,NaN,3070,croma,NaN,Free Delivery,<NA>,<NA>
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,NaN,4.7,3446,flipkart,NaN,Free Delivery,<NA>,<NA>
4,men running shoes,Dell men running shoes Model 536,2176.0,NaN,3.8,2031,croma,NaN,5 Days,<NA>,<NA>
5,power bank fast charging,Samsung power bank fast charging Model 562,5331.0,NaN,NaN,4124,reliance digital,NaN,5 Days,<NA>,<NA>
6,air fryer India,Philips air fryer India Model 259,Not Available,NaN,2.8,1761,croma,NaN,5 Days,<NA>,<NA>
7,office chair ergonomic,Philips office chair ergonomic Model 836,4564.0,NaN,3.0,1540,amazon,NaN,Free Delivery,<NA>,<NA>
8,microwave oven convection,Boat microwave oven convection Model 588,21830.0,NaN,4.0,126,croma,NaN,Free Delivery,<NA>,<NA>
9,office chair ergonomic,Puma office chair ergonomic Model 591,19233.0,NaN,4.6,3911,reliance digital,NaN,5 Days,<NA>,<NA>

In [40]:
clean_df.tail(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail
2429,printer,Canon imageCLASS MF751Cdw II Wireless Multifun...,432.2,$432.20,4.4,11.0,best buy,31.0,<NA>,<NA>,https://encrypted-tbn0.gstatic.com/shopping?q=...
2430,printer,Brother Mfc-l2760dw Wireless Compact Monochrom...,199.99,$199.99,4.2,628.0,walmart,32.0,Free delivery,<NA>,https://encrypted-tbn0.gstatic.com/shopping?q=...
2431,printer,HP LaserJet MFP M140we,149.99,$149.99,3.9,519.0,newegg.com - america's best supplies,33.0,<NA>,<NA>,https://encrypted-tbn0.gstatic.com/shopping?q=...
2432,printer,HP OfficeJet Pro 8125 All-in-One Printer,109.99,$109.99,4.2,277.0,staples,34.0,Free delivery by Tue,<NA>,https://encrypted-tbn0.gstatic.com/shopping?q=...
2433,printer,HP Smart Tank 5100 All-in-One Printer,189.99,$189.99,4.1,323.0,best buy,35.0,Free delivery by Tue,<NA>,https://encrypted-tbn1.gstatic.com/shopping?q=...
2434,printer,Canon PIXMA MG2541S AiO Colour printer,49.0,$49.00,4.0,34.0,abed tahan,36.0,<NA>,<NA>,https://encrypted-tbn2.gstatic.com/shopping?q=...
2435,printer,HP LaserJet Pro MFP 3101fdw Multifunction Lase...,279.0,$279.00,4.3,311.0,office depot,37.0,Free delivery,<NA>,https://encrypted-tbn1.gstatic.com/shopping?q=...
2436,printer,Canon PIXMA G3270 Wireless MegaTank All-in-One...,159.99,$159.99,4.1,849.0,canon,38.0,<NA>,<NA>,https://encrypted-tbn1.gstatic.com/shopping?q=...
2437,printer,Brother HL-L2325DW Monochrome Laser Printer,339.99,$339.99,4.2,705.0,walmart - daily spirit deals,39.0,Free delivery,<NA>,https://encrypted-tbn3.gstatic.com/shopping?q=...
2438,printer,"Munbyn 941AP Airprint Thermal Label Printer, W...",199.99,$199.99,NaN,NaN,munbyn,40.0,Free delivery,<NA>,https://encrypted-tbn0.gstatic.com/shopping?q=...

In [41]:
print(clean_df[clean_df["title"].str.contains(r"[^A-Za-z0-9\s]")].head)

<bound method NDFrame.head of                         Keyword  \
1     microwave oven convection
10            men running shoes
18       office chair ergonomic
22     power bank fast charging
31    microwave oven convection
...                         ...
2432                    printer
2433                    printer
2436                    printer
2437                    printer
2438                    printer

                                                  title    price raw_price  \
1       Samsung microwave oven convection Model 524 !!!      NaN       NaN
10                 Boat men running shoes Model 859 !!!  20381.0       NaN
18            Puma office chair ergonomic Model 198 !!!  15160.0       NaN
22          Puma power bank fast charging Model 621 !!!  48199.0       NaN
31         Nike microwave oven convection Model 917 !!!   4484.0       NaN
...                                                 ...      ...       ...
2432           HP OfficeJet Pro 8125 All-in-One Printer   109.99   $109.99
2433              HP Smart Tank 5100 All-in-One Printer   189.99   $189.99
2436  Canon PIXMA G3270 Wireless MegaTank All-in-One...   159.99   $159.99
2437        Brother HL-L2325DW Monochrome Laser Printer   339.99   $339.99
2438  Munbyn 941AP Airprint Thermal Label Printer, W...   199.99   $199.99

      rating Reviews                      platform  position  \
1        4.7    1294                        amazon       NaN
10       NaN     684                        amazon       NaN
18       3.2    1275                      flipkart       NaN
22       NaN     203                        amazon       NaN
31       3.0    3422              reliance digital       NaN
...      ...     ...                           ...       ...
2432     4.2   277.0                       staples      34.0
2433     4.1   323.0                      best buy      35.0
2436     4.1   849.0                         canon      38.0
2437     4.2   705.0  walmart - daily spirit deals      39.0
2438     NaN     NaN                        munbyn      40.0

                  Delivery  Link  \
1            Free Delivery  <NA>
10                  2 Days  <NA>
18                  2 Days  <NA>
22                  2 Days  <NA>
31                  5 Days  <NA>
...                    ...   ...
2432  Free delivery by Tue  <NA>
2433  Free delivery by Tue  <NA>
2436                  <NA>  <NA>
2437         Free delivery  <NA>
2438         Free delivery  <NA>

                                              thumbnail
1                                                  <NA>
10                                                 <NA>
18                                                 <NA>
22                                                 <NA>
31                                                 <NA>
...                                                 ...
2432  https://encrypted-tbn0.gstatic.com/shopping?q=...
2433  https://encrypted-tbn1.gstatic.com/shopping?q=...
2436  https://encrypted-tbn1.gstatic.com/shopping?q=...
2437  https://encrypted-tbn3.gstatic.com/shopping?q=...
2438  https://encrypted-tbn0.gstatic.com/shopping?q=...

[928 rows x 11 columns]>

In [42]:
clean_df["title"] = (
    clean_df["title"]
    .str.replace(r"[^A-Za-z0-9\s]", "", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [43]:
clean_df.head()

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,NaN,3.7,3241,croma,NaN,2 Days,<NA>,<NA>
1,microwave oven convection,Samsung microwave oven convection Model 524,NaN,NaN,4.7,1294,amazon,NaN,Free Delivery,<NA>,<NA>
2,power bank fast charging,Samsung power bank fast charging Model 402,Not Available,NaN,NaN,3070,croma,NaN,Free Delivery,<NA>,<NA>
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,NaN,4.7,3446,flipkart,NaN,Free Delivery,<NA>,<NA>
4,men running shoes,Dell men running shoes Model 536,2176.0,NaN,3.8,2031,croma,NaN,5 Days,<NA>,<NA>

In [44]:
print(clean_df["platform"].value_counts().head(10))

platform
reliance digital                353
amazon                          337
croma                           326
flipkart                        304
best buy                        138
walmart                          81
target                           62
home depot                       33
ebay                             28
american furniture warehouse     27
Name: count, dtype: int64[pyarrow]

In [45]:
print(clean_df[["price", "raw_price", "rating", "Reviews", "position"]].head(10))

           price raw_price  rating Reviews  position
0        36225.0       NaN     3.7    3241       NaN
1            NaN       NaN     4.7    1294       NaN
2  Not Available       NaN     NaN    3070       NaN
3         2507.0       NaN     4.7    3446       NaN
4         2176.0       NaN     3.8    2031       NaN
5         5331.0       NaN     NaN    4124       NaN
6  Not Available       NaN     2.8    1761       NaN
7         4564.0       NaN     3.0    1540       NaN
8        21830.0       NaN     4.0     126       NaN
9        19233.0       NaN     4.6    3911       NaN

In [46]:
clean_df["price"] = pd.to_numeric(
    clean_df["price"],
    errors="coerce"
)

clean_df["rating"] = pd.to_numeric(
    clean_df["rating"],
    errors="coerce"
)

clean_df["Reviews"] = pd.to_numeric(
    clean_df["Reviews"],
    errors="coerce"
).astype("Int64")

clean_df["position"] = pd.to_numeric(
    clean_df["position"],
    errors="coerce"
).astype("Int64")

clean_df["raw_price"] = (
    clean_df["raw_price"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

clean_df["raw_price"] = pd.to_numeric(
    clean_df["raw_price"],
    errors="coerce"
)

In [47]:
clean_df.head(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,NaN,3.7,3241,croma,<NA>,2 Days,<NA>,<NA>
1,microwave oven convection,Samsung microwave oven convection Model 524,NaN,NaN,4.7,1294,amazon,<NA>,Free Delivery,<NA>,<NA>
2,power bank fast charging,Samsung power bank fast charging Model 402,NaN,NaN,NaN,3070,croma,<NA>,Free Delivery,<NA>,<NA>
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,NaN,4.7,3446,flipkart,<NA>,Free Delivery,<NA>,<NA>
4,men running shoes,Dell men running shoes Model 536,2176.0,NaN,3.8,2031,croma,<NA>,5 Days,<NA>,<NA>
5,power bank fast charging,Samsung power bank fast charging Model 562,5331.0,NaN,NaN,4124,reliance digital,<NA>,5 Days,<NA>,<NA>
6,air fryer India,Philips air fryer India Model 259,NaN,NaN,2.8,1761,croma,<NA>,5 Days,<NA>,<NA>
7,office chair ergonomic,Philips office chair ergonomic Model 836,4564.0,NaN,3.0,1540,amazon,<NA>,Free Delivery,<NA>,<NA>
8,microwave oven convection,Boat microwave oven convection Model 588,21830.0,NaN,4.0,126,croma,<NA>,Free Delivery,<NA>,<NA>
9,office chair ergonomic,Puma office chair ergonomic Model 591,19233.0,NaN,4.6,3911,reliance digital,<NA>,5 Days,<NA>,<NA>

In [48]:
print(clean_df[[
    "price",
    "raw_price",
    "rating",
    "Reviews",
    "position"
]].dtypes)

price        float64
raw_price    float64
rating       float64
Reviews        Int64
position       Int64
dtype: object

In [49]:
clean_df.dtypes

Keyword       string
title         string
price        float64
raw_price    float64
rating       float64
Reviews        Int64
platform      string
position       Int64
Delivery      string
Link          string
thumbnail     string
dtype: object

In [50]:
print(clean_df[[
    "price",
    "raw_price",
    "rating",
    "Reviews",
    "position"
]].isnull().sum())

price         192
raw_price    1352
rating        398
Reviews       293
position     1320
dtype: int64

In [51]:
print("CSV missing price:",
      csv_df["price"].isnull().sum())

print("API missing price:",
      api_df["price"].isnull().sum())

CSV missing price: 126
API missing price: 0

In [52]:
clean_df.isnull().sum()

Keyword         0
title           0
price         192
raw_price    1352
rating        398
Reviews       293
platform       14
position     1320
Delivery      469
Link         2439
thumbnail    1320
dtype: int64

In [53]:
clean_df.isnull().mean().mul(100).round(2)

Keyword        0.00
title          0.00
price          7.87
raw_price     55.43
rating        16.32
Reviews       12.01
platform       0.57
position      54.12
Delivery      19.23
Link         100.00
thumbnail     54.12
dtype: float64

In [54]:
clean_df["Data_Source"] = [
    "CSV" if i < len(csv_df) else "API"
    for i in range(len(clean_df))
]

In [55]:
print(clean_df["Data_Source"].value_counts())

Data_Source
CSV    1320
API    1119
Name: count, dtype: int64

In [56]:
for source in clean_df["Data_Source"].unique():

    print(f"\n--- {source} ---")

    print(
        clean_df[
            clean_df["Data_Source"] == source
        ].isnull().sum()
    )

--- CSV ---
Keyword           0
title             0
price           192
raw_price      1320
rating          131
Reviews          26
platform          0
position       1320
Delivery          0
Link           1320
thumbnail      1320
Data_Source       0
dtype: int64

--- API ---
Keyword           0
title             0
price             0
raw_price        32
rating          267
Reviews         267
platform         14
position          0
Delivery        469
Link           1119
thumbnail         0
Data_Source       0
dtype: int64

In [57]:
duplicate_count = clean_df.duplicated().sum()

print("Total duplicate rows:", duplicate_count)

Total duplicate rows: 154

In [58]:
duplicates = clean_df[
    clean_df.duplicated(keep=False)
].sort_values("title")

duplicates.head(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail,Data_Source
1695,washing machine,45 Cu Ft Ultra Large Front Load Washer,745.00,745.00,NaN,<NA>,southern appliances,17,Free delivery,<NA>,https://encrypted-tbn0.gstatic.com/shopping?q=...,API
1735,washing machine,45 Cu Ft Ultra Large Front Load Washer,745.00,745.00,NaN,<NA>,southern appliances,17,Free delivery,<NA>,https://encrypted-tbn0.gstatic.com/shopping?q=...,API
1470,television,50 4K UHD Smart TV,297.49,297.49,4.5,189,fpd,32,Free delivery by Tue,<NA>,https://encrypted-tbn2.gstatic.com/shopping?q=...,API
1510,television,50 4K UHD Smart TV,297.49,297.49,4.5,189,fpd,32,Free delivery by Tue,<NA>,https://encrypted-tbn2.gstatic.com/shopping?q=...,API
1698,washing machine,50 cu ft Mega Capacity Smart Front Load Washer...,1166.00,1166.00,NaN,<NA>,valley oak home appliance center,20,<NA>,<NA>,https://encrypted-tbn1.gstatic.com/shopping?q=...,API
1699,washing machine,50 cu ft Mega Capacity Smart Front Load Washer...,1049.00,1049.00,NaN,<NA>,bill & rods appliances,21,<NA>,<NA>,https://encrypted-tbn1.gstatic.com/shopping?q=...,API
1700,washing machine,50 cu ft Mega Capacity Smart Front Load Washer...,1166.00,1166.00,NaN,<NA>,johnson's appliances & bedding,22,<NA>,<NA>,https://encrypted-tbn1.gstatic.com/shopping?q=...,API
1738,washing machine,50 cu ft Mega Capacity Smart Front Load Washer...,1166.00,1166.00,NaN,<NA>,valley oak home appliance center,20,<NA>,<NA>,https://encrypted-tbn1.gstatic.com/shopping?q=...,API
1739,washing machine,50 cu ft Mega Capacity Smart Front Load Washer...,1049.00,1049.00,NaN,<NA>,bill & rods appliances,21,<NA>,<NA>,https://encrypted-tbn1.gstatic.com/shopping?q=...,API
1740,washing machine,50 cu ft Mega Capacity Smart Front Load Washer...,1166.00,1166.00,NaN,<NA>,johnson's appliances & bedding,22,<NA>,<NA>,https://encrypted-tbn1.gstatic.com/shopping?q=...,API

In [59]:
clean_df = clean_df.drop_duplicates().reset_index(drop=True)

print("Shape after removing duplicates:", clean_df.shape)

Shape after removing duplicates: (2285, 12)

In [60]:
print("Final rows:", len(clean_df))
print("Duplicate rows:", clean_df.duplicated().sum())

Final rows: 2285
Duplicate rows: 0

In [61]:
print("Missing prices:", clean_df["price"].isnull().sum())

print("Zero prices:", (clean_df["price"] == 0).sum())

print("Negative prices:", (clean_df["price"] < 0).sum())

print("\nMinimum price:", clean_df["price"].min())
print("Maximum price:", clean_df["price"].max())

Missing prices: 185
Zero prices: 0
Negative prices: 26

Minimum price: -999.0
Maximum price: 498050.0

In [62]:
print("Missing rating:", clean_df['rating'].isnull().sum())
print("Missing Review:", clean_df['Reviews'].isnull().sum())

print("\nZero rating:", (clean_df['rating'] == 0).sum())
print("Zero Review:", (clean_df['Reviews'] ==0).sum())

print("\nNegative rating:", (clean_df['rating'] < 0).sum())
print("Negative Review:", (clean_df['Reviews'] < 0).sum())

print("Rating above 5:", (clean_df['rating'] > 5).sum())

print("\nMinimum rating:", clean_df['rating'].min())
print("Minimum Review:", clean_df['Reviews'].min())

print("\nMaximum rating:", clean_df['rating'].max())
print("Maximum Review:", clean_df['Reviews'].max())

Missing rating: 361
Missing Review: 266

Zero rating: 0
Zero Review: 0

Negative rating: 0
Negative Review: 0
Rating above 5: 0

Minimum rating: 1.0
Minimum Review: 1

Maximum rating: 5.0
Maximum Review: 108000

In [63]:
print("Rating distribution:")
print(clean_df["rating"].describe())

print("\nReviews distribution:")
print(clean_df["Reviews"].describe())

Rating distribution:
count    1924.000000
mean        3.949948
std         0.773740
min         1.000000
25%         3.400000
50%         4.100000
75%         4.600000
max         5.000000
Name: rating, dtype: float64

Reviews distribution:
count         2019.0
mean     3027.234274
std      6467.438467
min              1.0
25%            434.0
50%           1743.0
75%           3496.5
max         108000.0
Name: Reviews, dtype: Float64

In [64]:
many_count = (clean_df["Reviews"] == "many").sum()

print("Records with 'many':", many_count)
print(clean_df[clean_df["Reviews"] == "many"])

Records with 'many': 0
Empty DataFrame
Columns: [Keyword, title, price, raw_price, rating, Reviews, platform, position, Delivery, Link, thumbnail, Data_Source]
Index: []

In [65]:
clean_df.head(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail,Data_Source
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,NaN,3.7,3241,croma,<NA>,2 Days,<NA>,<NA>,CSV
1,microwave oven convection,Samsung microwave oven convection Model 524,NaN,NaN,4.7,1294,amazon,<NA>,Free Delivery,<NA>,<NA>,CSV
2,power bank fast charging,Samsung power bank fast charging Model 402,NaN,NaN,NaN,3070,croma,<NA>,Free Delivery,<NA>,<NA>,CSV
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,NaN,4.7,3446,flipkart,<NA>,Free Delivery,<NA>,<NA>,CSV
4,men running shoes,Dell men running shoes Model 536,2176.0,NaN,3.8,2031,croma,<NA>,5 Days,<NA>,<NA>,CSV
5,power bank fast charging,Samsung power bank fast charging Model 562,5331.0,NaN,NaN,4124,reliance digital,<NA>,5 Days,<NA>,<NA>,CSV
6,air fryer India,Philips air fryer India Model 259,NaN,NaN,2.8,1761,croma,<NA>,5 Days,<NA>,<NA>,CSV
7,office chair ergonomic,Philips office chair ergonomic Model 836,4564.0,NaN,3.0,1540,amazon,<NA>,Free Delivery,<NA>,<NA>,CSV
8,microwave oven convection,Boat microwave oven convection Model 588,21830.0,NaN,4.0,126,croma,<NA>,Free Delivery,<NA>,<NA>,CSV
9,office chair ergonomic,Puma office chair ergonomic Model 591,19233.0,NaN,4.6,3911,reliance digital,<NA>,5 Days,<NA>,<NA>,CSV

In [66]:
clean_df.loc[clean_df["price"] < 0, "price"] = np.nan

In [67]:
print("Negative prices:", (clean_df["price"] < 0).sum())
print("Missing prices:", clean_df["price"].isnull().sum())
print("Missing rawprice:", clean_df['raw_price'].isnull().sum())
print("Missing reviews:", clean_df['Reviews'].isnull().sum())

Negative prices: 0
Missing prices: 211
Missing rawprice: 1264
Missing reviews: 266

In [68]:
clean_df["price"].describe()

count      2074.000000
mean      17755.101977
std       44854.484375
min           4.990000
25%         249.990000
50%        2035.595000
75%       24596.250000
max      498050.000000
Name: price, dtype: float64

In [69]:
Q1 = clean_df["price"].quantile(0.25)
Q3 = clean_df["price"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

Q1: 249.99
Q3: 24596.25
IQR: 24346.26
Lower Bound: -36269.4
Upper Bound: 61115.64

In [70]:
price_outliers = clean_df[
    (clean_df["price"] < lower_bound) | 
    (clean_df["price"] > upper_bound)
]

print("Number of price outliers:", len(price_outliers))

Number of price outliers: 49

In [71]:
price_outliers[
    ["Keyword", "title", "price", "platform", "Data_Source"]
].sort_values("price", ascending=False).head(10)

,Keyword,title,price,platform,Data_Source
266,men running shoes,HP men running shoes Model 483,498050.0,amazon,CSV
1215,air fryer India,Nike air fryer India Model 162,489880.0,flipkart,CSV
440,microwave oven convection,Boat microwave oven convection Model 424,482890.0,amazon,CSV
965,men running shoes,HP men running shoes Model 580,461640.0,amazon,CSV
282,office chair ergonomic,Boat office chair ergonomic Model 324,455330.0,amazon,CSV
34,microwave oven convection,Dell microwave oven convection Model 272,438510.0,reliance digital,CSV
374,power bank fast charging,Nike power bank fast charging Model 406,436130.0,reliance digital,CSV
1015,office chair ergonomic,Boat office chair ergonomic Model 756,405890.0,amazon,CSV
1032,microwave oven convection,Philips microwave oven convection Model 148,402890.0,reliance digital,CSV
1219,office chair ergonomic,Sony office chair ergonomic Model 116,397700.0,reliance digital,CSV

In [72]:
clean_df.loc[
    (clean_df["price"] < lower_bound) |
    (clean_df["price"] > upper_bound),
    "price"
] = np.nan

In [73]:
invalid_price_rows = clean_df[
    clean_df["price"].isna()
]

invalid_price_rows[
    ["Keyword", "title", "price", "platform", "Data_Source"]
].head(20)

,Keyword,title,price,platform,Data_Source
1,microwave oven convection,Samsung microwave oven convection Model 524,NaN,amazon,CSV
2,power bank fast charging,Samsung power bank fast charging Model 402,NaN,croma,CSV
6,air fryer India,Philips air fryer India Model 259,NaN,croma,CSV
12,power bank fast charging,Dell power bank fast charging Model 575,NaN,croma,CSV
19,microwave oven convection,Samsung microwave oven convection Model 810,NaN,croma,CSV
21,men running shoes,Puma men running shoes Model 233,NaN,flipkart,CSV
23,microwave oven convection,LG microwave oven convection Model 479,NaN,amazon,CSV
33,power bank fast charging,Boat power bank fast charging Model 977,NaN,amazon,CSV
34,microwave oven convection,Dell microwave oven convection Model 272,NaN,reliance digital,CSV
46,power bank fast charging,Puma power bank fast charging Model 256,NaN,amazon,CSV
63,microwave oven convection,Sony microwave oven convection Model 912,NaN,reliance digital,CSV
64,men running shoes,Samsung men running shoes Model 630,NaN,amazon,CSV
68,office chair ergonomic,Puma office chair ergonomic Model 514,NaN,croma,CSV
70,microwave oven convection,Nike microwave oven convection Model 591,NaN,reliance digital,CSV
73,power bank fast charging,Boat power bank fast charging Model 137,NaN,reliance digital,CSV
78,office chair ergonomic,LG office chair ergonomic Model 374,NaN,croma,CSV
95,men running shoes,Boat men running shoes Model 369,NaN,flipkart,CSV
96,microwave oven convection,Sony microwave oven convection Model 340,NaN,reliance digital,CSV
97,office chair ergonomic,Nike office chair ergonomic Model 416,NaN,croma,CSV
98,air fryer India,Philips air fryer India Model 746,NaN,croma,CSV

In [74]:
print(clean_df["price"].median())
print(clean_df["price"].mean())

1670.0
11983.744444444445

In [75]:
clean_df["price"].isnull().sum()

np.int64(260)

In [76]:
print(clean_df.groupby('Keyword')['price'].median())

Keyword
air fryer India              23754.50
camera                         574.95
chair                          248.67
fridge                         629.99
laptop                         799.99
men running shoes            22065.00
microwave                      109.99
microwave oven convection    22546.50
office chair ergonomic       23925.50
phone                          372.49
power bank fast charging     26131.00
printer                        107.00
tablet                         192.49
television                     289.91
washing machine                369.99
Name: price, dtype: float64

In [77]:
clean_df["price"] = clean_df.groupby("Keyword")["price"].transform(
    lambda x: x.fillna(x.median())
)

In [78]:
clean_df["price"].isnull().sum()

np.int64(0)

In [79]:
price_outliers = clean_df[
    (clean_df["price"] < lower_bound) | 
    (clean_df["price"] > upper_bound)
]

print("Number of price outliers:", len(price_outliers))

Number of price outliers: 0

In [80]:
print(clean_df["rating"].mean())
print(clean_df["rating"].median())

3.949948024948025
4.1

In [81]:
clean_df["rating"].isnull().sum()

np.int64(361)

In [82]:
print(clean_df.groupby("Keyword")["rating"].median())

Keyword
air fryer India              3.8
camera                       5.0
chair                        4.5
fridge                       4.1
laptop                       4.5
men running shoes            3.7
microwave                    4.2
microwave oven convection    3.8
office chair ergonomic       3.7
phone                        4.6
power bank fast charging     3.9
printer                      4.2
tablet                       4.6
television                   4.5
washing machine              4.3
Name: rating, dtype: float64

In [83]:
clean_df["rating"] = clean_df.groupby("Keyword")["rating"].transform(
    lambda x: x.fillna(x.median())
)

In [84]:
clean_df["rating"].isnull().sum()

np.int64(0)

In [85]:
clean_df["price"].describe()

count     2285.000000
mean     13295.850761
std      15125.762749
min          4.990000
25%        299.800000
50%       4845.000000
75%      23925.500000
max      49990.000000
Name: price, dtype: float64

In [86]:
clean_df["Delivery"] = (
    clean_df["Delivery"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .replace("", "Unknown")
    .fillna("Unknown")
)

In [87]:
print(
    clean_df["Delivery"].value_counts(dropna=False)
)

Delivery
Unknown                       437
Free Delivery                 431
2 Days                        411
5 Days                        393
Free delivery                 365
Free delivery by Wed           63
Free delivery by Tue           55
Free delivery by Sat           54
Free delivery by Thu           48
Free delivery by Fri           19
Free next-day delivery          6
Free delivery on $99+           2
Free delivery on $500,000+      1
Name: count, dtype: int64[pyarrow]

In [88]:
clean_df["platform"] = (
    clean_df["platform"]
    .astype("string")
    .str.strip()
    .str.lower()
)

clean_df["platform"] = clean_df["platform"].replace(
    r"^\s*$",
    np.nan,
    regex=True
)

In [91]:
print("Unique platforms:", clean_df["platform"].nunique())

print("\nTop platforms:")
print(
    clean_df["platform"]
    .value_counts()
    .head(20)
)

Unique platforms: 316

Top platforms:
platform
reliance digital                324
amazon                          321
croma                           303
flipkart                        287
best buy                        135
walmart                          73
target                           57
home depot                       33
ebay                             26
mercari                          23
staples                          20
american furniture warehouse     20
lowe's                           19
macy's                           13
office depot                     11
hsn                              10
ohiofurnitureusa.com             10
ebay - sarahcell                  9
rent-a-center                     9
t-mobile                          8
Name: count, dtype: int64[pyarrow]

In [92]:
amazon_values = clean_df.loc[
    clean_df["platform"]
    .astype("string")
    .str.strip()
    .str.lower()
    .eq("amazon"),
    "platform"
].value_counts()

print(amazon_values)

platform
amazon    321
Name: count, dtype: int64[pyarrow]

In [93]:
clean_df["brand"] = (
    clean_df["title"]
    .str.split()
    .str[0]
    .str.strip()
)

In [94]:
print(clean_df[["title", "brand"]].head(10))

                                         title    brand
0          HP office chair ergonomic Model 603       HP
1  Samsung microwave oven convection Model 524  Samsung
2   Samsung power bank fast charging Model 402  Samsung
3     Dell microwave oven convection Model 877     Dell
4             Dell men running shoes Model 536     Dell
5   Samsung power bank fast charging Model 562  Samsung
6            Philips air fryer India Model 259  Philips
7     Philips office chair ergonomic Model 836  Philips
8     Boat microwave oven convection Model 588     Boat
9        Puma office chair ergonomic Model 591     Puma

In [95]:
clean_df.head()

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail,Data_Source,brand
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,NaN,3.7,3241,croma,<NA>,2 Days,<NA>,<NA>,CSV,HP
1,microwave oven convection,Samsung microwave oven convection Model 524,22546.5,NaN,4.7,1294,amazon,<NA>,Free Delivery,<NA>,<NA>,CSV,Samsung
2,power bank fast charging,Samsung power bank fast charging Model 402,26131.0,NaN,3.9,3070,croma,<NA>,Free Delivery,<NA>,<NA>,CSV,Samsung
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,NaN,4.7,3446,flipkart,<NA>,Free Delivery,<NA>,<NA>,CSV,Dell
4,men running shoes,Dell men running shoes Model 536,2176.0,NaN,3.8,2031,croma,<NA>,5 Days,<NA>,<NA>,CSV,Dell

In [96]:
clean_df["rank"] = clean_df["rating"].rank(
    method="dense",
    ascending=False
).astype("Int64")

In [97]:
print(
    clean_df[["rating", "rank"]].head(10)
)

   rating  rank
0     3.7    14
1     4.7     4
2     3.9    12
3     4.7     4
4     3.8    13
5     3.9    12
6     2.8    23
7     3.0    21
8     4.0    11
9     4.6     5

In [98]:
clean_df["visibility_score"] = (
    1 / clean_df["rank"]
) * 100

In [99]:
print(
    clean_df[["rank", "visibility_score"]].head(20)
)

    rank  visibility_score
0     14          7.142857
1      4              25.0
2     12          8.333333
3      4              25.0
4     13          7.692308
5     12          8.333333
6     23          4.347826
7     21          4.761905
8     11          9.090909
9      5              20.0
10    14          7.142857
11     2              50.0
12     6         16.666667
13     1             100.0
14    24          4.166667
15    14          7.142857
16    22          4.545455
17    22          4.545455
18    19          5.263158
19    18          5.555556

In [100]:
print(
    clean_df[
        clean_df["rank"].notna()
    ][[
        "title",
        "rank",
        "visibility_score"
    ]].head(20).to_string(index=False)
)

                                      title  rank  visibility_score
        HP office chair ergonomic Model 603    14          7.142857
Samsung microwave oven convection Model 524     4              25.0
 Samsung power bank fast charging Model 402    12          8.333333
   Dell microwave oven convection Model 877     4              25.0
           Dell men running shoes Model 536    13          7.692308
 Samsung power bank fast charging Model 562    12          8.333333
          Philips air fryer India Model 259    23          4.347826
   Philips office chair ergonomic Model 836    21          4.761905
   Boat microwave oven convection Model 588    11          9.090909
      Puma office chair ergonomic Model 591     5              20.0
           Boat men running shoes Model 859    14          7.142857
      Puma office chair ergonomic Model 417     2              50.0
    Dell power bank fast charging Model 575     6         16.666667
    Sony power bank fast charging Model 896     1             100.0
          Philips air fryer India Model 339    24          4.166667
        Philips men running shoes Model 418    14          7.142857
      LG power bank fast charging Model 382    22          4.545455
     HP microwave oven convection Model 409    22          4.545455
      Puma office chair ergonomic Model 198    19          5.263158
Samsung microwave oven convection Model 810    18          5.555556

In [101]:
print(
    "Ranked products:",
    clean_df["rank"].notna().sum()
)

print(
    "Missing visibility scores:",
    clean_df["visibility_score"].isna().sum()
)

Ranked products: 2285
Missing visibility scores: 0

In [102]:
clean_df["top_10_products"] = clean_df["rank"] <= 10

In [103]:
print(
    clean_df["top_10_products"]
    .value_counts(dropna=False)
)

top_10_products
True     1239
False    1046
Name: count, dtype: Int64

In [104]:
clean_df.head()

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail,Data_Source,brand,rank,visibility_score,top_10_products
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,NaN,3.7,3241,croma,<NA>,2 Days,<NA>,<NA>,CSV,HP,14,7.142857,False
1,microwave oven convection,Samsung microwave oven convection Model 524,22546.5,NaN,4.7,1294,amazon,<NA>,Free Delivery,<NA>,<NA>,CSV,Samsung,4,25.0,True
2,power bank fast charging,Samsung power bank fast charging Model 402,26131.0,NaN,3.9,3070,croma,<NA>,Free Delivery,<NA>,<NA>,CSV,Samsung,12,8.333333,False
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,NaN,4.7,3446,flipkart,<NA>,Free Delivery,<NA>,<NA>,CSV,Dell,4,25.0,True
4,men running shoes,Dell men running shoes Model 536,2176.0,NaN,3.8,2031,croma,<NA>,5 Days,<NA>,<NA>,CSV,Dell,13,7.692308,False

In [105]:
top10_percentage = clean_df["top_10_products"].mean() * 100

print(
    "Products in Top 10 (%):",
    round(top10_percentage, 2)
)

Products in Top 10 (%): 54.22

In [106]:
clean_df["price_range"] = pd.qcut(
    clean_df["price"],
    q=4,
    labels=["Budget", "Mid Range", "Premium", "Luxury"]
)

In [107]:
print(clean_df["price_range"].value_counts(dropna=False))

price_range
Premium      615
Budget       572
Mid Range    571
Luxury       527
Name: count, dtype: int64

In [108]:
print(clean_df[["price", "price_range"]].head(20))

      price price_range
0   36225.0      Luxury
1   22546.5     Premium
2   26131.0      Luxury
3    2507.0   Mid Range
4    2176.0   Mid Range
5    5331.0     Premium
6   23754.5     Premium
7    4564.0   Mid Range
8   21830.0     Premium
9   19233.0     Premium
10  20381.0     Premium
11   8744.0     Premium
12  26131.0      Luxury
13   5150.0     Premium
14  45304.0      Luxury
15   9160.0     Premium
16  10945.0     Premium
17  17931.0     Premium
18  15160.0     Premium
19  22546.5     Premium

In [109]:
def parse_numeric(series):
    """Convert numbers such as '₹12,999', '$1,299.00', '1.2K' to numeric.
    Ambiguous values such as 'many' and 'Not Available' become NaN.
    """
    def one(value):
        if pd.isna(value):
            return np.nan
        if isinstance(value, (int, float, np.integer, np.floating)):
            return float(value) if np.isfinite(value) else np.nan
        s = str(value).strip().lower().replace(",", "")
        if s in {"", "na", "n/a", "nan", "none", "null", "many", "not available", "unknown", "-"}:
            return np.nan
        multiplier = 1.0
        if re.search(r"\d\s*k\b", s):
            multiplier = 1_000.0
            s = re.sub(r"(?<=\d)\s*k\b", "", s)
        elif re.search(r"\d\s*m\b", s):
            multiplier = 1_000_000.0
            s = re.sub(r"(?<=\d)\s*m\b", "", s)
        s = re.sub(r"[^0-9.\-]", "", s)
        if s in {"", "-", ".", "-.", "--"}:
            return np.nan
        try:
            return float(s) * multiplier
        except ValueError:
            return np.nan

    return series.map(one).astype("float64")


def clean_title(series):
    s = series.astype("string")

    # Remove repeated exclamation and hash symbols
    s = s.str.replace(r"!+", "", regex=True)
    s = s.str.replace(r"#+", "", regex=True)

    # Remove emojis using Unicode code points
    s = s.map(
        lambda x: (
            "".join(
                char for char in x
                if not (
                    0x1F300 <= ord(char) <= 0x1FAFF
                )
            )
            if pd.notna(x)
            else pd.NA
        ),
        na_action=None
    ).astype("string")

    # Normalize extra spaces
    s = s.str.replace(r"\s+", " ", regex=True).str.strip()

    # Convert empty titles to missing values
    return s.replace("", pd.NA)


def clean_category(series, default="Unknown"):
    s = series.astype("string").str.strip().str.replace(r"\s+", " ", regex=True)
    s = s.replace("", pd.NA).fillna(default)
    return s


def clean_platform(series):
    s = clean_category(series).str.lower()
    s = s.str.replace(r"\s+", " ", regex=True).str.strip()
    aliases = {
        "amazon.com": "amazon",
        "amazon.in": "amazon",
        "flipkart.com": "flipkart",
        "croma.com": "croma",
        "reliance digital": "reliance digital",
    }
    return s.replace(aliases)

In [110]:
# 1. KNOWN BRANDS

KNOWN_BRANDS = [
    "Hewlett Packard", "HP", "Samsung", "Apple", "Microsoft",
    "Lenovo", "Dell", "LG", "Sony", "Asus", "Acer", "MSI",
    "Razer", "Alienware", "Google", "Motorola", "OnePlus",
    "Xiaomi", "Redmi", "Realme", "Oppo", "Vivo", "Nokia",
    "Nothing", "Panasonic", "Toshiba", "Whirlpool", "Bosch",
    "Haier", "Godrej", "IFB", "Voltas", "Daikin", "Carrier",
    "Hitachi", "Blue Star", "Lloyd", "Mitsubishi", "Philips",
    "Bajaj", "Havells", "Usha", "Orient", "Crompton",
    "Prestige", "Pigeon", "Wonderchef", "Dyson", "Eureka Forbes",
    "Kent", "Aquaguard", "Canon", "Nikon", "Fujifilm", "JBL",
    "Bose", "Boat", "boAt", "Jabra", "Sennheiser", "Logitech",
    "TP-Link", "Netgear", "Epson", "Brother", "Puma", "Nike",
    "Adidas", "Reebok", "Ikea", "Wakefit", "Sleepwell",
    "Urban Ladder", "Nilkamal", "Cello", "Whiteduck"
]

# 2. BRAND ALIASES

BRAND_ALIASES = {
    "hewlett packard": "HP",
    "hp": "HP",
    "boat": "boAt",
    "redmi": "Xiaomi"
}

# 3. GENERIC WORDS

GENERIC_START_WORDS = {
    "best", "new", "portable", "wireless", "smart",
    "electric", "digital", "premium", "heavy", "office",
    "ergonomic", "gaming", "convection", "microwave",
    "laptop", "television", "tv", "phone", "washer",
    "fridge", "refrigerator", "table", "chair", "air",
    "power", "men", "women", "home", "kitchen", "large",
    "small", "medium", "automatic", "inverter", "mini",
    "inch", "inches", "modern", "model", "series", "ge",
    "black", "steel", "plastic", "wooden", "pack", "combo",
    "bundle", "unknown", "union", "cuft", "cm", "mm", "k",
    "kg", "gm", "mg", "ml", "gb", "tb", "mah", "watt", "GE",
    "volt", "hz", "tablet", "universal", "replacement", "K"
}

# Match longer brand names first
KNOWN_BRANDS_SORTED = sorted(
    set(KNOWN_BRANDS),
    key=len,
    reverse=True
)

# 4. BRAND EXTRACTION FUNCTION

def extract_brand(title):

    if pd.isna(title):
        return "Unknown"

    title = str(title).strip()

    if not title:
        return "Unknown"

    matches = []

    for brand in KNOWN_BRANDS_SORTED:

        pattern = (
            r"(?<![A-Za-z0-9])"
            + re.escape(brand)
            + r"(?![A-Za-z0-9])"
        )

        match = re.search(
            pattern,
            title,
            flags=re.IGNORECASE
        )

        if match:
            canonical = BRAND_ALIASES.get(
                brand.lower(),
                brand
            )

            matches.append(
                (match.start(), -len(brand), canonical)
            )

    # Prefer the earliest brand mention; longer match wins
    # if two matches start at the same position.
    if matches:
        matches.sort()
        return matches[0][2]

    # Conservative fallback: first token only
    # if it is not a generic product-description word.
    tokens = re.findall(
        r"[A-Za-z][A-Za-z0-9&.+-]*",
        title
    )

    if tokens and tokens[0].lower() not in GENERIC_START_WORDS:
        return tokens[0]

    return "Unknown"


# 5. CHECK REQUIRED COLUMNS

required_columns = [
    "title", "Keyword", "platform"
]

missing_columns = [
    col for col in required_columns
    if col not in clean_df.columns
]

if missing_columns:
    raise KeyError(
        f"Missing required columns: {missing_columns}"
    )

# Keep a backup of the existing brand column
if "brand" in clean_df.columns:
    clean_df["brand_original"] = clean_df["brand"].copy()

# ==========================================
# 6. CLEAN TITLE AND RE-EXTRACT BRAND
# ==========================================

clean_df["title"] = (
    clean_df["title"]
    .astype("string")
    .str.strip()
)

clean_df["brand"] = (
    clean_df["title"]
    .map(extract_brand)
    .astype("string")
)

# ==========================================
# 7. FLAG SUSPICIOUS BRAND VALUES
# ==========================================

SUSPICIOUS_WORDS = {
    "small", "medium", "large", "xl", "xxl", "mini",
    "big", "cu", "inch", "inches", "cm", "mm", "feet",
    "ft", "cuft", "kg", "kgs", "gram", "grams", "gm",
    "mg", "liter", "litre", "liters", "litres", "ml",
    "pack", "packs", "piece", "pieces", "pcs", "att",
    "set", "combo", "bundle", "pair", "count", "gb",
    "tb", "mb", "mah", "watt", "watts", "kw", "volt",
    "volts", "hz", "mp", "mpx", "modern", "series",
    "wireless", "wired", "bluetooth", "rechargeable",
    "portable", "foldable", "ergonomic", "adjustable",
    "digital", "electric", "automatic", "manual",
    "stainless", "steel", "plastic", "wooden", "black",
    "premium", "classic", "standard", "regular", "cafe",
    "model", "heavy", "duty", "new", "latest", "original",
    "tablet", "universal", "compatible", "replacement",
    "unknown", "union", "K", "ge", "GE", "k"
}

brand_normalized = (
    clean_df["brand"]
    .astype("string")
    .str.strip()
    .str.lower()
)

# Flag exact generic matches, excluding Unknown from this flag
suspicious_mask = (
    brand_normalized.isin(SUSPICIOUS_WORDS)
    & brand_normalized.ne("unknown")
)

# Convert suspicious fallback values to Unknown
clean_df.loc[suspicious_mask, "brand"] = "Unknown"

# ==========================================
# 8. DISPLAY SUSPICIOUS / UNKNOWN RECORDS
# ==========================================

unknown_mask = (
    clean_df["brand"]
    .astype("string")
    .str.strip()
    .str.lower()
    .eq("unknown")
)

print("=" * 60)
print("BRAND CLEANING SUMMARY")
print("=" * 60)

print("Total rows:", len(clean_df))
print("Distinct identified brands:",
      clean_df.loc[~unknown_mask, "brand"].nunique())
print("Unknown brand rows:", int(unknown_mask.sum()))

print("\nBrand frequency:")
display(
    clean_df["brand"]
    .value_counts()
    .rename_axis("brand")
    .reset_index(name="count")
    .head(50)
)

print("\nUnknown brand records for manual inspection:")
display(
    clean_df.loc[
        unknown_mask,
        ["Keyword", "title", "brand", "platform"]
    ].head(100)
)

print("\nSuspicious values detected before replacement:")
display(
    clean_df.loc[
        suspicious_mask,
        ["Keyword", "title", "brand_original", "platform"]
    ].head(100)
)

# ==========================================
# 9. CHECK DUPLICATES WITHOUT DELETING
# ==========================================

duplicate_columns = [
    "Keyword", "title", "platform", "price"
]

if all(col in clean_df.columns for col in duplicate_columns):

    duplicate_mask = clean_df.duplicated(
        subset=duplicate_columns,
        keep="first"
    )

    print("\nDuplicate rows detected:",
          int(duplicate_mask.sum()))

    display(
        clean_df.loc[
            duplicate_mask,
            ["Keyword", "title", "brand", "platform", "price"]
        ].head(50)
    )

print("\nBrand cleaning complete. No rows were deleted.")

============================================================
BRAND CLEANING SUMMARY
============================================================
Total rows: 2285
Distinct identified brands: 187
Unknown brand rows: 101

Brand frequency:

          brand  count
0       Samsung    226
1            HP    216
2            LG    197
3       Philips    145
4          Dell    137
5          Puma    136
6          boAt    135
7          Nike    135
8          Sony    134
9       Unknown    101
10        Apple     63
11        Canon     61
12       Lenovo     33
13      Costway     29
14       Google     21
15    Whirlpool     19
16     Insignia     17
17     Hamilton     15
18        Epson     15
19   Frigidaire     14
20        Retro     14
21      Brother     14
22    Microsoft     13
23    Mainstays     13
24          Onn     12
25       Maiden     11
26       Amazon     10
27    Nostalgia      9
28     Fujifilm      9
29         Acer      8
30      Staples      8
31     Insta360      7
32         Roku      6
33     Hotpoint      6
34        Haier      6
35         Ikea      6
36         Asus      5
37    Panasonic      5
38        Vizio      5
39     Motorola      5
40       Maytag      5
41          OSP      5
42        Zokop      4
43  BLACKDECKER      4
44      Kenmore      4
45       Galanz      4
46       Tacool      4
47      Contixo      4
48       LINSAY      4
49   Sharecloud      4

Unknown brand records for manual inspection:

,Keyword,title,brand,platform
1242,laptop,16 inch Laptop ComputerIntel Core i516GB RAM 5...,Unknown,walmart - tpv tech
1265,laptop,156 inch Laptop12GB RAM 256gb SSDWindows 11 Pr...,Unknown,walmart - tpv tech
1272,laptop,Laptop,Unknown,fab by epic games
1315,laptop,156 Gaming LaptopIPS Fhd AMD Ryzen 7 8745hs Ra...,Unknown,walmart - esoor
1335,laptop,16 inch Laptop ComputerIntel Core i516GB RAM 5...,Unknown,walmart - tpv tech
...,...,...,...,...
2078,chair,Union Scale FlexFit Dexley Mesh Task Chair Blu...,Unknown,walmart - myofficeinnovations
2099,camera,Mini Action Camera 64gb Thumb POV Portable Bod...,Unknown,walmart - lacrtope
2110,camera,Bundle Osmo Action 6 Adventure Combo with DJI ...,Unknown,best buy
2132,camera,Mini Action Camera 64gb Thumb POV Portable Bod...,Unknown,walmart - lacrtope
2229,printer,Wireless Printer A4 Thermal Printer Monochrome...,Unknown,walmart - baokaler

Suspicious values detected before replacement:

,Keyword,title,brand_original,platform
1477,phone,Att iPhone 17 Pro Max 256gb Deep Blue Size 256 GB,Att,walmart
1512,phone,Att iPhone 17 Pro Max 256gb Deep Blue Size 256 GB,Att,walmart
1577,washing machine,45 Cu Ft Ultra Large Front Load Washer,45,southern appliances
1580,washing machine,50 cu ft Mega Capacity Smart Front Load Washer...,50,valley oak home appliance center
1581,washing machine,50 cu ft Mega Capacity Smart Front Load Washer...,50,bill & rods appliances
1582,washing machine,50 cu ft Mega Capacity Smart Front Load Washer...,50,johnson's appliances & bedding
1584,washing machine,50 cu ft Mega Capacity Smart Front Load Washer...,50,kelsey's appliance
1586,washing machine,50 cu ft Mega Capacity Smart Front Load Washer...,50,albo appliance
1616,washing machine,50 cu ft Mega Capacity Smart Front Load Washer...,50,albo appliance
1665,microwave,09 Cu ft Countertop Microwave in Blue,09,walmart
1727,microwave,Cafe 15 Cu Ft Smart Countertop ConvectionMicro...,Cafe,brandsmart usa
1737,microwave,Big Chill Retro Microwave 16 cu ft,Big,big chill
1757,fridge,31 Cu Ft Two Door Mini Fridge W Freezer Revers...,31,ebay - tradepost898
1758,fridge,32 Cu Ft Two Door Mini Fridge With Freezer Rev...,32,ebay - tradepost898
1759,fridge,46 Cu ft Two Door Mini Refrigerator with Freez...,46,trending deals
1761,fridge,31 Cu Ft Compact TwoDoor Mini Fridge With Free...,31,praktijkzinnia.be
1765,fridge,31 Cu Ft Mini Fridge With Freezer Stainless St...,31,ebay - jslellc
1797,fridge,31 Cu Ft Two Door Mini Fridge W Freezer Revers...,31,ebay - tradepost898
1798,fridge,32 Cu Ft Two Door Mini Fridge With Freezer Rev...,32,ebay - tradepost898
1799,fridge,46 Cu ft Two Door Mini Refrigerator with Freez...,46,trending deals
1801,fridge,31 Cu Ft Compact TwoDoor Mini Fridge With Free...,31,praktijkzinnia.be
1805,fridge,31 Cu Ft Mini Fridge With Freezer Stainless St...,31,ebay - jslellc
1838,fridge,Big Chill Classic Fridge Color Brushed Brass,Big,big chill

Duplicate rows detected: 223

,Keyword,title,brand,platform,price
851,men running shoes,Boat men running shoes Model 401,boAt,reliance digital,22065.00
1201,office chair ergonomic,Philips office chair ergonomic Model 798,Philips,flipkart,23925.50
1205,air fryer India,Philips air fryer India Model 269,Philips,flipkart,23754.50
1210,air fryer India,HP air fryer India Model 947,HP,croma,26570.00
1220,air fryer India,Philips air fryer India Model 213,Philips,amazon,23754.50
1223,office chair ergonomic,Philips office chair ergonomic Model 733,Philips,flipkart,2022.00
1224,men running shoes,Sony men running shoes Model 584,Sony,croma,22065.00
1228,office chair ergonomic,Philips office chair ergonomic Model 414,Philips,amazon,12081.00
1232,office chair ergonomic,LG office chair ergonomic Model 829,LG,amazon,48662.00
1233,air fryer India,LG air fryer India Model 363,LG,croma,10393.00
1275,laptop,Microsoft Surface Laptop Copilot PC 138 Snapdr...,Microsoft,microsoft store,1399.99
1276,laptop,Apple MacBook Neo 13 A18 Pro chip,Apple,target,699.99
1277,laptop,Alienware 15 DA15265 153 Gaming Laptop Computer,Alienware,walmart,899.00
1278,laptop,Lenovo Yoga 7 16ILL10 Copilot PC 2in1 Laptop C...,Lenovo,best buy,799.99
1279,laptop,Dell 156 Touchscreen Laptop Intel Core i5 Proc...,Dell,lowe's,539.99
1280,laptop,GeekBook M16 Laptop Intel Ultra,GeekBook,geekompc.com,849.00
1281,laptop,Microsoft 13 Surface Laptop Copilot PC,Microsoft,nfm,1239.99
1282,laptop,Lenovo IdeaPad Slim 3x 153 Touchscreen Copilot...,Lenovo,lenovo,779.99
1283,laptop,NIMO 173 AI Laptop AMD Ryzen AI 9 HX 370 Radeo...,NIMO,nimo,1399.99
1284,laptop,Microsoft Surface Pro 13 Snapdragon X2 Plus,Microsoft,b&h photo-video-audio,1599.99
1286,laptop,LG gram Book 16 Inch Copilot PC Windows 11 Hom...,LG,best buy,999.99
1290,laptop,Dell Plus 16 2in1 16 Touchscreen Laptop,Dell,newegg.com - rockystone,909.99
1291,laptop,MSI 16 Vector 16 HX AI Gaming Laptop,MSI,walmart - newegg inc.,2299.00
1292,laptop,Acer Chromebook 315 156 FHD Laptop with Google...,Acer,best buy,379.00
1294,laptop,ASUS 156 Vivobook 15 Touchscreen Laptop Intel ...,Asus,electronic express,749.99
1295,laptop,Microsoft Surface Laptop Copilot PC 138 Snapdr...,Microsoft,microsoft store,1499.99
1296,laptop,HP 840 G8core I51145g7 26ghz16gb Ram256gb,HP,target,440.99
1297,laptop,HP Stream 14 Laptop Intel Celeron N4120 4GB RA...,HP,walmart,229.99
1298,laptop,Apple MacBook Air M1 7core GPU,Apple,event link,250.00
1300,laptop,HP Intel i5 13th Gen Intel Iris Xe Graphics,HP,newegg.com - lone star computer,959.79
1303,laptop,Temlicolo 141 Laptop 8GB RAM PC 256GB SSD Inte...,Temlicolo,walmart - temlicolo tablet,269.99
1305,laptop,Jumper Laptop 156 Inch Computer 16GB DDR3 RAM ...,Jumper,best buy,329.98
1312,laptop,Acer Chromebook 315 156 FHD Laptop with Google...,Acer,best buy,379.00
1330,laptop,Hp 173 inch FHD IPS Notebook AMD Ryzen 5 7430u...,HP,walmart - antonline.com,479.99
1333,laptop,Temlicolo 141 Laptop 8GB RAM PC 256GB SSD Inte...,Temlicolo,walmart - temlicolo tablet,269.99
1335,laptop,16 inch Laptop ComputerIntel Core i516GB RAM 5...,Unknown,walmart - tpv tech,399.99
1392,television,Samsung Class M70HD Series Mini LED 4K UHD Sma...,Samsung,bj's wholesale club,327.99
1393,television,VIZIO Quantum 4K QLED HDR Smart TV,VIZIO,walmart,298.00
1394,television,Television by Roman Skaskiw Paperback,Unknown,books a million,5.38
1397,television,TV,Unknown,mercari.com,114.00
1402,television,Hiro Roku TV 720p HD Smart TV Flat Screen LED ...,Hiro,target,99.99
1403,television,Onn Class 4K UHD Powered by Vizio Smart Televi...,Onn,walmart,148.00
1405,television,Samsung Class M70hb Series Mini LED 4K UHD Sam...,Samsung,walmart,348.00
1410,television,Class LG QNED AI QNED7SB Mini LED 4K Smart TV ...,LG,best buy,349.99
1411,television,VIZIO Quantum 4K QLED HDR Smart TV,VIZIO,walmart,298.00
1431,television,Onn 32 in 1080p FHD Building Block Smart Roku ...,Onn,walmart,138.00
1488,phone,Apple iPhone 13 128GB 256GB BlueRed Unlocked V...,Apple,ebay - sarahcell,338.00
1489,phone,Apple iPhone 13 128GB 256GB BlueRed Unlocked V...,Apple,ebay - sarahcell,338.00
1494,phone,Apple iPhone 13 128GB 256GB BlueRed Unlocked V...,Apple,ebay - sarahcell,324.00
1495,phone,Apple iPhone 17 Pro Max,Apple,walmart - adopt-a-phone,1159.00

Brand cleaning complete. No rows were deleted.

In [111]:
print("Unknown brands:", 
      clean_df["brand"].eq("Unknown").sum())

print("Total rows:", len(clean_df))

display(
    clean_df.loc[
        clean_df["brand"].eq("Unknown"),
        ["Keyword", "title", "brand", "platform"]
    ].head(30)
)

Unknown brands: 101
Total rows: 2285

,Keyword,title,brand,platform
1242,laptop,16 inch Laptop ComputerIntel Core i516GB RAM 5...,Unknown,walmart - tpv tech
1265,laptop,156 inch Laptop12GB RAM 256gb SSDWindows 11 Pr...,Unknown,walmart - tpv tech
1272,laptop,Laptop,Unknown,fab by epic games
1315,laptop,156 Gaming LaptopIPS Fhd AMD Ryzen 7 8745hs Ra...,Unknown,walmart - esoor
1335,laptop,16 inch Laptop ComputerIntel Core i516GB RAM 5...,Unknown,walmart - tpv tech
1349,laptop,173 Gaming Laptop AMD Ryzen 9 8945hs Beats i91...,Unknown,walmart - ruly
1372,television,TV,Unknown,mercari.com
1376,television,Television by Roman Skaskiw Paperback,Unknown,books a million
1379,television,TV,Unknown,mercari.com
1382,television,50 4K UHD Smart TV,Unknown,fpd
1383,television,tv flat screen,Unknown,mercari.com
1385,television,Digital Television Technology and Standards,Unknown,books a million
1386,television,tv,Unknown,mercari.com
1394,television,Television by Roman Skaskiw Paperback,Unknown,books a million
1397,television,TV,Unknown,mercari.com
1477,phone,Att iPhone 17 Pro Max 256gb Deep Blue Size 256 GB,Unknown,walmart
1512,phone,Att iPhone 17 Pro Max 256gb Deep Blue Size 256 GB,Unknown,walmart
1523,washing machine,GE 45 Cu Ft Capacity Washer with Water Level C...,Unknown,mazer appliance
1542,washing machine,GE Profile 50 Cu Ft Top Load Washer with Smart...,Unknown,ace family hardware
1559,washing machine,GE 5cu ft High Efficiency TopLoad Washer Diamo...,Unknown,littlewoods
1565,washing machine,Mini Wash Machine Compact Twin Tub Top Load Wa...,Unknown,ebay - 1soundandfury
1566,washing machine,GE 32 in 48 cu ft White Front Load Washing Mac...,Unknown,littlewoods
1577,washing machine,45 Cu Ft Ultra Large Front Load Washer,Unknown,southern appliances
1579,washing machine,GE 50 cu ft Smart Front Load Steam Washer with...,Unknown,appliance center | sleep shop
1580,washing machine,50 cu ft Mega Capacity Smart Front Load Washer...,Unknown,valley oak home appliance center
1581,washing machine,50 cu ft Mega Capacity Smart Front Load Washer...,Unknown,bill & rods appliances
1582,washing machine,50 cu ft Mega Capacity Smart Front Load Washer...,Unknown,johnson's appliances & bedding
1583,washing machine,GE 40 Cu Ft HighEfficiency Top Load Washer wit...,Unknown,ohiofurnitureusa.com
1584,washing machine,50 cu ft Mega Capacity Smart Front Load Washer...,Unknown,kelsey's appliance
1585,washing machine,41 Cuft Top Load Washer With Agitator Slamproo...,Unknown,hd supply

In [112]:
# Count before removal
before = len(clean_df)

# Remove rows with Unknown or missing brands
clean_df = clean_df.loc[
    clean_df["brand"].astype("string").str.strip().str.lower().ne("unknown")
    & clean_df["brand"].notna()
].copy()

# Check results
print("Rows before:", before)
print("Rows removed:", before - len(clean_df))
print("Rows remaining:", len(clean_df))
print(
    "Unknown brands remaining:",
    clean_df["brand"].astype("string").str.strip().str.lower().eq("unknown").sum()
)

Rows before: 2285
Rows removed: 101
Rows remaining: 2184
Unknown brands remaining: 0

In [113]:
clean_df["brand"].info()

<class 'pandas.Series'>
Index: 2184 entries, 0 to 2284
Series name: brand
Non-Null Count  Dtype
--------------  -----
2184 non-null   string
dtypes: string(1)
memory usage: 44.8 KB

In [114]:
clean_df.dropna(subset=["brand"], inplace=True)

In [115]:
clean_df["brand"].isnull().sum()

np.int64(0)

In [116]:
duplicates = clean_df[
    clean_df.duplicated(keep=False)
].sort_values("title")

duplicates.head(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail,Data_Source,brand,rank,visibility_score,top_10_products,price_range,brand_original
971,air fryer India,Philips air fryer India Model 213,23754.5,NaN,4.4,2655,amazon,<NA>,2 Days,<NA>,<NA>,CSV,Philips,7,14.285714,True,Premium,Philips
1220,air fryer India,Philips air fryer India Model 213,23754.5,NaN,4.4,2655,amazon,<NA>,2 Days,<NA>,<NA>,CSV,Philips,7,14.285714,True,Premium,Philips

In [117]:
clean_df = clean_df.drop_duplicates().reset_index(drop=True)

print("Shape after removing duplicates:", clean_df.shape)

Shape after removing duplicates: (2183, 18)

In [118]:
duplicates = clean_df[
    clean_df.duplicated(keep=False)
].sort_values("title")

duplicates.head(10)

Empty DataFrame
Columns: [Keyword, title, price, raw_price, rating, Reviews, platform, position, Delivery, Link, thumbnail, Data_Source, brand, rank, visibility_score, top_10_products, price_range, brand_original]
Index: []

In [119]:
clean_df.to_csv(
    "cleaned_dataset.csv",
    index=False
)

print("Final cleaned data saved to 'cleaned_dataset.csv'")
print("Final cleaned data shape:", clean_df.shape)

Final cleaned data saved to 'cleaned_dataset.csv'
Final cleaned data shape: (2183, 18)

In [120]:
import sqlite3

In [121]:
conn = sqlite3.connect("brand_visibility_data.db")

In [122]:
clean_df.to_sql(
    "products",
    conn,
    if_exists="replace",
    index=False
)

2183

In [123]:
query = """
SELECT COUNT(*) AS total_products
FROM products;
"""
result = pd.read_sql_query(query, conn)

print(result)

   total_products
0            2183

In [124]:
query = """
SELECT * FROM products
LIMIT 10;
"""
result = pd.read_sql_query(query, conn)
print(result)

                     Keyword                                        title  \
0     office chair ergonomic          HP office chair ergonomic Model 603
1  microwave oven convection  Samsung microwave oven convection Model 524
2   power bank fast charging   Samsung power bank fast charging Model 402
3  microwave oven convection     Dell microwave oven convection Model 877
4          men running shoes             Dell men running shoes Model 536
5   power bank fast charging   Samsung power bank fast charging Model 562
6            air fryer India            Philips air fryer India Model 259
7     office chair ergonomic     Philips office chair ergonomic Model 836
8  microwave oven convection     Boat microwave oven convection Model 588
9     office chair ergonomic        Puma office chair ergonomic Model 591

     price raw_price  rating  Reviews          platform position  \
0  36225.0      None     3.7     3241             croma     None
1  22546.5      None     4.7     1294            amazon     None
2  26131.0      None     3.9     3070             croma     None
3   2507.0      None     4.7     3446          flipkart     None
4   2176.0      None     3.8     2031             croma     None
5   5331.0      None     3.9     4124  reliance digital     None
6  23754.5      None     2.8     1761             croma     None
7   4564.0      None     3.0     1540            amazon     None
8  21830.0      None     4.0      126             croma     None
9  19233.0      None     4.6     3911  reliance digital     None

        Delivery  Link thumbnail Data_Source    brand  rank  visibility_score  \
0         2 Days  None      None         CSV       HP    14          7.142857
1  Free Delivery  None      None         CSV  Samsung     4         25.000000
2  Free Delivery  None      None         CSV  Samsung    12          8.333333
3  Free Delivery  None      None         CSV     Dell     4         25.000000
4         5 Days  None      None         CSV     Dell    13          7.692308
5         5 Days  None      None         CSV  Samsung    12          8.333333
6         5 Days  None      None         CSV  Philips    23          4.347826
7  Free Delivery  None      None         CSV  Philips    21          4.761905
8  Free Delivery  None      None         CSV     boAt    11          9.090909
9         5 Days  None      None         CSV     Puma     5         20.000000

   top_10_products price_range brand_original
0                0      Luxury             HP
1                1     Premium        Samsung
2                0      Luxury        Samsung
3                1   Mid Range           Dell
4                0   Mid Range           Dell
5                0     Premium        Samsung
6                0     Premium        Philips
7                0   Mid Range        Philips
8                0     Premium           Boat
9                1     Premium           Puma

In [125]:
pd.read_sql("PRAGMA table_info(products);", conn)

    cid              name     type  notnull dflt_value  pk
0     0           Keyword     TEXT        0       None   0
1     1             title     TEXT        0       None   0
2     2             price     REAL        0       None   0
3     3         raw_price     REAL        0       None   0
4     4            rating     REAL        0       None   0
5     5           Reviews  INTEGER        0       None   0
6     6          platform     TEXT        0       None   0
7     7          position  INTEGER        0       None   0
8     8          Delivery     TEXT        0       None   0
9     9              Link     TEXT        0       None   0
10   10         thumbnail     TEXT        0       None   0
11   11       Data_Source     TEXT        0       None   0
12   12             brand     TEXT        0       None   0
13   13              rank  INTEGER        0       None   0
14   14  visibility_score     REAL        0       None   0
15   15   top_10_products  INTEGER        0       None   0
16   16       price_range     TEXT        0       None   0
17   17    brand_original     TEXT        0       None   0

EDA Questions

🟦 General Market Analysis

Ques.1. How many total products are available per keyword?

In [126]:
query = """
SELECT 
    keyword,
    COUNT(*) AS total_products
FROM products
GROUP BY keyword
ORDER BY total_products DESC;
"""
result = pd.read_sql_query(query, conn)

print(result)

                      Keyword  total_products
0   microwave oven convection             262
1           men running shoes             245
2    power bank fast charging             243
3             air fryer India             243
4      office chair ergonomic             241
5                     printer             118
6                      tablet             114
7                      laptop             110
8                   microwave             101
9                       chair              99
10                     fridge              89
11            washing machine              84
12                 television              81
13                      phone              78
14                     camera              75

Ques.2. What is the overall average price of products?

In [127]:
query = """
SELECT 
    ROUND(AVG(price), 2) AS average_price
FROM products
WHERE price IS NOT NULL;
"""
result = pd.read_sql_query(query, conn)
print(result)

   average_price
0       13882.93

Ques.3. What is the distribution of price across all products?

In [128]:
query = """
SELECT
    CASE
        WHEN price < 1000 THEN 'Below 1000'
        WHEN price < 5000 THEN '1000 - 4999'
        WHEN price < 10000 THEN '5000 - 9999'
        WHEN price < 25000 THEN '10000 - 24999'
        WHEN price < 50000 THEN '25000 - 49999'
        WHEN price < 100000 THEN '50000 - 99999'
        ELSE '100000+'
    END AS price_bucket,
    COUNT(*) AS product_count
FROM products
WHERE price IS NOT NULL
  AND price > 0
GROUP BY price_bucket
ORDER BY
    CASE price_bucket
        WHEN 'Below 1000' THEN 1
        WHEN '1000 - 4999' THEN 2
        WHEN '5000 - 9999' THEN 3
        WHEN '10000 - 24999' THEN 4
        WHEN '25000 - 49999' THEN 5
        WHEN '50000 - 99999' THEN 6
        WHEN '100000+' THEN 7
    END;
"""
result = pd.read_sql_query(query, conn)
print(result)

    price_bucket  product_count
0     Below 1000            823
1    1000 - 4999            222
2    5000 - 9999            111
3  10000 - 24999            516
4  25000 - 49999            511

Ques.4. What is the average rating across all products?

In [129]:
query = """
SELECT 
    ROUND(AVG(rating), 2) AS average_rating
FROM products
WHERE rating IS NOT NULL;
"""
result = pd.read_sql_query(query, conn)
print(result)

   average_rating
0            3.98

Ques.5. How are reviews distributed (low vs high engagement products)?

In [130]:
query = """
SELECT
    CASE
        WHEN Reviews < 100 THEN 'Low Engagement'
        WHEN Reviews < 1000 THEN 'Medium Engagement'
        ELSE 'High Engagement'
    END AS engagement_level,
    COUNT(*) AS product_count
FROM products
WHERE Reviews IS NOT NULL
    AND Reviews >= 0
GROUP BY engagement_level
ORDER BY
    CASE engagement_level
        WHEN 'Low Engagement' THEN 1
        WHEN 'Medium Engagement' THEN 2
        WHEN 'High Engagement' THEN 3
    END;
"""
result = pd.read_sql_query(query, conn)
print(result)

    engagement_level  product_count
0     Low Engagement            214
1  Medium Engagement            540
2    High Engagement           1212

🟩 Brand Analysis

Ques.6. Which brand appears most frequently?

In [131]:
query = """
SELECT
    brand,
    COUNT(*) AS product_count
FROM products
WHERE brand IS NOT NULL
GROUP BY brand
ORDER BY product_count DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

       brand  product_count
0    Samsung            226
1         HP            216
2         LG            197
3    Philips            144
4       Dell            137
..       ...            ...
182      Ave              1
183    Armor              1
184  Android              1
185   Amelia              1
186    Amana              1

[187 rows x 2 columns]

Ques.7. Which brand has the highest average visibility_score?

In [132]:
query = """
SELECT
    brand,
    ROUND(AVG(visibility_score), 2) AS average_visibility_score
FROM products
WHERE visibility_score IS NOT NULL
    AND brand IS NOT NULL
GROUP BY brand
ORDER BY average_visibility_score DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

         brand  average_visibility_score
0      Vicenza                    100.00
1       Swivel                    100.00
2        Retro                    100.00
3          Rae                    100.00
4      Papasan                    100.00
..         ...                       ...
182      Nuisk                      4.17
183  Realspace                      4.13
184    Veat00l                      4.00
185    COSTWAY                      3.33
186  Calliever                      2.94

[187 rows x 2 columns]

Ques.8. What is the average position (ranking) per brand?

In [133]:
query = """
SELECT
    brand,
    ROUND(AVG(rank), 2) AS avg_position
FROM products
WHERE rank IS NOT NULL
    AND brand IS NOT NULL
GROUP BY brand
ORDER BY avg_position ASC;
"""
result = pd.read_sql_query(query, conn)
print(result)

         brand  avg_position
0      Android          1.00
1        Britt          1.00
2         Fuji          1.00
3       Galaxy          1.00
4        Gopro          1.00
..         ...           ...
182      Nuisk         24.00
183  Realspace         24.33
184    Veat00l         25.00
185    COSTWAY         30.00
186  Calliever         34.00

[187 rows x 2 columns]

Ques.9. Which brands appear most in top 10 positions (position <= 10)?

In [134]:
query = """
SELECT
    brand,
    COUNT(*) AS top_10_products
FROM products
WHERE brand IS NOT NULL
    AND rank IS NOT NULL
    AND rank <= 10
GROUP BY brand
ORDER BY top_10_products DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

       brand  top_10_products
0    Samsung              113
1         HP               98
2         LG               87
3       Dell               64
4       Sony               62
..       ...              ...
147      BLU                1
148      Ave                1
149    Armor                1
150  Android                1
151   Amelia                1

[152 rows x 2 columns]

Ques.10. Which brands have the highest average rating?

In [135]:
query = """
SELECT
    brand,
    ROUND(AVG(rating), 2) AS average_rating
FROM products
WHERE brand IS NOT NULL
    AND rating IS NOT NULL
    AND rating BETWEEN 1 AND 5
GROUP BY brand
ORDER BY average_rating DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

         brand  average_rating
0      Vicenza            5.00
1       Swivel            5.00
2        Retro            5.00
3          Rae            5.00
4      Papasan            5.00
..         ...             ...
182      Nuisk            2.70
183  Realspace            2.67
184    Veat00l            2.60
185    COSTWAY            2.00
186  Calliever            1.40

[187 rows x 2 columns]

🟨 Pricing Analysis

Ques.11. What is the price distribution across different brands?

In [136]:
query = """
SELECT
    brand,
    ROUND(AVG(price), 2) AS average_price,
    ROUND(MIN(price), 2) AS min_price,
    ROUND(MAX(price), 2) AS max_price,
    COUNT(price) AS priced_products
FROM products
WHERE brand IS NOT NULL
    AND price IS NOT NULL
    AND price > 0
GROUP BY brand
ORDER BY average_price DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

          brand  average_price  min_price  max_price  priced_products
0          Puma       25416.87     889.00   49325.00              136
1          Nike       23490.31     509.00   49953.00              135
2          boAt       23180.49    1312.00   49612.00              135
3       Philips       23059.64     148.00   49516.00              144
4          Dell       22095.95     385.00   49421.00              137
..          ...            ...        ...        ...              ...
182      Rongta          36.99      36.99      36.99                3
183  Microondas          31.32      31.32      31.32                1
184    Tracfone          19.88      19.88      19.88                1
185        Fuji          12.50      12.50      12.50                1
186       Eaton           8.25       8.25       8.25                1

[187 rows x 5 columns]

Ques.12. How are products distributed across price_range categories?

In [137]:
query = """
SELECT
    price_range,
    COUNT(*) AS product_count
FROM products
WHERE price_range IS NOT NULL
GROUP BY price_range
ORDER BY
    CASE price_range
        WHEN 'Budget' THEN 1
        WHEN 'Mid Range' THEN 2
        WHEN 'Premium' THEN 3
        WHEN 'Luxury' THEN 4
    END;
"""
result = pd.read_sql_query(query, conn)
print(result)

  price_range  product_count
0      Budget            512
1   Mid Range            531
2     Premium            613
3      Luxury            527

Ques.13. Do higher-priced products have better rankings (position)?

In [138]:
query = """
SELECT
    CASE
        WHEN price < 1000 THEN 'Below 1000'
        WHEN price < 5000 THEN '1000 - 4999'
        WHEN price < 10000 THEN '5000 - 9999'
        WHEN price < 25000 THEN '10000 - 24999'
        WHEN price < 50000 THEN '25000 - 49999'
        WHEN price < 100000 THEN '50000 - 99999'
        ELSE '100000+'
    END AS price_bucket,
    COUNT(*) AS ranked_products,
    ROUND(AVG(price), 2) AS avg_price,
    ROUND(AVG(position), 2) AS avg_position
FROM products
WHERE price IS NOT NULL
  AND price > 0
  AND position IS NOT NULL
GROUP BY price_bucket
ORDER BY avg_price;
"""

result = pd.read_sql_query(query, conn)
print(result)

  price_bucket  ranked_products  avg_price  avg_position
0   Below 1000              815     312.55         20.43
1  1000 - 4999              128    1949.54         22.53
2  5000 - 9999                6    6730.94         20.17

Ques.14. What is the average price per platform?

In [139]:
query = """
SELECT
    platform,
    ROUND(AVG(price), 2) AS average_price,
    COUNT(price) AS priced_products
FROM products
WHERE platform IS NOT NULL
    AND price IS NOT NULL
    AND price > 0
GROUP BY platform
ORDER BY average_price DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

                 platform  average_price  priced_products
0        reliance digital       25315.51              324
1                flipkart       24554.08              287
2                  amazon       23534.28              320
3                   croma       23041.50              303
4              connection        6989.28                1
..                    ...            ...              ...
276           dialrto.com          16.95                1
277      ebay - toto2-163          15.99                1
278     ebay - lamasdeals          12.50                1
279        masterpiece oü          12.00                1
280  wengers of myerstown           8.25                1

[281 rows x 3 columns]

Ques.15. Which products have the highest price within each keyword?

In [140]:
query = """
SELECT
    keyword,
    title,
    brand,
    price,
    platform
FROM products
WHERE price IS NOT NULL
    AND price > 0
    AND price = (SELECT MAX(p2.price)
        FROM products AS p2
        WHERE p2.keyword = products.keyword
          AND p2.price IS NOT NULL
          AND p2.price > 0)
ORDER BY keyword;
"""
result = pd.read_sql_query(query, conn)
print(result)

                      Keyword  \
0             air fryer India
1                      camera
2                      camera
3                       chair
4                      fridge
5                      laptop
6           men running shoes
7                   microwave
8   microwave oven convection
9      office chair ergonomic
10                      phone
11   power bank fast charging
12                    printer
13                     tablet
14                 television
15            washing machine

                                                title    brand     price  \
0                      Nike air fryer India Model 162     Nike  48988.00
1   Canon EOS R6 Mark III Mirrorless Camera with R...    Canon   4671.00
2   Canon EOS R6 Mark III Mirrorless Camera with R...    Canon   4671.00
3                               Knoll Barcelona Chair    Knoll   9110.25
4   ZLINE Autograph Edition 36 216 Cu ft Fingerpri...    ZLINE   3919.99
5                        Lenovo ThinkPad P1 Gen 8 21q   Lenovo   6989.28
6                 Samsung men running shoes Model 751  Samsung  49670.00
7                        Fisher Paykel Microwave Oven   Fisher    799.00
8         Samsung microwave oven convection Model 305  Samsung  49682.00
9               Sony office chair ergonomic Model 476     Sony  49990.00
10                             Samsung Galaxy Z Fold7  Samsung   2739.09
11            Nike power bank fast charging Model 373     Nike  49953.00
12           Zebra gx43 series printers GX43102712150    Zebra    878.22
13  Samsung Galaxy Tab S10 Ai Tablet Android Table...  Samsung   5963.05
14                      Samsung S95D OLED 4K Smart TV  Samsung   6710.18
15  Miele wxc280wcs WXC280 WCS Steam W1 Frontloadi...    Miele   1999.00

                           platform
0                          flipkart
1                       panamoz.com
2                       panamoz.com
3               design within reach
4              plesser's appliances
5                        connection
6                  reliance digital
7             designer home surplus
8                  reliance digital
9                             croma
10                     mcgrocer.com
11                         flipkart
12                      posguys.com
13  ebay - soundsolutions_worldwide
14                     voomi supply
15                         best buy

🟥 Discount & Offer Analysis

Ques.16. What percentage of products have a non-zero discount?

In [141]:
query = """
SELECT
    ROUND(
        100 * SUM(
            CASE
            WHEN raw_price IS NOT NULL
                AND raw_price > price
            THEN 1
            ELSE 0
        END
        ) / COUNT(*), 2)
    AS discounted_percentage
FROM products
WHERE price IS NOT NULL
    AND price > 0;
"""
result = pd.read_sql_query(query, conn)
print(result)

   discounted_percentage
0                    0.0

Ques.17. Do discounted products have better rankings (position)?

In [142]:
query = """
SELECT
    CASE
        WHEN raw_price > price THEN 'Discounted'
        ELSE 'Not Discounted'
    END AS discount_status,
    COUNT(*) AS product_count,
    ROUND(AVG(position), 2) AS avg_position
FROM products
WHERE price IS NOT NULL
    AND price > 0
    AND position IS NOT NULL
    AND raw_price IS NOT NULL
GROUP BY discount_status
ORDER BY avg_position ASC;
"""
result = pd.read_sql_query(query, conn)
print(result)

  discount_status  product_count  avg_position
0      Discounted              1           5.0
1  Not Discounted            921          20.7

Ques.18. Which brand offers the highest average discount?

In [143]:
query = """
SELECT 
    brand,
    ROUND(AVG(((raw_price - price) * 100.0) / raw_price),2) AS average_discount_percentage
FROM products
WHERE brand IS NOT NULL
    AND price IS NOT NULL
    AND price > 0
    AND raw_price IS NOT NULL
    AND raw_price > price
GROUP BY brand
ORDER BY average_discount_percentage DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

  brand  average_discount_percentage
0    LG                        99.37

Ques.19. Which platform provides the highest average discount?

In [144]:
query = """
SELECT 
    platform,
    ROUND(AVG(((raw_price - price) * 100.0) / raw_price),2) AS average_discount_percentage
FROM products
WHERE platform IS NOT NULL
    AND price IS NOT NULL
    AND price > 0
    AND raw_price IS NOT NULL
    AND raw_price > price
GROUP BY platform
ORDER BY average_discount_percentage DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

   platform  average_discount_percentage
0  lg parts                        99.37

Ques.20. Is there a relationship between discount and rating?

In [145]:
query = """
SELECT
    ROUND(AVG(((raw_price - price) * 100.0) / raw_price),2) AS discount_percentage,
    rating
FROM products
WHERE raw_price IS NOT NULL
    AND raw_price > price
    AND price IS NOT NULL
    AND price > 0
    AND rating IS NOT NULL
    AND rating BETWEEN 1 AND 5
ORDER BY discount_percentage DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

   discount_percentage  rating
0                99.37     1.2

🟪 Platform Analysis

Ques.21. Which platform lists the highest number of products?

In [146]:
query = """
SELECT 
    platform,
    COUNT(*) AS product_count
FROM products
WHERE platform IS NOT NULL
GROUP BY platform
ORDER BY product_count DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

              platform  product_count
0     reliance digital            324
1               amazon            320
2                croma            303
3             flipkart            287
4             best buy            133
..                 ...            ...
276        aden camera              1
277         acryl-line              1
278         abed tahan              1
279      abc warehouse              1
280  abc carpet & home              1

[281 rows x 2 columns]

Ques.22. Which platform has the highest average rating?

In [147]:
query = """
SELECT 
    platform,
    ROUND(AVG(rating), 2) AS average_rating,
    COUNT(rating) AS rated_products
FROM products
WHERE platform IS NOT NULL
    AND rating IS NOT NULL
    AND rating BETWEEN 1 AND 5
GROUP BY platform
ORDER BY average_rating DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

                                     platform  average_rating  rated_products
0        woodland hills camera and telescopes             5.0               2
1       walmart - wenyang hk business limited             5.0               1
2                   walmart - techrific deals             5.0               1
3                        walmart - magic chef             5.0               1
4    walmart - cardinal camera & video center             5.0               2
..                                        ...             ...             ...
276                            appliance mart             2.3               1
277                      newegg.com - dianlan             2.0               1
278                         ebay - itembazaar             1.7               1
279                        walmart - alifemap             1.4               2
280                                  lg parts             1.2               1

[281 rows x 3 columns]

Ques.23. Which platform has the lowest average price?

In [148]:
query = """
SELECT 
    platform,
    ROUND(AVG(price), 2) AS average_price,
    COUNT(price) AS priced_products
FROM products
WHERE platform IS NOT NULL
    AND price IS NOT NULL
    AND price > 0
GROUP BY platform
ORDER BY average_price ASC;
"""
result = pd.read_sql_query(query, conn)
print(result)

                 platform  average_price  priced_products
0    wengers of myerstown           8.25                1
1          masterpiece oü          12.00                1
2       ebay - lamasdeals          12.50                1
3        ebay - toto2-163          15.99                1
4             dialrto.com          16.95                1
..                    ...            ...              ...
276            connection        6989.28                1
277                 croma       23041.50              303
278                amazon       23534.28              320
279              flipkart       24554.08              287
280      reliance digital       25315.51              324

[281 rows x 3 columns]

Ques.24. What is the average position (ranking) per platform?

In [149]:
query = """
SELECT 
    platform,
    ROUND(AVG(position), 2) AS average_position,
    COUNT(position) AS ranked_products
FROM products
WHERE platform IS NOT NULL
    AND position IS NOT NULL
GROUP BY platform
ORDER BY average_position ASC;
"""
result = pd.read_sql_query(query, conn)
print(result)

                 platform  average_position  ranked_products
0       ebay - anlordtown               1.0                1
1       ebay - usa*stores               1.0                1
2            mcgrocer.com               1.0                1
3         walmart - verdi               1.0                1
4                 wayfair               1.0                1
..                    ...               ...              ...
272      bhphotovideo.com              40.0                1
273       books a million              40.0                1
274  ebay - goodbyeretail              40.0                1
275                munbyn              40.0                1
276   walmart - jumbobuys              40.0                1

[277 rows x 3 columns]

Ques.25. Which brands are most frequently listed on each platform?

In [150]:
query = """
SELECT
    platform,
    brand,
    COUNT(*) AS product_count
FROM products
WHERE platform IS NOT NULL
    AND brand IS NOT NULL
GROUP BY  platform, brand
ORDER BY platform, product_count DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

                         platform    brand  product_count
0               6 ave electronics    Canon              2
1               abc carpet & home    Cisco              1
2                   abc warehouse       LG              1
3                      abed tahan    Canon              1
4    abt electronics & appliances  Samsung              2
..                            ...      ...            ...
510                       xavlyin   Maytag              1
511               younes electric  Samsung              1
512              ysvara lifestyle    Haier              3
513              ysvara lifestyle    Bosch              3
514              ysvara lifestyle  Samsung              1

[515 rows x 3 columns]

🟫 Visibility & Ranking Analysis

Ques.26. What is the distribution of position (ranking)?

In [151]:
query = """
SELECT 
    rank,
    COUNT(*) AS product_count
FROM products
WHERE rank IS NOT NULL
GROUP BY rank
ORDER BY rank ASC;
"""
result = pd.read_sql_query(query, conn)
print(result)

    rank  product_count
0      1            182
1      2             65
2      3             76
3      4             98
4      5            136
5      6            158
6      7             99
7      8            124
8      9            116
9     10            104
10    11             62
11    12             83
12    13            114
13    14            122
14    15             74
15    16             55
16    17             57
17    18             59
18    19             43
19    20             55
20    21             58
21    22             55
22    23             38
23    24             60
24    25             43
25    26             20
26    27              3
27    28              6
28    29              3
29    30              2
30    31              1
31    32              1
32    33              1
33    34              4
34    35              1
35    36              1
36    37              4

Ques.27. Which products have the highest visibility_score?

In [152]:
query = """
SELECT
    title,
    brand,
    keyword,
    rank,
    ROUND(visibility_score, 2) AS visibility_score
FROM products
WHERE rank IS NOT NULL
ORDER BY visibility_score DESC
LIMIT 20;
"""
result = pd.read_sql_query(query, conn)
print(result)

                                          title    brand  \
0       Sony power bank fast charging Model 896     Sony
1        LG microwave oven convection Model 421       LG
2       Sony power bank fast charging Model 720     Sony
3         LG power bank fast charging Model 952       LG
4         LG power bank fast charging Model 599       LG
5              Sony men running shoes Model 596     Sony
6   Philips microwave oven convection Model 889  Philips
7         LG power bank fast charging Model 902       LG
8             Philips air fryer India Model 978  Philips
9                HP men running shoes Model 889       HP
10     Philips office chair ergonomic Model 808  Philips
11               Dell air fryer India Model 406     Dell
12   Samsung power bank fast charging Model 292  Samsung
13     Philips office chair ergonomic Model 666  Philips
14        Dell office chair ergonomic Model 448     Dell
15               Sony air fryer India Model 541     Sony
16          HP office chair ergonomic Model 389       HP
17     Puma microwave oven convection Model 155     Puma
18               Dell air fryer India Model 521     Dell
19     Sony microwave oven convection Model 861     Sony

                      Keyword  rank  visibility_score
0    power bank fast charging     1             100.0
1   microwave oven convection     1             100.0
2    power bank fast charging     1             100.0
3    power bank fast charging     1             100.0
4    power bank fast charging     1             100.0
5           men running shoes     1             100.0
6   microwave oven convection     1             100.0
7    power bank fast charging     1             100.0
8             air fryer India     1             100.0
9           men running shoes     1             100.0
10     office chair ergonomic     1             100.0
11            air fryer India     1             100.0
12   power bank fast charging     1             100.0
13     office chair ergonomic     1             100.0
14     office chair ergonomic     1             100.0
15            air fryer India     1             100.0
16     office chair ergonomic     1             100.0
17  microwave oven convection     1             100.0
18            air fryer India     1             100.0
19  microwave oven convection     1             100.0

Ques.28. Is there a relationship between rating and position?

In [153]:
query = """
SELECT 
    rating,
    rank,
    title,
    brand,
    platform
FROM products
WHERE rating IS NOT NULL
    AND rating BETWEEN 1 AND 5
    AND rank IS NOT NULL
ORDER BY rank ASC;
"""
result = pd.read_sql_query(query, conn)
print(result)

      rating  rank                                              title  \
0        5.0     1            Sony power bank fast charging Model 896
1        5.0     1             LG microwave oven convection Model 421
2        5.0     1            Sony power bank fast charging Model 720
3        5.0     1              LG power bank fast charging Model 952
4        5.0     1              LG power bank fast charging Model 599
...      ...   ...                                                ...
2178     1.2    36                 LG LFCS28768S Refrigerator ASTCNA2
2179     1.0    37  Fpd 40inch Smart TV 1080p Fhd Compatible with ...
2180     1.0    37             Hamilton Beach 09 Cu ft Microwave Oven
2181     1.0    37             Hamilton Beach 09 Cu ft Microwave Oven
2182     1.0    37  Kodak Charmera 1987 Keychain Digital Camera Ty...

         brand                platform
0         Sony                   croma
1           LG        reliance digital
2         Sony                  amazon
3           LG                   croma
4           LG                   croma
...        ...                     ...
2178        LG                lg parts
2179   Samsung  walmart - fpd official
2180  Hamilton             tiktok shop
2181  Hamilton             tiktok shop
2182     Kodak                    ebay

[2183 rows x 5 columns]

Ques.29. Do products with higher reviews rank better?

In [154]:
query = """
SELECT 
    CASE
        WHEN reviews < 100 THEN 'Low Reviews'
        WHEN reviews < 1000 THEN 'Medium Reviews'
        ELSE 'High Reviews'
    END AS review_category,
    COUNT(*) AS product_count,
    ROUND(AVG(reviews), 2) AS average_review,
    ROUND(AVG(rank), 2) AS average_rank
FROM products
WHERE reviews IS NOT NULL
    AND reviews >= 0
    AND rank IS NOT NULL
GROUP BY review_category
ORDER BY average_rank ASC;
"""
result = pd.read_sql_query(query, conn)
print(result)

  review_category  product_count  average_review  average_rank
0  Medium Reviews            540          472.44         10.86
1     Low Reviews            214           31.98         10.95
2    High Reviews           1212         4476.08         12.00

Ques.30. Which combination of factors (price, rating, reviews) influences top-ranking products?

In [155]:
query = """
SELECT
    CASE
        WHEN rank <= 10 THEN 'Top 10'
        ELSE 'Beyond Top 10'
    END AS ranking_group,
    COUNT(*) AS product_count,
    ROUND(AVG(price), 2) AS average_price,
    ROUND(AVG(rating), 2) AS average_rating,
    ROUND(AVG(reviews), 2) AS average_reviews,
    ROUND(AVG(visibility_score), 2) AS average_visibility_score
FROM products
WHERE rank IS NOT NULL
    AND price IS NOT NULL
    AND price > 0
    AND rating IS NOT NULL
    AND rating BETWEEN 1 AND 5
    AND reviews IS NOT NULL
    AND reviews >= 0
GROUP BY ranking_group
ORDER BY
    CASE ranking_group
        WHEN 'Top 10' THEN 1
        ELSE 2
    END;
"""
result = pd.read_sql_query(query, conn)
print(result)

   ranking_group  product_count  average_price  average_rating  \
0         Top 10            960       11563.33            4.57
1  Beyond Top 10           1006       18317.88            3.34

   average_reviews  average_visibility_score
0          3017.19                     33.71
1          2773.83                      6.12