In [2]:
import requests
import pandas as pd 
import numpy as np

In [3]:
api = "b92b21fbfc5ea4f9179ce9bfd04e8535987e4cf2ff02e12320d3084aa03178de"

In [4]:
keywords = [
    "Phone",
    "television",
    "laptop",
    "fridge",
    "dryer",
    "headset",
    "lamp",
    "microwave",
    "guitar",
    "mixer"
]

In [5]:
url = "https://serpapi.com/search.json"

all_api_data = []

for keyword in keywords:

    params = {
        "engine": "google_shopping",
        "q": keyword,
        "location": "India",
        "api_key": api
    }

    response = requests.get(
        url,
        params=params
    )

    data = response.json()

    results = data.get(
        "shopping_results",
        []
    )

    for item in results:

        record = {
            "Keyword": keyword,
            "title": item.get("title"),
            "price": item.get("extracted_price"),
            "raw_price": item.get("extracted_original_price"),
            "rating": item.get("rating"),
            "Reviews": item.get("reviews"),
            "platform": item.get("source"),
            "position": item.get("position"),
            "Delivery": item.get("delivery"),
            "Link": item.get("product_link"),
            "thumbnail": item.get("thumbnail")
        }

        all_api_data.append(record)

In [6]:
api_df = pd.DataFrame(all_api_data)

In [7]:
api_df.shape

(400, 11)

In [8]:
api_df.head(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail
0,Phone,Apple iPhone 17e,5.99,None,4.6,3400.0,AT&T,1,Free delivery,https://www.google.com/search?ibp=oshop&q=Phon...,https://encrypted-tbn0.gstatic.com/shopping?q=...
1,Phone,Samsung Galaxy A17 5G,NaN,None,NaN,NaN,Cricket Wireless,2,Free delivery,https://www.google.com/search?ibp=oshop&q=Phon...,https://encrypted-tbn3.gstatic.com/shopping?q=...
2,Phone,Apple iPhone 17 Pro Max,1199.00,None,3.8,3500.0,Apple,3,Free next-day delivery,https://www.google.com/search?ibp=oshop&q=Phon...,https://encrypted-tbn3.gstatic.com/shopping?q=...
3,Phone,Apple iPhone 16,20.27,None,4.4,7300.0,Verizon,4,Free delivery,https://www.google.com/search?ibp=oshop&q=Phon...,https://encrypted-tbn1.gstatic.com/shopping?q=...
4,Phone,Nothing Phone Pro,539.00,None,4.8,212.0,Nothing US,5,NaN,https://www.google.com/search?ibp=oshop&q=Phon...,https://encrypted-tbn2.gstatic.com/shopping?q=...
5,Phone,Samsung Galaxy Z Fold8 Ultra,58.34,None,4.9,14000.0,Best Buy,6,Free delivery by Sun,https://www.google.com/search?ibp=oshop&q=Phon...,https://encrypted-tbn0.gstatic.com/shopping?q=...
6,Phone,Motorola Moto G stylus 2025,29.99,None,1.0,1.0,Cricket Wireless,7,Free delivery,https://www.google.com/search?ibp=oshop&q=Phon...,https://encrypted-tbn3.gstatic.com/shopping?q=...
7,Phone,Apple iPhone 17,829.00,None,4.6,15000.0,Apple,8,Free next-day delivery,https://www.google.com/search?ibp=oshop&q=Phon...,https://encrypted-tbn0.gstatic.com/shopping?q=...
8,Phone,Google Pixel 10 Pro,999.00,None,4.4,2200.0,Google Store,9,Free delivery,https://www.google.com/search?ibp=oshop&q=Phon...,https://encrypted-tbn0.gstatic.com/shopping?q=...
9,Phone,Samsung Galaxy S26,4.99,None,4.7,13000.0,AT&T,10,Free delivery,https://www.google.com/search?ibp=oshop&q=Phon...,https://encrypted-tbn0.gstatic.com/shopping?q=...

In [9]:
api_df.tail(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail
390,mixer,Mackie 5-Channel Compact Mixer Mix5,79.99,None,4.6,162.0,Guitar Center,31,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn1.gstatic.com/shopping?q=...
391,mixer,KitchenAid Ultra Power Plus 4.5 Quart Tilt-Hea...,299.99,None,4.7,819.0,Target,32,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn1.gstatic.com/shopping?q=...
392,mixer,Yamaha mg10xu 10-Channel Mixer with Effects,250.74,None,4.8,438.0,idjnow,33,Free delivery by Fri,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn0.gstatic.com/shopping?q=...
393,mixer,Hamilton Beach 7 Speed Stack & Scrape Stand Mixer,124.95,None,4.7,30.0,Home Depot,34,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn0.gstatic.com/shopping?q=...
394,mixer,Breville The Bakery Chef Stand Mixer,449.95,None,4.6,269.0,Breville,35,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn3.gstatic.com/shopping?q=...
395,mixer,Hell's Kitchen 3.5L Stainless Steel Stand Mixe...,72.99,None,NaN,NaN,Best Buy,36,NaN,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...
396,mixer,"Spiralmac Mixer, SV8 Royal Queen, Light Creme",1960.00,None,NaN,NaN,Pleasant Hill Grain,37,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn1.gstatic.com/shopping?q=...
397,mixer,Ankarsrum Original Mixer,799.95,None,4.8,2800.0,Everything Kitchens,38,Free delivery by Sat,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...
398,mixer,Dash 3.5 Qt Tilt-Head Stand Mixer,75.99,None,4.5,498.0,Target,39,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn0.gstatic.com/shopping?q=...
399,mixer,Hamilton Beach 6-Speed Classic Hand & Stand Mixer,63.69,None,3.7,967.0,Macy's,40,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...

In [10]:
api_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Keyword    400 non-null    str
 1   title      400 non-null    str
 2   price      399 non-null    float64
 3   raw_price  0 non-null      object
 4   rating     355 non-null    float64
 5   Reviews    355 non-null    float64
 6   platform   400 non-null    str
 7   position   400 non-null    int64
 8   Delivery   280 non-null    str
 9   Link       400 non-null    str
 10  thumbnail  400 non-null    str
dtypes: float64(3), int64(1), object(1), str(6)
memory usage: 245.4+ KB

In [11]:
api_df.isnull().sum()

Keyword        0
title          0
price          1
raw_price    400
rating        45
Reviews       45
platform       0
position       0
Delivery     120
Link           0
thumbnail      0
dtype: int64

In [12]:
csv_df = pd.read_csv("brand_dirty_dataset.csv")

csv_df

,keyword,title,price,rating,reviews,platform,delivery
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,3.7,3241,croma,2 Days
1,microwave oven convection,Samsung microwave oven convection Model 524 !!!,NaN,4.7,1294,amazon,Free Delivery
2,power bank fast charging,Samsung power bank fast charging Model 402,Not Available,NaN,3070,CROMA,Free Delivery
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,4.7,3446,flipkart,Free Delivery
4,men running shoes,Dell men running shoes Model 536,2176.0,3.8,2031,croma,5 Days
...,...,...,...,...,...,...,...
1315,office chair ergonomic,HP office chair ergonomic Model 168,20097.0,3.5,2880,CROMA,2 Days
1316,office chair ergonomic,Nike office chair ergonomic Model 138,33684.0,4.1,4006,croma,5 Days
1317,power bank fast charging,HP power bank fast charging Model 250,38959.0,4.6,579,RELIANCE DIGITAL,2 Days
1318,power bank fast charging,Samsung power bank fast charging Model 407,NaN,3.0,384,reliance digital,5 Days
1319,microwave oven convection,Philips microwave oven convection Model 322,Not Available,4.2,3643,croma,Free Delivery

In [13]:
csv_df.shape

(1320, 7)

In [14]:
csv_df.head(10)

,keyword,title,price,rating,reviews,platform,delivery
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,3.7,3241,croma,2 Days
1,microwave oven convection,Samsung microwave oven convection Model 524 !!!,NaN,4.7,1294,amazon,Free Delivery
2,power bank fast charging,Samsung power bank fast charging Model 402,Not Available,NaN,3070,CROMA,Free Delivery
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,4.7,3446,flipkart,Free Delivery
4,men running shoes,Dell men running shoes Model 536,2176.0,3.8,2031,croma,5 Days
5,power bank fast charging,Samsung power bank fast charging Model 562,5331.0,NaN,4124,RELIANCE DIGITAL,5 Days
6,air fryer India,Philips air fryer India Model 259,Not Available,2.8,1761,CROMA,5 Days
7,office chair ergonomic,Philips office chair ergonomic Model 836,4564.0,3.0,1540,AMAZON,Free Delivery
8,microwave oven convection,Boat microwave oven convection Model 588,21830.0,4.0,126,croma,Free Delivery
9,office chair ergonomic,Puma office chair ergonomic Model 591,19233.0,4.6,3911,RELIANCE DIGITAL,5 Days

In [15]:
csv_df.tail(10)

,keyword,title,price,rating,reviews,platform,delivery
1310,microwave oven convection,Boat microwave oven convection Model 727,16473.0,NaN,4296,CROMA,Free Delivery
1311,air fryer India,LG air fryer India Model 363,10393.0,3.5,many,CROMA,2 Days
1312,air fryer India,Sony air fryer India Model 915,21233.0,4.6,57,CROMA,2 Days
1313,microwave oven convection,Nike microwave oven convection Model 392,18929.0,3.7,4407,AMAZON,Free Delivery
1314,microwave oven convection,Samsung microwave oven convection Model 524,NaN,4.7,1294,AMAZON,Free Delivery
1315,office chair ergonomic,HP office chair ergonomic Model 168,20097.0,3.5,2880,CROMA,2 Days
1316,office chair ergonomic,Nike office chair ergonomic Model 138,33684.0,4.1,4006,croma,5 Days
1317,power bank fast charging,HP power bank fast charging Model 250,38959.0,4.6,579,RELIANCE DIGITAL,2 Days
1318,power bank fast charging,Samsung power bank fast charging Model 407,NaN,3.0,384,reliance digital,5 Days
1319,microwave oven convection,Philips microwave oven convection Model 322,Not Available,4.2,3643,croma,Free Delivery

In [16]:
csv_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1320 entries, 0 to 1319
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   keyword   1320 non-null   str
 1   title     1320 non-null   str
 2   price     1194 non-null   str
 3   rating    1189 non-null   float64
 4   reviews   1320 non-null   str
 5   platform  1320 non-null   str
 6   delivery  1320 non-null   str
dtypes: float64(1), str(6)
memory usage: 181.3 KB

In [17]:
csv_df.isnull().sum()

keyword       0
title         0
price       126
rating      131
reviews       0
platform      0
delivery      0
dtype: int64

In [18]:
print(csv_df.columns.tolist())

['keyword', 'title', 'price', 'rating', 'reviews', 'platform', 'delivery']

In [19]:
def standardize_columns(df):

    df = df.copy()

    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("-", "_")
    )

    return df

In [20]:
rename_columns = {

    "keyword": "Keyword",
    "title": "title",

    "price": "price",
    "raw_price": "raw_price",

    "rating": "rating",

    "reviews": "Reviews",
    "review": "Reviews",

    "platform": "platform",
    "source": "platform",

    "position": "position",
    "rank": "position",

    "delivery": "Delivery",

    "link": "Link",
    "product_link": "Link",

    "thumbnail": "thumbnail"
}

In [21]:
csv_df = standardize_columns(csv_df)

api_df = standardize_columns(api_df)

print("CSV Columns:")
print(csv_df.columns.tolist())

print("\nAPI Columns:")
print(api_df.columns.tolist())

CSV Columns:
['keyword', 'title', 'price', 'rating', 'reviews', 'platform', 'delivery']

API Columns:
['keyword', 'title', 'price', 'raw_price', 'rating', 'reviews', 'platform', 'position', 'delivery', 'link', 'thumbnail']

In [22]:
csv_df = csv_df.rename(
    columns=rename_columns
)

api_df = api_df.rename(
    columns=rename_columns
)

In [23]:
rename_columns = {

    "keyword": "Keyword",
    "title": "title",

    "price": "price",
    "raw_price": "raw_price",

    "rating": "rating",

    "reviews": "Reviews",
    "review": "Reviews",

    "platform": "platform",
    "source": "platform",

    "position": "position",
    "rank": "position",

    "delivery": "Delivery",

    "link": "Link",
    "product_link": "Link",

    "thumbnail": "thumbnail"
}

In [24]:
required_columns = [
    "Keyword",
    "title",
    "price",
    "raw_price",
    "rating",
    "Reviews",
    "platform",
    "position",
    "Delivery",
    "Link",
    "thumbnail"
]

In [25]:
for column in required_columns:

    if column not in csv_df.columns:
        csv_df[column] = np.nan

    if column not in api_df.columns:
        api_df[column] = np.nan

In [26]:
csv_df = csv_df[
    required_columns
]

api_df = api_df[
    required_columns
]

In [27]:
combined_df = pd.concat(
    [
        csv_df,
        api_df
    ],
    ignore_index=True
)

In [28]:
combined_df.to_csv(
    "merged_data.csv",
    index=False
)

In [29]:
missing_count = combined_df.isnull().sum()

missing_percentage = (
    combined_df.isnull().mean() * 100
).round(2)

missing_report = pd.DataFrame({

    "Missing Count": missing_count,

    "Missing Percentage":
        missing_percentage
})

missing_report

           Missing Count  Missing Percentage
Keyword                0                0.00
title                  0                0.00
price                127                7.38
raw_price           1720              100.00
rating               176               10.23
Reviews               45                2.62
platform               0                0.00
position            1320               76.74
Delivery             120                6.98
Link                1320               76.74
thumbnail           1320               76.74

In [30]:
pd.read_csv("merged_data.csv")

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,NaN,3.7,3241,croma,NaN,2 Days,NaN,NaN
1,microwave oven convection,Samsung microwave oven convection Model 524 !!!,NaN,NaN,4.7,1294,amazon,NaN,Free Delivery,NaN,NaN
2,power bank fast charging,Samsung power bank fast charging Model 402,Not Available,NaN,NaN,3070,CROMA,NaN,Free Delivery,NaN,NaN
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,NaN,4.7,3446,flipkart,NaN,Free Delivery,NaN,NaN
4,men running shoes,Dell men running shoes Model 536,2176.0,NaN,3.8,2031,croma,NaN,5 Days,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1715,mixer,Hell's Kitchen 3.5L Stainless Steel Stand Mixe...,72.99,NaN,NaN,NaN,Best Buy,36.0,NaN,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...
1716,mixer,"Spiralmac Mixer, SV8 Royal Queen, Light Creme",1960.0,NaN,NaN,NaN,Pleasant Hill Grain,37.0,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn1.gstatic.com/shopping?q=...
1717,mixer,Ankarsrum Original Mixer,799.95,NaN,4.8,2800.0,Everything Kitchens,38.0,Free delivery by Sat,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...
1718,mixer,Dash 3.5 Qt Tilt-Head Stand Mixer,75.99,NaN,4.5,498.0,Target,39.0,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn0.gstatic.com/shopping?q=...
1719,mixer,Hamilton Beach 6-Speed Classic Hand & Stand Mixer,63.69,NaN,3.7,967.0,Macy's,40.0,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...

In [31]:
merged_df = pd.read_csv("merged_data.csv")

In [32]:
merged_df.shape

(1720, 11)

In [33]:
merged_df.head(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,NaN,3.7,3241,croma,NaN,2 Days,NaN,NaN
1,microwave oven convection,Samsung microwave oven convection Model 524 !!!,NaN,NaN,4.7,1294,amazon,NaN,Free Delivery,NaN,NaN
2,power bank fast charging,Samsung power bank fast charging Model 402,Not Available,NaN,NaN,3070,CROMA,NaN,Free Delivery,NaN,NaN
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,NaN,4.7,3446,flipkart,NaN,Free Delivery,NaN,NaN
4,men running shoes,Dell men running shoes Model 536,2176.0,NaN,3.8,2031,croma,NaN,5 Days,NaN,NaN
5,power bank fast charging,Samsung power bank fast charging Model 562,5331.0,NaN,NaN,4124,RELIANCE DIGITAL,NaN,5 Days,NaN,NaN
6,air fryer India,Philips air fryer India Model 259,Not Available,NaN,2.8,1761,CROMA,NaN,5 Days,NaN,NaN
7,office chair ergonomic,Philips office chair ergonomic Model 836,4564.0,NaN,3.0,1540,AMAZON,NaN,Free Delivery,NaN,NaN
8,microwave oven convection,Boat microwave oven convection Model 588,21830.0,NaN,4.0,126,croma,NaN,Free Delivery,NaN,NaN
9,office chair ergonomic,Puma office chair ergonomic Model 591,19233.0,NaN,4.6,3911,RELIANCE DIGITAL,NaN,5 Days,NaN,NaN

In [34]:
merged_df.tail(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail
1710,mixer,Mackie 5-Channel Compact Mixer Mix5,79.99,NaN,4.6,162.0,Guitar Center,31.0,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn1.gstatic.com/shopping?q=...
1711,mixer,KitchenAid Ultra Power Plus 4.5 Quart Tilt-Hea...,299.99,NaN,4.7,819.0,Target,32.0,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn1.gstatic.com/shopping?q=...
1712,mixer,Yamaha mg10xu 10-Channel Mixer with Effects,250.74,NaN,4.8,438.0,idjnow,33.0,Free delivery by Fri,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn0.gstatic.com/shopping?q=...
1713,mixer,Hamilton Beach 7 Speed Stack & Scrape Stand Mixer,124.95,NaN,4.7,30.0,Home Depot,34.0,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn0.gstatic.com/shopping?q=...
1714,mixer,Breville The Bakery Chef Stand Mixer,449.95,NaN,4.6,269.0,Breville,35.0,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn3.gstatic.com/shopping?q=...
1715,mixer,Hell's Kitchen 3.5L Stainless Steel Stand Mixe...,72.99,NaN,NaN,NaN,Best Buy,36.0,NaN,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...
1716,mixer,"Spiralmac Mixer, SV8 Royal Queen, Light Creme",1960.0,NaN,NaN,NaN,Pleasant Hill Grain,37.0,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn1.gstatic.com/shopping?q=...
1717,mixer,Ankarsrum Original Mixer,799.95,NaN,4.8,2800.0,Everything Kitchens,38.0,Free delivery by Sat,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...
1718,mixer,Dash 3.5 Qt Tilt-Head Stand Mixer,75.99,NaN,4.5,498.0,Target,39.0,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn0.gstatic.com/shopping?q=...
1719,mixer,Hamilton Beach 6-Speed Classic Hand & Stand Mixer,63.69,NaN,3.7,967.0,Macy's,40.0,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...

In [35]:
missing_report

           Missing Count  Missing Percentage
Keyword                0                0.00
title                  0                0.00
price                127                7.38
raw_price           1720              100.00
rating               176               10.23
Reviews               45                2.62
platform               0                0.00
position            1320               76.74
Delivery             120                6.98
Link                1320               76.74
thumbnail           1320               76.74

In [36]:
print("CSV shape:", csv_df.shape)
print("API shape:", api_df.shape)

print("\nCSV missing values:")
print(csv_df.isnull().sum())

print("\nAPI missing values:")
print(api_df.isnull().sum())

CSV shape: (1320, 11)
API shape: (400, 11)

CSV missing values:
Keyword         0
title           0
price         126
raw_price    1320
rating        131
Reviews         0
platform        0
position     1320
Delivery        0
Link         1320
thumbnail    1320
dtype: int64

API missing values:
Keyword        0
title          0
price          1
raw_price    400
rating        45
Reviews       45
platform       0
position       0
Delivery     120
Link           0
thumbnail      0
dtype: int64

In [37]:
print("CSV Position missing:")
print(csv_df["position"].isnull().sum())

print("API Position missing:")
print(api_df["position"].isnull().sum())

CSV Position missing:
1320
API Position missing:
0

In [38]:
print("CSV Platform values:")
print(csv_df["platform"].value_counts(dropna=False))

print("\nAPI Platform values:")
print(api_df["platform"].value_counts(dropna=False))

CSV Platform values:
platform
reliance digital    193
amazon              182
flipkart            168
CROMA               164
croma               162
RELIANCE DIGITAL    160
AMAZON              155
FLIPKART            136
Name: count, dtype: int64

API Platform values:
platform
Best Buy               50
Walmart                43
Target                 39
Home Depot             33
Lowe's                 21
                       ..
Chef's Corner Store     1
Sur La Table            1
idjnow                  1
Breville                1
Pleasant Hill Grain     1
Name: count, Length: 129, dtype: int64

In [39]:
print(merged_df.dtypes)

Keyword          str
title            str
price            str
raw_price    float64
rating       float64
Reviews          str
platform         str
position     float64
Delivery         str
Link             str
thumbnail        str
dtype: object

In [40]:
clean_df = merged_df.copy()

In [41]:
clean_df.shape

(1720, 11)

In [42]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1720 entries, 0 to 1719
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Keyword    1720 non-null   str
 1   title      1720 non-null   str
 2   price      1593 non-null   str
 3   raw_price  0 non-null      float64
 4   rating     1544 non-null   float64
 5   Reviews    1675 non-null   str
 6   platform   1720 non-null   str
 7   position   400 non-null    float64
 8   Delivery   1600 non-null   str
 9   Link       400 non-null    str
 10  thumbnail  400 non-null    str
dtypes: float64(3), str(8)
memory usage: 472.6 KB

In [43]:
text_columns = [
    "Keyword",
    "title",
    "platform",
    "Delivery",
    "Link",
    "thumbnail"
]

for column in text_columns:
    clean_df[column] = (
        clean_df[column]
        .astype("string")
        .str.strip()
    )

In [44]:
clean_df["platform"] = (
    clean_df["platform"]
    .str.lower()
    .str.strip()
)

In [45]:
clean_df.head(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,NaN,3.7,3241,croma,NaN,2 Days,<NA>,<NA>
1,microwave oven convection,Samsung microwave oven convection Model 524 !!!,NaN,NaN,4.7,1294,amazon,NaN,Free Delivery,<NA>,<NA>
2,power bank fast charging,Samsung power bank fast charging Model 402,Not Available,NaN,NaN,3070,croma,NaN,Free Delivery,<NA>,<NA>
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,NaN,4.7,3446,flipkart,NaN,Free Delivery,<NA>,<NA>
4,men running shoes,Dell men running shoes Model 536,2176.0,NaN,3.8,2031,croma,NaN,5 Days,<NA>,<NA>
5,power bank fast charging,Samsung power bank fast charging Model 562,5331.0,NaN,NaN,4124,reliance digital,NaN,5 Days,<NA>,<NA>
6,air fryer India,Philips air fryer India Model 259,Not Available,NaN,2.8,1761,croma,NaN,5 Days,<NA>,<NA>
7,office chair ergonomic,Philips office chair ergonomic Model 836,4564.0,NaN,3.0,1540,amazon,NaN,Free Delivery,<NA>,<NA>
8,microwave oven convection,Boat microwave oven convection Model 588,21830.0,NaN,4.0,126,croma,NaN,Free Delivery,<NA>,<NA>
9,office chair ergonomic,Puma office chair ergonomic Model 591,19233.0,NaN,4.6,3911,reliance digital,NaN,5 Days,<NA>,<NA>

In [46]:
clean_df.tail(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail
1710,mixer,Mackie 5-Channel Compact Mixer Mix5,79.99,NaN,4.6,162.0,guitar center,31.0,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn1.gstatic.com/shopping?q=...
1711,mixer,KitchenAid Ultra Power Plus 4.5 Quart Tilt-Hea...,299.99,NaN,4.7,819.0,target,32.0,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn1.gstatic.com/shopping?q=...
1712,mixer,Yamaha mg10xu 10-Channel Mixer with Effects,250.74,NaN,4.8,438.0,idjnow,33.0,Free delivery by Fri,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn0.gstatic.com/shopping?q=...
1713,mixer,Hamilton Beach 7 Speed Stack & Scrape Stand Mixer,124.95,NaN,4.7,30.0,home depot,34.0,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn0.gstatic.com/shopping?q=...
1714,mixer,Breville The Bakery Chef Stand Mixer,449.95,NaN,4.6,269.0,breville,35.0,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn3.gstatic.com/shopping?q=...
1715,mixer,Hell's Kitchen 3.5L Stainless Steel Stand Mixe...,72.99,NaN,NaN,NaN,best buy,36.0,<NA>,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...
1716,mixer,"Spiralmac Mixer, SV8 Royal Queen, Light Creme",1960.0,NaN,NaN,NaN,pleasant hill grain,37.0,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn1.gstatic.com/shopping?q=...
1717,mixer,Ankarsrum Original Mixer,799.95,NaN,4.8,2800.0,everything kitchens,38.0,Free delivery by Sat,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...
1718,mixer,Dash 3.5 Qt Tilt-Head Stand Mixer,75.99,NaN,4.5,498.0,target,39.0,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn0.gstatic.com/shopping?q=...
1719,mixer,Hamilton Beach 6-Speed Classic Hand & Stand Mixer,63.69,NaN,3.7,967.0,macy's,40.0,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...

In [47]:
print(clean_df["platform"].value_counts().head(20))

platform
reliance digital    353
amazon              337
croma               326
flipkart            304
best buy             50
walmart              43
target               39
home depot           33
lowe's               21
apple                 8
cricket wireless      6
razer.com             6
sweetwater            6
lenovo                5
brandsmart usa        5
zzounds               5
guitar center         5
staples               4
hp                    4
pc richard & son      4
Name: count, dtype: int64[pyarrow]

In [48]:
print(clean_df[["price", "raw_price", "rating", "Reviews", "position"]].head(20))

            price  raw_price  rating Reviews  position
0         36225.0        NaN     3.7    3241       NaN
1             NaN        NaN     4.7    1294       NaN
2   Not Available        NaN     NaN    3070       NaN
3          2507.0        NaN     4.7    3446       NaN
4          2176.0        NaN     3.8    2031       NaN
5          5331.0        NaN     NaN    4124       NaN
6   Not Available        NaN     2.8    1761       NaN
7          4564.0        NaN     3.0    1540       NaN
8         21830.0        NaN     4.0     126       NaN
9         19233.0        NaN     4.6    3911       NaN
10        20381.0        NaN     NaN     684       NaN
11         8744.0        NaN     4.9    3832       NaN
12       190200.0        NaN     4.5    4367       NaN
13         5150.0        NaN     5.0    2220       NaN
14        45304.0        NaN     2.7    1761       NaN
15         9160.0        NaN     3.7    2887       NaN
16        10945.0        NaN     2.9    3032       NaN
17        17931.0        NaN     2.9    4166       NaN
18        15160.0        NaN     3.2    1275       NaN
19  Not Available        NaN     3.3     105       NaN

In [49]:
clean_df["price"] = pd.to_numeric(
    clean_df["price"],
    errors="coerce"
)

clean_df["rating"] = pd.to_numeric(
    clean_df["rating"],
    errors="coerce"
)

clean_df["Reviews"] = pd.to_numeric(
    clean_df["Reviews"],
    errors="coerce"
).astype("Int64")

clean_df["position"] = pd.to_numeric(
    clean_df["position"],
    errors="coerce"
).astype("Int64")

In [50]:
clean_df.head(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,NaN,3.7,3241,croma,<NA>,2 Days,<NA>,<NA>
1,microwave oven convection,Samsung microwave oven convection Model 524 !!!,NaN,NaN,4.7,1294,amazon,<NA>,Free Delivery,<NA>,<NA>
2,power bank fast charging,Samsung power bank fast charging Model 402,NaN,NaN,NaN,3070,croma,<NA>,Free Delivery,<NA>,<NA>
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,NaN,4.7,3446,flipkart,<NA>,Free Delivery,<NA>,<NA>
4,men running shoes,Dell men running shoes Model 536,2176.0,NaN,3.8,2031,croma,<NA>,5 Days,<NA>,<NA>
5,power bank fast charging,Samsung power bank fast charging Model 562,5331.0,NaN,NaN,4124,reliance digital,<NA>,5 Days,<NA>,<NA>
6,air fryer India,Philips air fryer India Model 259,NaN,NaN,2.8,1761,croma,<NA>,5 Days,<NA>,<NA>
7,office chair ergonomic,Philips office chair ergonomic Model 836,4564.0,NaN,3.0,1540,amazon,<NA>,Free Delivery,<NA>,<NA>
8,microwave oven convection,Boat microwave oven convection Model 588,21830.0,NaN,4.0,126,croma,<NA>,Free Delivery,<NA>,<NA>
9,office chair ergonomic,Puma office chair ergonomic Model 591,19233.0,NaN,4.6,3911,reliance digital,<NA>,5 Days,<NA>,<NA>

In [51]:
clean_df.tail(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail
1710,mixer,Mackie 5-Channel Compact Mixer Mix5,79.99,NaN,4.6,162,guitar center,31,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn1.gstatic.com/shopping?q=...
1711,mixer,KitchenAid Ultra Power Plus 4.5 Quart Tilt-Hea...,299.99,NaN,4.7,819,target,32,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn1.gstatic.com/shopping?q=...
1712,mixer,Yamaha mg10xu 10-Channel Mixer with Effects,250.74,NaN,4.8,438,idjnow,33,Free delivery by Fri,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn0.gstatic.com/shopping?q=...
1713,mixer,Hamilton Beach 7 Speed Stack & Scrape Stand Mixer,124.95,NaN,4.7,30,home depot,34,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn0.gstatic.com/shopping?q=...
1714,mixer,Breville The Bakery Chef Stand Mixer,449.95,NaN,4.6,269,breville,35,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn3.gstatic.com/shopping?q=...
1715,mixer,Hell's Kitchen 3.5L Stainless Steel Stand Mixe...,72.99,NaN,NaN,<NA>,best buy,36,<NA>,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...
1716,mixer,"Spiralmac Mixer, SV8 Royal Queen, Light Creme",1960.00,NaN,NaN,<NA>,pleasant hill grain,37,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn1.gstatic.com/shopping?q=...
1717,mixer,Ankarsrum Original Mixer,799.95,NaN,4.8,2800,everything kitchens,38,Free delivery by Sat,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...
1718,mixer,Dash 3.5 Qt Tilt-Head Stand Mixer,75.99,NaN,4.5,498,target,39,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn0.gstatic.com/shopping?q=...
1719,mixer,Hamilton Beach 6-Speed Classic Hand & Stand Mixer,63.69,NaN,3.7,967,macy's,40,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...

In [52]:
print(clean_df[[
    "price",
    "rating",
    "Reviews",
    "position"
]].dtypes)

price       float64
rating      float64
Reviews       Int64
position      Int64
dtype: object

In [53]:
clean_df.dtypes

Keyword       string
title         string
price        float64
raw_price    float64
rating       float64
Reviews        Int64
platform      string
position       Int64
Delivery      string
Link          string
thumbnail     string
dtype: object

In [54]:
print(clean_df[[
    "price",
    "rating",
    "Reviews",
    "position"
]].isnull().sum())

price        193
rating       176
Reviews       71
position    1320
dtype: int64

In [55]:
print("CSV missing price:",
      csv_df["price"].isnull().sum())

print("API missing price:",
      api_df["price"].isnull().sum())

CSV missing price: 126
API missing price: 1

In [56]:
clean_df.isnull().sum()

Keyword         0
title           0
price         193
raw_price    1720
rating        176
Reviews        71
platform        0
position     1320
Delivery      120
Link         1320
thumbnail    1320
dtype: int64

In [57]:
clean_df.isnull().mean().mul(100).round(2)

Keyword        0.00
title          0.00
price         11.22
raw_price    100.00
rating        10.23
Reviews        4.13
platform       0.00
position      76.74
Delivery       6.98
Link          76.74
thumbnail     76.74
dtype: float64

In [58]:
clean_df["Data_Source"] = [
    "CSV" if i < len(csv_df) else "API"
    for i in range(len(clean_df))
]

In [59]:
print(clean_df["Data_Source"].value_counts())

Data_Source
CSV    1320
API     400
Name: count, dtype: int64

In [60]:
for source in clean_df["Data_Source"].unique():

    print(f"\n--- {source} ---")

    print(
        clean_df[
            clean_df["Data_Source"] == source
        ].isnull().sum()
    )

--- CSV ---
Keyword           0
title             0
price           192
raw_price      1320
rating          131
Reviews          26
platform          0
position       1320
Delivery          0
Link           1320
thumbnail      1320
Data_Source       0
dtype: int64

--- API ---
Keyword          0
title            0
price            1
raw_price      400
rating          45
Reviews         45
platform         0
position         0
Delivery       120
Link             0
thumbnail        0
Data_Source      0
dtype: int64

In [61]:
duplicate_count = clean_df.duplicated().sum()

print("Total duplicate rows:", duplicate_count)

Total duplicate rows: 72

In [62]:
duplicates = clean_df[
    clean_df.duplicated(keep=False)
].sort_values("title")

duplicates.head(20)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail,Data_Source
497,air fryer India,Boat air fryer India Model 608,10828.0,NaN,3.3,4277,flipkart,<NA>,5 Days,<NA>,<NA>,CSV
1205,air fryer India,Boat air fryer India Model 608,10828.0,NaN,3.3,4277,flipkart,<NA>,5 Days,<NA>,<NA>,CSV
562,air fryer India,Boat air fryer India Model 698,46221.0,NaN,NaN,1104,reliance digital,<NA>,2 Days,<NA>,<NA>,CSV
1242,air fryer India,Boat air fryer India Model 698,46221.0,NaN,NaN,1104,reliance digital,<NA>,2 Days,<NA>,<NA>,CSV
114,air fryer India,Boat air fryer India Model 908,41753.0,NaN,4.3,3905,reliance digital,<NA>,Free Delivery,<NA>,<NA>,CSV
1293,air fryer India,Boat air fryer India Model 908,41753.0,NaN,4.3,3905,reliance digital,<NA>,Free Delivery,<NA>,<NA>,CSV
1026,air fryer India,Boat air fryer India Model 971,12775.0,NaN,4.0,2898,reliance digital,<NA>,Free Delivery,<NA>,<NA>,CSV
1249,air fryer India,Boat air fryer India Model 971,12775.0,NaN,4.0,2898,reliance digital,<NA>,Free Delivery,<NA>,<NA>,CSV
456,air fryer India,Dell air fryer India Model 222,46717.0,NaN,4.4,4987,amazon,<NA>,2 Days,<NA>,<NA>,CSV
1203,air fryer India,Dell air fryer India Model 222,46717.0,NaN,4.4,4987,amazon,<NA>,2 Days,<NA>,<NA>,CSV
872,air fryer India,Dell air fryer India Model 326,21328.0,NaN,4.5,2894,amazon,<NA>,2 Days,<NA>,<NA>,CSV
1306,air fryer India,Dell air fryer India Model 326,21328.0,NaN,4.5,2894,amazon,<NA>,2 Days,<NA>,<NA>,CSV
1181,air fryer India,Dell air fryer India Model 376,48528.0,NaN,2.6,3673,flipkart,<NA>,Free Delivery,<NA>,<NA>,CSV
1281,air fryer India,Dell air fryer India Model 376,48528.0,NaN,2.6,3673,flipkart,<NA>,Free Delivery,<NA>,<NA>,CSV
105,air fryer India,Dell air fryer India Model 471,25906.0,NaN,2.8,2582,reliance digital,<NA>,Free Delivery,<NA>,<NA>,CSV
1209,air fryer India,Dell air fryer India Model 471,25906.0,NaN,2.8,2582,reliance digital,<NA>,Free Delivery,<NA>,<NA>,CSV
394,men running shoes,Dell men running shoes Model 277,10071.0,NaN,4.9,4560,croma,<NA>,5 Days,<NA>,<NA>,CSV
1246,men running shoes,Dell men running shoes Model 277,10071.0,NaN,4.9,4560,croma,<NA>,5 Days,<NA>,<NA>,CSV
517,microwave oven convection,Dell microwave oven convection Model 270,35994.0,NaN,2.7,2870,flipkart,<NA>,5 Days,<NA>,<NA>,CSV
1253,microwave oven convection,Dell microwave oven convection Model 270,35994.0,NaN,2.7,2870,flipkart,<NA>,5 Days,<NA>,<NA>,CSV

In [63]:
clean_df = clean_df.drop_duplicates().reset_index(drop=True)

print("Shape after removing duplicates:", clean_df.shape)

Shape after removing duplicates: (1648, 12)

In [64]:
print("Final rows:", len(clean_df))
print("Duplicate rows:", clean_df.duplicated().sum())

Final rows: 1648
Duplicate rows: 0

In [65]:
print("Missing prices:", clean_df['price'].isnull().sum())

print("Zero prices:", (clean_df['price'] == 0).sum())

print("Negative prices:", (clean_df['price'] < 0).sum())

print("\nMinimum price:", clean_df['price'].min())
print("Maximum price:", clean_df['price'].max())

Missing prices: 188
Zero prices: 0
Negative prices: 26

Minimum price: -999.0
Maximum price: 498050.0

In [66]:
print(clean_df["price"].describe())

count      1460.000000
mean      25069.020582
std       51725.123434
min        -999.000000
25%         999.742500
50%       13900.000000
75%       33325.000000
max      498050.000000
Name: price, dtype: float64

In [67]:
clean_df.loc[clean_df['price'] < 0, 'price'] = np.nan

In [68]:
print("Negative prices after cleaning:", (clean_df['price'] < 0).sum())

print("Missing prices after cleaning:", clean_df['price'].isnull().sum())

Negative prices after cleaning: 0
Missing prices after cleaning: 214

In [69]:
invalid_price_rows = clean_df[
    clean_df['price'].isna()
]

invalid_price_rows[
    ["Keyword", "title", "price", "platform", "Data_Source"]
].head(20)

,Keyword,title,price,platform,Data_Source
1,microwave oven convection,Samsung microwave oven convection Model 524 !!!,NaN,amazon,CSV
2,power bank fast charging,Samsung power bank fast charging Model 402,NaN,croma,CSV
6,air fryer India,Philips air fryer India Model 259,NaN,croma,CSV
19,microwave oven convection,Samsung microwave oven convection Model 810,NaN,croma,CSV
21,men running shoes,Puma men running shoes Model 233,NaN,flipkart,CSV
23,microwave oven convection,LG microwave oven convection Model 479,NaN,amazon,CSV
33,power bank fast charging,Boat power bank fast charging Model 977,NaN,amazon,CSV
46,power bank fast charging,Puma power bank fast charging Model 256,NaN,amazon,CSV
63,microwave oven convection,Sony microwave oven convection Model 912,NaN,reliance digital,CSV
64,men running shoes,Samsung men running shoes Model 630,NaN,amazon,CSV
68,office chair ergonomic,Puma office chair ergonomic Model 514,NaN,croma,CSV
70,microwave oven convection,Nike microwave oven convection Model 591,NaN,reliance digital,CSV
73,power bank fast charging,Boat power bank fast charging Model 137,NaN,reliance digital,CSV
78,office chair ergonomic,LG office chair ergonomic Model 374,NaN,croma,CSV
95,men running shoes,Boat men running shoes Model 369,NaN,flipkart,CSV
96,microwave oven convection,Sony microwave oven convection Model 340,NaN,reliance digital,CSV
97,office chair ergonomic,Nike office chair ergonomic Model 416 !!!,NaN,croma,CSV
98,air fryer India,Philips air fryer India Model 746,NaN,croma,CSV
99,men running shoes,LG men running shoes Model 542,NaN,reliance digital,CSV
108,power bank fast charging,Dell power bank fast charging Model 386,NaN,reliance digital,CSV

In [70]:
Q1 = clean_df['price'].quantile(0.25)
Q3 = clean_df['price'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

Q1: 1209.9925
Q3: 33475.5
IQR: 32265.5075
Lower Bound: -47188.268749999996
Upper Bound: 81873.76125

In [71]:
price_outliers = clean_df[
    (clean_df['price'] < lower_bound) | 
    (clean_df['price'] > upper_bound)
]

print("Number of price outliers:", len(price_outliers))

Number of price outliers: 46

In [72]:
price_outliers[
    ["Keyword", "title", "price", "platform", "Data_Source"]
].sort_values("price", ascending=False).head(20)

,Keyword,title,price,platform,Data_Source
266,men running shoes,HP men running shoes Model 483 !!!,498050.0,amazon,CSV
1217,air fryer India,Nike air fryer India Model 162 !!!,489880.0,flipkart,CSV
440,microwave oven convection,Boat microwave oven convection Model 424,482890.0,amazon,CSV
965,men running shoes,HP men running shoes Model 580,461640.0,amazon,CSV
282,office chair ergonomic,Boat office chair ergonomic Model 324,455330.0,amazon,CSV
34,microwave oven convection,Dell microwave oven convection Model 272,438510.0,reliance digital,CSV
374,power bank fast charging,Nike power bank fast charging Model 406 !!!,436130.0,reliance digital,CSV
1015,office chair ergonomic,Boat office chair ergonomic Model 756,405890.0,amazon,CSV
1032,microwave oven convection,Philips microwave oven convection Model 148,402890.0,reliance digital,CSV
1225,office chair ergonomic,Sony office chair ergonomic Model 116 !!!,397700.0,reliance digital,CSV
735,office chair ergonomic,Sony office chair ergonomic Model 215 !!!,395720.0,reliance digital,CSV
422,men running shoes,Dell men running shoes Model 628,390740.0,croma,CSV
364,microwave oven convection,Dell microwave oven convection Model 838,383970.0,reliance digital,CSV
506,men running shoes,Boat men running shoes Model 227 !!!,380730.0,croma,CSV
156,microwave oven convection,Nike microwave oven convection Model 158,325160.0,croma,CSV
1233,microwave oven convection,Dell microwave oven convection Model 367,323170.0,amazon,CSV
933,men running shoes,LG men running shoes Model 509,320280.0,amazon,CSV
278,air fryer India,Boat air fryer India Model 822,317150.0,reliance digital,CSV
985,power bank fast charging,Samsung power bank fast charging Model 302,289730.0,croma,CSV
953,air fryer India,Puma air fryer India Model 989,286470.0,amazon,CSV

In [73]:
print("Missing ratings:", clean_df['rating'].isnull().sum())

print("Rating below 0:", (clean_df['rating'] < 0).sum())
print("Rating above 5:", (clean_df['rating'] > 5).sum())

print("\nRating distribution:")
print(clean_df["rating"].describe())

Missing ratings: 168
Rating below 0: 0
Rating above 5: 0

Rating distribution:
count    1480.000000
mean        3.912703
std         0.714725
min         1.000000
25%         3.400000
50%         4.100000
75%         4.500000
max         5.000000
Name: rating, dtype: float64

In [74]:
print("Missing reviews:", clean_df['Reviews'].isnull().sum())

print("Negative reviews:", (clean_df['Reviews'] < 0).sum())

print("\nReviews distribution:")
print(clean_df["Reviews"].describe())

Missing reviews: 71
Negative reviews: 0

Reviews distribution:
count         1577.0
mean     2382.759036
std      3109.666516
min              1.0
25%            679.0
50%           1998.0
75%           3468.0
max          57000.0
Name: Reviews, dtype: Float64

In [75]:
print("Missing positions:", clean_df['position'].isnull().sum())

print("Zero positions:", (clean_df['position'] == 0).sum())
print("Negative positions:", (clean_df['position'] < 0).sum())

print("\nPosition distribution:")
print(clean_df["position"].describe())

Missing positions: 1248
Zero positions: 0
Negative positions: 0

Position distribution:
count        400.0
mean          20.5
std      11.557853
min            1.0
25%          10.75
50%           20.5
75%          30.25
max           40.0
Name: position, dtype: Float64

In [76]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1648 entries, 0 to 1647
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Keyword      1648 non-null   string
 1   title        1648 non-null   string
 2   price        1434 non-null   float64
 3   raw_price    0 non-null      float64
 4   rating       1480 non-null   float64
 5   Reviews      1577 non-null   Int64
 6   platform     1648 non-null   string
 7   position     400 non-null    Int64
 8   Delivery     1528 non-null   string
 9   Link         400 non-null    string
 10  thumbnail    400 non-null    string
 11  Data_Source  1648 non-null   str
dtypes: Int64(2), float64(3), str(1), string(6)
memory usage: 465.4 KB

In [77]:
duplicate_count = clean_df.duplicated().sum()

print("Total duplicate rows:", duplicate_count)

Total duplicate rows: 1

In [78]:
duplicates = clean_df[
    clean_df.duplicated(keep=False)
].sort_values("title")

duplicates.head(20)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail,Data_Source
971,air fryer India,Philips air fryer India Model 213,NaN,NaN,4.4,2655,amazon,<NA>,2 Days,<NA>,<NA>,CSV
1226,air fryer India,Philips air fryer India Model 213,NaN,NaN,4.4,2655,amazon,<NA>,2 Days,<NA>,<NA>,CSV

In [79]:
clean_df = clean_df.drop_duplicates().reset_index(drop=True)

print("Shape after removing duplicates:", clean_df.shape)

Shape after removing duplicates: (1647, 12)

In [80]:
print("Final rows:", len(clean_df))
print("Duplicate rows:", clean_df.duplicated().sum())

Final rows: 1647
Duplicate rows: 0

In [81]:
duplicate_count = clean_df.duplicated().sum()
print("Remaining duplicate rows:", duplicate_count)

Remaining duplicate rows: 0

In [82]:
clean_df["Delivery"].value_counts(dropna=False).head(20)

Delivery
Free Delivery               438
2 Days                      413
5 Days                      396
Free delivery               205
<NA>                        120
Free delivery by Tue         22
Free delivery by Fri         17
Free delivery by Sat         11
Free next-day delivery       10
Free delivery on $35+         8
Free delivery by Sun          4
Free delivery on $2,500+      1
Free delivery on $79+         1
Next-day delivery $15         1
Name: count, dtype: int64[pyarrow]

In [83]:
clean_df["Delivery"] = clean_df["Delivery"].fillna("Unknown")

In [84]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1647 entries, 0 to 1646
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Keyword      1647 non-null   string
 1   title        1647 non-null   string
 2   price        1434 non-null   float64
 3   raw_price    0 non-null      float64
 4   rating       1479 non-null   float64
 5   Reviews      1576 non-null   Int64
 6   platform     1647 non-null   string
 7   position     400 non-null    Int64
 8   Delivery     1647 non-null   string
 9   Link         400 non-null    string
 10  thumbnail    400 non-null    string
 11  Data_Source  1647 non-null   str
dtypes: Int64(2), float64(3), str(1), string(6)
memory usage: 465.9 KB

In [85]:
clean_df.isnull().sum()

Keyword           0
title             0
price           213
raw_price      1647
rating          168
Reviews          71
platform          0
position       1247
Delivery          0
Link           1247
thumbnail      1247
Data_Source       0
dtype: int64

In [86]:
clean_df.duplicated().sum()

np.int64(0)

In [87]:
print("Negative prices:", (clean_df['price'] < 0).sum())
print("Invalid ratings:", ((clean_df['rating'] < 0) | (clean_df['rating'] > 5)).sum())
print("Negative reviews:", (clean_df['Reviews'] < 0).sum())
print("Invalid positions:", (clean_df['position'] <= 0).sum())

Negative prices: 0
Invalid ratings: 0
Negative reviews: 0
Invalid positions: 0

In [88]:
print(clean_df["title"].head(20).to_string())

0                 HP office chair ergonomic Model 603
1     Samsung microwave oven convection Model 524 !!!
2          Samsung power bank fast charging Model 402
3            Dell microwave oven convection Model 877
4                    Dell men running shoes Model 536
5          Samsung power bank fast charging Model 562
6                   Philips air fryer India Model 259
7            Philips office chair ergonomic Model 836
8            Boat microwave oven convection Model 588
9               Puma office chair ergonomic Model 591
10               Boat men running shoes Model 859 !!!
11              Puma office chair ergonomic Model 417
12            Dell power bank fast charging Model 575
13            Sony power bank fast charging Model 896
14                  Philips air fryer India Model 339
15                Philips men running shoes Model 418
16              LG power bank fast charging Model 382
17             HP microwave oven convection Model 409
18          Puma office chair ergonomic Model 198 !!!
19        Samsung microwave oven convection Model 810

In [89]:
print(
    clean_df["title"].str.contains(r"[!@#$%^&*]", regex=True, na=False).sum()
)

145

In [90]:
print("Missing titles:", clean_df["title"].isnull().sum())

print("Blank titles:", (clean_df["title"].str.strip() == "").sum())

Missing titles: 0
Blank titles: 0

In [91]:
clean_df["title"] = (
    clean_df["title"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [92]:
print("Missing titles:", clean_df["title"].isnull().sum())

Missing titles: 0

In [93]:
clean_df.head(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail,Data_Source
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,NaN,3.7,3241,croma,<NA>,2 Days,<NA>,<NA>,CSV
1,microwave oven convection,Samsung microwave oven convection Model 524 !!!,NaN,NaN,4.7,1294,amazon,<NA>,Free Delivery,<NA>,<NA>,CSV
2,power bank fast charging,Samsung power bank fast charging Model 402,NaN,NaN,NaN,3070,croma,<NA>,Free Delivery,<NA>,<NA>,CSV
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,NaN,4.7,3446,flipkart,<NA>,Free Delivery,<NA>,<NA>,CSV
4,men running shoes,Dell men running shoes Model 536,2176.0,NaN,3.8,2031,croma,<NA>,5 Days,<NA>,<NA>,CSV
5,power bank fast charging,Samsung power bank fast charging Model 562,5331.0,NaN,NaN,4124,reliance digital,<NA>,5 Days,<NA>,<NA>,CSV
6,air fryer India,Philips air fryer India Model 259,NaN,NaN,2.8,1761,croma,<NA>,5 Days,<NA>,<NA>,CSV
7,office chair ergonomic,Philips office chair ergonomic Model 836,4564.0,NaN,3.0,1540,amazon,<NA>,Free Delivery,<NA>,<NA>,CSV
8,microwave oven convection,Boat microwave oven convection Model 588,21830.0,NaN,4.0,126,croma,<NA>,Free Delivery,<NA>,<NA>,CSV
9,office chair ergonomic,Puma office chair ergonomic Model 591,19233.0,NaN,4.6,3911,reliance digital,<NA>,5 Days,<NA>,<NA>,CSV

In [94]:
print(
    clean_df["Delivery"].value_counts(dropna=False).head(20)
)

Delivery
Free Delivery               438
2 Days                      413
5 Days                      396
Free delivery               205
Unknown                     120
Free delivery by Tue         22
Free delivery by Fri         17
Free delivery by Sat         11
Free next-day delivery       10
Free delivery on $35+         8
Free delivery by Sun          4
Free delivery on $2,500+      1
Free delivery on $79+         1
Next-day delivery $15         1
Name: count, dtype: int64[pyarrow]

In [95]:
clean_df["Delivery"] = (
    clean_df["Delivery"].astype("string").str.strip()
)

clean_df["Delivery"] = clean_df["Delivery"].fillna("Unknown")

In [96]:
print(clean_df["Delivery"].value_counts(dropna=False).head(20))

Delivery
Free Delivery               438
2 Days                      413
5 Days                      396
Free delivery               205
Unknown                     120
Free delivery by Tue         22
Free delivery by Fri         17
Free delivery by Sat         11
Free next-day delivery       10
Free delivery on $35+         8
Free delivery by Sun          4
Free delivery on $2,500+      1
Free delivery on $79+         1
Next-day delivery $15         1
Name: count, dtype: int64[pyarrow]

In [97]:
clean_df["platform"] = (
    clean_df["platform"]
    .astype("string")
    .str.strip()
    .str.lower()
)

clean_df["platform"] = clean_df["platform"].replace(
    r"^\s*$",
    np.nan,
    regex=True
)

In [98]:
print("Unique platforms after cleaning:", clean_df["platform"].nunique())

print(
    clean_df["platform"].value_counts(dropna=False).head(20)
)

Unique platforms after cleaning: 133
platform
reliance digital    328
amazon              323
croma               307
flipkart            289
best buy             50
walmart              43
target               39
home depot           33
lowe's               21
apple                 8
cricket wireless      6
razer.com             6
sweetwater            6
lenovo                5
brandsmart usa        5
zzounds               5
guitar center         5
staples               4
hp                    4
pc richard & son      4
Name: count, dtype: int64[pyarrow]

In [99]:
missing_count = clean_df.isnull().sum()

missing_percentage = (
    clean_df.isnull().mean() * 100
).round(2)

final_missing_report = pd.DataFrame({
    "missing_count": missing_count,
    "missing_percentage": missing_percentage
})

final_missing_report

             missing_count  missing_percentage
Keyword                  0                0.00
title                    0                0.00
price                  213               12.93
raw_price             1647              100.00
rating                 168               10.20
Reviews                 71                4.31
platform                 0                0.00
position              1247               75.71
Delivery                 0                0.00
Link                  1247               75.71
thumbnail             1247               75.71
Data_Source              0                0.00

In [100]:
print(clean_df.dtypes)

Keyword         string
title           string
price          float64
raw_price      float64
rating         float64
Reviews          Int64
platform        string
position         Int64
Delivery        string
Link            string
thumbnail       string
Data_Source        str
dtype: object

In [101]:
print("Negative prices:", (clean_df['price'] < 0).sum())
print("Zero prices:", (clean_df['price'] == 0).sum())

print("Invalid ratings:", ((clean_df['rating'] < 0) | (clean_df['rating'] > 5)).sum())

print("Negative reviews:", (clean_df['Reviews'] < 0).sum())

print("Invalid positions:", (clean_df['position'] <= 0).sum())

print("Duplicate rows:", clean_df.duplicated().sum())

Negative prices: 0
Zero prices: 0
Invalid ratings: 0
Negative reviews: 0
Invalid positions: 0
Duplicate rows: 0

In [102]:
print("Total records after cleaning:", len(clean_df))
print("Missing titles:", clean_df["title"].isnull().sum())

print("Sample titles:")
print(clean_df["title"].head(10).to_string())

Total records after cleaning: 1647
Missing titles: 0
Sample titles:
0                HP office chair ergonomic Model 603
1    Samsung microwave oven convection Model 524 !!!
2         Samsung power bank fast charging Model 402
3           Dell microwave oven convection Model 877
4                   Dell men running shoes Model 536
5         Samsung power bank fast charging Model 562
6                  Philips air fryer India Model 259
7           Philips office chair ergonomic Model 836
8           Boat microwave oven convection Model 588
9              Puma office chair ergonomic Model 591

In [103]:
clean_df["title"] = (
    clean_df["title"]
    .str.replace(r"!+", " ", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [104]:
print(clean_df["title"].head(20).to_string())

0             HP office chair ergonomic Model 603
1     Samsung microwave oven convection Model 524
2      Samsung power bank fast charging Model 402
3        Dell microwave oven convection Model 877
4                Dell men running shoes Model 536
5      Samsung power bank fast charging Model 562
6               Philips air fryer India Model 259
7        Philips office chair ergonomic Model 836
8        Boat microwave oven convection Model 588
9           Puma office chair ergonomic Model 591
10               Boat men running shoes Model 859
11          Puma office chair ergonomic Model 417
12        Dell power bank fast charging Model 575
13        Sony power bank fast charging Model 896
14              Philips air fryer India Model 339
15            Philips men running shoes Model 418
16          LG power bank fast charging Model 382
17         HP microwave oven convection Model 409
18          Puma office chair ergonomic Model 198
19    Samsung microwave oven convection Model 810

In [105]:
print(
    "Title containing !:",
    clean_df["title"].str.contains("!", na=False).sum()
)

Title containing !: 0

In [106]:
print(
    "Blank Titles:",
    clean_df["title"].str.strip().eq("").sum()
)

print(
    "Missing Titles:",
    clean_df["title"].isna().sum()
)

Blank Titles: 0
Missing Titles: 0

In [107]:
print(
    clean_df["Delivery"]
    .value_counts(dropna=False)
)

Delivery
Free Delivery               438
2 Days                      413
5 Days                      396
Free delivery               205
Unknown                     120
Free delivery by Tue         22
Free delivery by Fri         17
Free delivery by Sat         11
Free next-day delivery       10
Free delivery on $35+         8
Free delivery by Sun          4
Free delivery on $2,500+      1
Free delivery on $79+         1
Next-day delivery $15         1
Name: count, dtype: int64[pyarrow]

In [108]:
clean_df["Delivery"] = (
    clean_df["Delivery"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [109]:
clean_df["Delivery"] = clean_df["Delivery"].fillna("Unknown")

In [110]:
clean_df.loc[
    clean_df["Delivery"].str.strip().eq(""),
    "Delivery"
] = "Unknown"

In [111]:
print(
    clean_df["Delivery"]
    .value_counts(dropna=False)
)

Delivery
Free Delivery               438
2 Days                      413
5 Days                      396
Free delivery               205
Unknown                     120
Free delivery by Tue         22
Free delivery by Fri         17
Free delivery by Sat         11
Free next-day delivery       10
Free delivery on $35+         8
Free delivery by Sun          4
Free delivery on $2,500+      1
Free delivery on $79+         1
Next-day delivery $15         1
Name: count, dtype: int64[pyarrow]

In [112]:
print(
    "Missing Delivery:",
    clean_df["Delivery"].isna().sum()
)

Missing Delivery: 0

In [113]:
print("Unique platforms:", clean_df["platform"].nunique())

print("\nTop platforms:")
print(
    clean_df["platform"]
    .value_counts()
    .head(20)
)

Unique platforms: 133

Top platforms:
platform
reliance digital    328
amazon              323
croma               307
flipkart            289
best buy             50
walmart              43
target               39
home depot           33
lowe's               21
apple                 8
cricket wireless      6
razer.com             6
sweetwater            6
lenovo                5
brandsmart usa        5
zzounds               5
guitar center         5
staples               4
hp                    4
pc richard & son      4
Name: count, dtype: int64[pyarrow]

In [114]:
print(
    "Missing platforms:",
    clean_df["platform"].isna().sum()
)

print(
    "Blank platforms:",
    clean_df["platform"].str.strip().eq("").sum()
)

Missing platforms: 0
Blank platforms: 0

In [115]:
print(
    "Duplicate rows:",
    clean_df.duplicated().sum()
)

Duplicate rows: 13

In [116]:
duplicates = clean_df[
    clean_df.duplicated(keep=False)
].sort_values("title")

duplicates.head(20)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail,Data_Source
1067,air fryer India,Boat air fryer India Model 433,30954.0,NaN,4.2,746,amazon,<NA>,5 Days,<NA>,<NA>,CSV
1236,air fryer India,Boat air fryer India Model 433,30954.0,NaN,4.2,746,amazon,<NA>,5 Days,<NA>,<NA>,CSV
932,air fryer India,Boat air fryer India Model 950,35032.0,NaN,3.9,2261,reliance digital,<NA>,2 Days,<NA>,<NA>,CSV
1223,air fryer India,Boat air fryer India Model 950,35032.0,NaN,3.9,2261,reliance digital,<NA>,2 Days,<NA>,<NA>,CSV
1083,microwave oven convection,Boat microwave oven convection Model 727,16473.0,NaN,NaN,4296,croma,<NA>,Free Delivery,<NA>,<NA>,CSV
1243,microwave oven convection,Boat microwave oven convection Model 727,16473.0,NaN,NaN,4296,croma,<NA>,Free Delivery,<NA>,<NA>,CSV
593,power bank fast charging,HP power bank fast charging Model 815,5912.0,NaN,3.6,80,reliance digital,<NA>,Free Delivery,<NA>,<NA>,CSV
1240,power bank fast charging,HP power bank fast charging Model 815,5912.0,NaN,3.6,80,reliance digital,<NA>,Free Delivery,<NA>,<NA>,CSV
1149,power bank fast charging,LG power bank fast charging Model 347,16861.0,NaN,4.4,1826,croma,<NA>,2 Days,<NA>,<NA>,CSV
1241,power bank fast charging,LG power bank fast charging Model 347,16861.0,NaN,4.4,1826,croma,<NA>,2 Days,<NA>,<NA>,CSV
399,air fryer India,Nike air fryer India Model 258,17028.0,NaN,3.0,3583,flipkart,<NA>,5 Days,<NA>,<NA>,CSV
1208,air fryer India,Nike air fryer India Model 258,17028.0,NaN,3.0,3583,flipkart,<NA>,5 Days,<NA>,<NA>,CSV
757,office chair ergonomic,Nike office chair ergonomic Model 977,41365.0,NaN,3.8,1093,croma,<NA>,Free Delivery,<NA>,<NA>,CSV
1219,office chair ergonomic,Nike office chair ergonomic Model 977,41365.0,NaN,3.8,1093,croma,<NA>,Free Delivery,<NA>,<NA>,CSV
413,power bank fast charging,Nike power bank fast charging Model 593,NaN,NaN,NaN,1615,amazon,<NA>,Free Delivery,<NA>,<NA>,CSV
1201,power bank fast charging,Nike power bank fast charging Model 593,NaN,NaN,NaN,1615,amazon,<NA>,Free Delivery,<NA>,<NA>,CSV
658,air fryer India,Philips air fryer India Model 594,41057.0,NaN,3.6,3166,reliance digital,<NA>,2 Days,<NA>,<NA>,CSV
1226,air fryer India,Philips air fryer India Model 594,41057.0,NaN,3.6,3166,reliance digital,<NA>,2 Days,<NA>,<NA>,CSV
598,microwave oven convection,Puma microwave oven convection Model 212,12632.0,NaN,3.0,2291,flipkart,<NA>,Free Delivery,<NA>,<NA>,CSV
1222,microwave oven convection,Puma microwave oven convection Model 212,12632.0,NaN,3.0,2291,flipkart,<NA>,Free Delivery,<NA>,<NA>,CSV

In [117]:
clean_df = clean_df.drop_duplicates(
    keep="first"
).reset_index(drop=True)

In [118]:
print("Rows:", len(clean_df))
print("Duplicates:", clean_df.duplicated().sum())

Rows: 1634
Duplicates: 0

In [119]:
print("Negative prices:",
      (clean_df["price"] < 0).sum())

print("Zero prices:",
      (clean_df["price"] == 0).sum())

print("Invalid ratings:",
      ((clean_df["rating"] < 0) |
       (clean_df["rating"] > 5)).sum())

print("Negative reviews:",
      (clean_df["Reviews"] < 0).sum())

print("Invalid positions:",
      (clean_df["position"] <= 0).sum())

Negative prices: 0
Zero prices: 0
Invalid ratings: 0
Negative reviews: 0
Invalid positions: 0

In [120]:
final_missing = pd.DataFrame({
    "Missing Count": clean_df.isna().sum(),
    "Missing Percentage": (
        clean_df.isna().mean() * 100
    ).round(2)
})

final_missing

             Missing Count  Missing Percentage
Keyword                  0                0.00
title                    0                0.00
price                  211               12.91
raw_price             1634              100.00
rating                 166               10.16
Reviews                 71                4.35
platform                 0                0.00
position              1234               75.52
Delivery                 0                0.00
Link                  1234               75.52
thumbnail             1234               75.52
Data_Source              0                0.00

In [121]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1634 entries, 0 to 1633
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Keyword      1634 non-null   string
 1   title        1634 non-null   string
 2   price        1423 non-null   float64
 3   raw_price    0 non-null      float64
 4   rating       1468 non-null   float64
 5   Reviews      1563 non-null   Int64
 6   platform     1634 non-null   string
 7   position     400 non-null    Int64
 8   Delivery     1634 non-null   string
 9   Link         400 non-null    string
 10  thumbnail    400 non-null    string
 11  Data_Source  1634 non-null   str
dtypes: Int64(2), float64(3), str(1), string(6)
memory usage: 463.3 KB

In [122]:
print(clean_df.dtypes)

Keyword         string
title           string
price          float64
raw_price      float64
rating         float64
Reviews          Int64
platform        string
position         Int64
Delivery        string
Link            string
thumbnail       string
Data_Source        str
dtype: object

In [123]:
clean_df.to_csv(
    "clean_brand_visibility_data.csv",
    index=False
)

In [124]:
clean_df.shape

(1634, 12)

In [125]:
clean_df.head(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail,Data_Source
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,NaN,3.7,3241,croma,<NA>,2 Days,<NA>,<NA>,CSV
1,microwave oven convection,Samsung microwave oven convection Model 524,NaN,NaN,4.7,1294,amazon,<NA>,Free Delivery,<NA>,<NA>,CSV
2,power bank fast charging,Samsung power bank fast charging Model 402,NaN,NaN,NaN,3070,croma,<NA>,Free Delivery,<NA>,<NA>,CSV
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,NaN,4.7,3446,flipkart,<NA>,Free Delivery,<NA>,<NA>,CSV
4,men running shoes,Dell men running shoes Model 536,2176.0,NaN,3.8,2031,croma,<NA>,5 Days,<NA>,<NA>,CSV
5,power bank fast charging,Samsung power bank fast charging Model 562,5331.0,NaN,NaN,4124,reliance digital,<NA>,5 Days,<NA>,<NA>,CSV
6,air fryer India,Philips air fryer India Model 259,NaN,NaN,2.8,1761,croma,<NA>,5 Days,<NA>,<NA>,CSV
7,office chair ergonomic,Philips office chair ergonomic Model 836,4564.0,NaN,3.0,1540,amazon,<NA>,Free Delivery,<NA>,<NA>,CSV
8,microwave oven convection,Boat microwave oven convection Model 588,21830.0,NaN,4.0,126,croma,<NA>,Free Delivery,<NA>,<NA>,CSV
9,office chair ergonomic,Puma office chair ergonomic Model 591,19233.0,NaN,4.6,3911,reliance digital,<NA>,5 Days,<NA>,<NA>,CSV

In [126]:
clean_df.duplicated().sum()

np.int64(0)

In [127]:
print("Rows:", clean_df.shape[0])
print("Columns:", clean_df.shape[1])

Rows: 1634
Columns: 12

In [128]:
print("Negative prices:", (clean_df["price"] < 0).sum())
print("Zero prices:", (clean_df["price"] == 0).sum())

print(
    "Invalid ratings:",
    ((clean_df["rating"] < 0) | (clean_df["rating"] > 5)).sum()
)

print("Negative reviews:", (clean_df["Reviews"] < 0).sum())

print("Invalid positions:", (clean_df["position"] <= 0).sum())

print("Duplicates:", clean_df.duplicated().sum())

Negative prices: 0
Zero prices: 0
Invalid ratings: 0
Negative reviews: 0
Invalid positions: 0
Duplicates: 0

In [129]:
print(
    clean_df["title"]
    .head(50)
    .to_string(index=False)
)

        HP office chair ergonomic Model 603
Samsung microwave oven convection Model 524
 Samsung power bank fast charging Model 402
   Dell microwave oven convection Model 877
           Dell men running shoes Model 536
 Samsung power bank fast charging Model 562
          Philips air fryer India Model 259
   Philips office chair ergonomic Model 836
   Boat microwave oven convection Model 588
      Puma office chair ergonomic Model 591
           Boat men running shoes Model 859
      Puma office chair ergonomic Model 417
    Dell power bank fast charging Model 575
    Sony power bank fast charging Model 896
          Philips air fryer India Model 339
        Philips men running shoes Model 418
      LG power bank fast charging Model 382
     HP microwave oven convection Model 409
      Puma office chair ergonomic Model 198
Samsung microwave oven convection Model 810
             Sony air fryer India Model 266
           Puma men running shoes Model 233
    Puma power bank fast charging Model 621
     LG microwave oven convection Model 479
           Nike men running shoes Model 602
     LG microwave oven convection Model 351
      Nike office chair ergonomic Model 173
             HP men running shoes Model 796
    Puma power bank fast charging Model 343
   Nike microwave oven convection Model 438
      Sony office chair ergonomic Model 955
   Nike microwave oven convection Model 917
             Dell air fryer India Model 250
    Boat power bank fast charging Model 977
   Dell microwave oven convection Model 272
               LG air fryer India Model 797
        LG office chair ergonomic Model 187
      LG power bank fast charging Model 927
      Boat office chair ergonomic Model 251
        Philips men running shoes Model 769
    Dell power bank fast charging Model 326
           Dell men running shoes Model 450
      LG power bank fast charging Model 330
        LG office chair ergonomic Model 365
             LG men running shoes Model 272
     HP microwave oven convection Model 260
    Puma power bank fast charging Model 256
             HP men running shoes Model 980
    Boat power bank fast charging Model 625
        HP office chair ergonomic Model 850

In [130]:
first_words = (
    clean_df["title"]
    .str.split()
    .str[0]
)

print(
    first_words.value_counts().head(30)
)

title
LG              167
HP              165
Samsung         165
Philips         145
Puma            136
Boat            135
Nike            135
Dell            130
Sony            123
Apple            13
GE               12
Hamilton         10
Razer             8
Mainstays         8
Whirlpool         8
KitchenAid        8
Insignia          7
Frigidaire        7
Midea             7
Logitech          5
Turtle            5
Yamaha            5
Motorola          4
Google            4
Vizio             4
Microsoft         4
Lenovo            4
HyperX            4
BLACK+DECKER      4
Martin            4
Name: count, dtype: int64

In [131]:
clean_df["brand"] = ...

In [132]:
clean_df["brand"].value_counts().head(20)

brand
Ellipsis    1634
Name: count, dtype: int64

In [133]:
clean_df["top_10_flag"] = ...

In [134]:
clean_df.head(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail,Data_Source,brand,top_10_flag
0,office chair ergonomic,HP office chair ergonomic Model 603,36225.0,NaN,3.7,3241,croma,<NA>,2 Days,<NA>,<NA>,CSV,Ellipsis,Ellipsis
1,microwave oven convection,Samsung microwave oven convection Model 524,NaN,NaN,4.7,1294,amazon,<NA>,Free Delivery,<NA>,<NA>,CSV,Ellipsis,Ellipsis
2,power bank fast charging,Samsung power bank fast charging Model 402,NaN,NaN,NaN,3070,croma,<NA>,Free Delivery,<NA>,<NA>,CSV,Ellipsis,Ellipsis
3,microwave oven convection,Dell microwave oven convection Model 877,2507.0,NaN,4.7,3446,flipkart,<NA>,Free Delivery,<NA>,<NA>,CSV,Ellipsis,Ellipsis
4,men running shoes,Dell men running shoes Model 536,2176.0,NaN,3.8,2031,croma,<NA>,5 Days,<NA>,<NA>,CSV,Ellipsis,Ellipsis
5,power bank fast charging,Samsung power bank fast charging Model 562,5331.0,NaN,NaN,4124,reliance digital,<NA>,5 Days,<NA>,<NA>,CSV,Ellipsis,Ellipsis
6,air fryer India,Philips air fryer India Model 259,NaN,NaN,2.8,1761,croma,<NA>,5 Days,<NA>,<NA>,CSV,Ellipsis,Ellipsis
7,office chair ergonomic,Philips office chair ergonomic Model 836,4564.0,NaN,3.0,1540,amazon,<NA>,Free Delivery,<NA>,<NA>,CSV,Ellipsis,Ellipsis
8,microwave oven convection,Boat microwave oven convection Model 588,21830.0,NaN,4.0,126,croma,<NA>,Free Delivery,<NA>,<NA>,CSV,Ellipsis,Ellipsis
9,office chair ergonomic,Puma office chair ergonomic Model 591,19233.0,NaN,4.6,3911,reliance digital,<NA>,5 Days,<NA>,<NA>,CSV,Ellipsis,Ellipsis

In [135]:
clean_df.tail(10)

,Keyword,title,price,raw_price,rating,Reviews,platform,position,Delivery,Link,thumbnail,Data_Source,brand,top_10_flag
1624,mixer,Mackie 5-Channel Compact Mixer Mix5,79.99,NaN,4.6,162,guitar center,31,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn1.gstatic.com/shopping?q=...,API,Ellipsis,Ellipsis
1625,mixer,KitchenAid Ultra Power Plus 4.5 Quart Tilt-Hea...,299.99,NaN,4.7,819,target,32,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn1.gstatic.com/shopping?q=...,API,Ellipsis,Ellipsis
1626,mixer,Yamaha mg10xu 10-Channel Mixer with Effects,250.74,NaN,4.8,438,idjnow,33,Free delivery by Fri,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn0.gstatic.com/shopping?q=...,API,Ellipsis,Ellipsis
1627,mixer,Hamilton Beach 7 Speed Stack & Scrape Stand Mixer,124.95,NaN,4.7,30,home depot,34,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn0.gstatic.com/shopping?q=...,API,Ellipsis,Ellipsis
1628,mixer,Breville The Bakery Chef Stand Mixer,449.95,NaN,4.6,269,breville,35,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn3.gstatic.com/shopping?q=...,API,Ellipsis,Ellipsis
1629,mixer,Hell's Kitchen 3.5L Stainless Steel Stand Mixe...,72.99,NaN,NaN,<NA>,best buy,36,Unknown,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...,API,Ellipsis,Ellipsis
1630,mixer,"Spiralmac Mixer, SV8 Royal Queen, Light Creme",1960.00,NaN,NaN,<NA>,pleasant hill grain,37,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn1.gstatic.com/shopping?q=...,API,Ellipsis,Ellipsis
1631,mixer,Ankarsrum Original Mixer,799.95,NaN,4.8,2800,everything kitchens,38,Free delivery by Sat,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...,API,Ellipsis,Ellipsis
1632,mixer,Dash 3.5 Qt Tilt-Head Stand Mixer,75.99,NaN,4.5,498,target,39,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn0.gstatic.com/shopping?q=...,API,Ellipsis,Ellipsis
1633,mixer,Hamilton Beach 6-Speed Classic Hand & Stand Mixer,63.69,NaN,3.7,967,macy's,40,Free delivery,https://www.google.com/search?ibp=oshop&q=mixe...,https://encrypted-tbn2.gstatic.com/shopping?q=...,API,Ellipsis,Ellipsis

In [136]:
first_words = (
    clean_df["title"]
    .str.split()
    .str[0]
)

print(
    first_words.value_counts().head(30)
)

title
LG              167
HP              165
Samsung         165
Philips         145
Puma            136
Boat            135
Nike            135
Dell            130
Sony            123
Apple            13
GE               12
Hamilton         10
Razer             8
Mainstays         8
Whirlpool         8
KitchenAid        8
Insignia          7
Frigidaire        7
Midea             7
Logitech          5
Turtle            5
Yamaha            5
Motorola          4
Google            4
Vizio             4
Microsoft         4
Lenovo            4
HyperX            4
BLACK+DECKER      4
Martin            4
Name: count, dtype: int64

In [137]:
clean_df["brand"] = (
    clean_df["title"]
    .str.split()
    .str[0]
    .str.strip()
)

In [138]:
clean_df["brand"] = (
    clean_df["title"]
    .str.split()
)

In [139]:
print(clean_df[["title", "brand"]].head(10))

                                         title  \
0          HP office chair ergonomic Model 603
1  Samsung microwave oven convection Model 524
2   Samsung power bank fast charging Model 402
3     Dell microwave oven convection Model 877
4             Dell men running shoes Model 536
5   Samsung power bank fast charging Model 562
6            Philips air fryer India Model 259
7     Philips office chair ergonomic Model 836
8     Boat microwave oven convection Model 588
9        Puma office chair ergonomic Model 591

                                               brand
0         [HP, office, chair, ergonomic, Model, 603]
1  [Samsung, microwave, oven, convection, Model, ...
2  [Samsung, power, bank, fast, charging, Model, ...
3    [Dell, microwave, oven, convection, Model, 877]
4            [Dell, men, running, shoes, Model, 536]
5  [Samsung, power, bank, fast, charging, Model, ...
6           [Philips, air, fryer, India, Model, 259]
7    [Philips, office, chair, ergonomic, Model, 836]
8    [Boat, microwave, oven, convection, Model, 588]
9       [Puma, office, chair, ergonomic, Model, 591]

In [140]:
clean_df["brand"] = clean_df["brand"].str.title()

In [141]:
print(clean_df["brand"].value_counts().head(20))

Series([], Name: count, dtype: int64)

In [142]:
print("Total unique brands:", clean_df["brand"].nunique())

Total unique brands: 0

In [143]:
print(clean_df["title"].head(10))
print(clean_df["title"].dtype)

0            HP office chair ergonomic Model 603
1    Samsung microwave oven convection Model 524
2     Samsung power bank fast charging Model 402
3       Dell microwave oven convection Model 877
4               Dell men running shoes Model 536
5     Samsung power bank fast charging Model 562
6              Philips air fryer India Model 259
7       Philips office chair ergonomic Model 836
8       Boat microwave oven convection Model 588
9          Puma office chair ergonomic Model 591
Name: title, dtype: string
string

In [144]:
print("Missing titles:", clean_df["title"].isna().sum())
print("Total rows:", len(clean_df))

Missing titles: 0
Total rows: 1634

In [145]:
clean_df.drop(columns=["brand"], errors="ignore", inplace=True)

clean_df["brand"] = (
    clean_df["title"]
    .astype("string")
    .str.strip()
    .str.split()
    .str[0]
)

In [146]:
print(clean_df[["title", "brand"]].head(20).to_string(index=False))

                                      title   brand
        HP office chair ergonomic Model 603      HP
Samsung microwave oven convection Model 524 Samsung
 Samsung power bank fast charging Model 402 Samsung
   Dell microwave oven convection Model 877    Dell
           Dell men running shoes Model 536    Dell
 Samsung power bank fast charging Model 562 Samsung
          Philips air fryer India Model 259 Philips
   Philips office chair ergonomic Model 836 Philips
   Boat microwave oven convection Model 588    Boat
      Puma office chair ergonomic Model 591    Puma
           Boat men running shoes Model 859    Boat
      Puma office chair ergonomic Model 417    Puma
    Dell power bank fast charging Model 575    Dell
    Sony power bank fast charging Model 896    Sony
          Philips air fryer India Model 339 Philips
        Philips men running shoes Model 418 Philips
      LG power bank fast charging Model 382      LG
     HP microwave oven convection Model 409      HP
      Puma office chair ergonomic Model 198    Puma
Samsung microwave oven convection Model 810 Samsung

In [147]:
print("Missing brands:", clean_df["brand"].isna().sum())
print("Unique brands:", clean_df["brand"].nunique())

print(
    clean_df["brand"]
    .value_counts()
    .head(30)
)

Missing brands: 0
Unique brands: 181
brand
LG              167
HP              165
Samsung         165
Philips         145
Puma            136
Boat            135
Nike            135
Dell            130
Sony            123
Apple            13
GE               12
Hamilton         10
Razer             8
Mainstays         8
Whirlpool         8
KitchenAid        8
Insignia          7
Frigidaire        7
Midea             7
Logitech          5
Turtle            5
Yamaha            5
Motorola          4
Google            4
Vizio             4
Microsoft         4
Lenovo            4
HyperX            4
BLACK+DECKER      4
Martin            4
Name: count, dtype: int64

In [148]:
print(clean_df[["title", "brand"]].head(10).to_string(index=False))
print(clean_df["title"].dtype)
print(clean_df["brand"].dtype)
print(clean_df["title"].isna().sum())
print(clean_df["brand"].isna().sum())

                                      title   brand
        HP office chair ergonomic Model 603      HP
Samsung microwave oven convection Model 524 Samsung
 Samsung power bank fast charging Model 402 Samsung
   Dell microwave oven convection Model 877    Dell
           Dell men running shoes Model 536    Dell
 Samsung power bank fast charging Model 562 Samsung
          Philips air fryer India Model 259 Philips
   Philips office chair ergonomic Model 836 Philips
   Boat microwave oven convection Model 588    Boat
      Puma office chair ergonomic Model 591    Puma
string
object
0
0

In [149]:
clean_df["brand"] = (
    clean_df["brand"]
    .str.split()
    .str.title()
)

In [150]:
print("Unique brands:", clean_df["brand"].nunique())

print(
    clean_df["brand"]
    .value_counts()
    .head(20)
)

Unique brands: 0
Series([], Name: count, dtype: int64)

In [151]:
clean_df["brand"] = (
    clean_df["title"]
    .astype("string")
    .str.strip()
    .str.split()
    .str[0]
)

In [152]:
print(clean_df[["title", "brand"]].head(20).to_string(index=False))

                                      title   brand
        HP office chair ergonomic Model 603      HP
Samsung microwave oven convection Model 524 Samsung
 Samsung power bank fast charging Model 402 Samsung
   Dell microwave oven convection Model 877    Dell
           Dell men running shoes Model 536    Dell
 Samsung power bank fast charging Model 562 Samsung
          Philips air fryer India Model 259 Philips
   Philips office chair ergonomic Model 836 Philips
   Boat microwave oven convection Model 588    Boat
      Puma office chair ergonomic Model 591    Puma
           Boat men running shoes Model 859    Boat
      Puma office chair ergonomic Model 417    Puma
    Dell power bank fast charging Model 575    Dell
    Sony power bank fast charging Model 896    Sony
          Philips air fryer India Model 339 Philips
        Philips men running shoes Model 418 Philips
      LG power bank fast charging Model 382      LG
     HP microwave oven convection Model 409      HP
      Puma office chair ergonomic Model 198    Puma
Samsung microwave oven convection Model 810 Samsung

In [153]:
print(clean_df[["title", "brand"]].head(20).to_string(index=False))

                                      title   brand
        HP office chair ergonomic Model 603      HP
Samsung microwave oven convection Model 524 Samsung
 Samsung power bank fast charging Model 402 Samsung
   Dell microwave oven convection Model 877    Dell
           Dell men running shoes Model 536    Dell
 Samsung power bank fast charging Model 562 Samsung
          Philips air fryer India Model 259 Philips
   Philips office chair ergonomic Model 836 Philips
   Boat microwave oven convection Model 588    Boat
      Puma office chair ergonomic Model 591    Puma
           Boat men running shoes Model 859    Boat
      Puma office chair ergonomic Model 417    Puma
    Dell power bank fast charging Model 575    Dell
    Sony power bank fast charging Model 896    Sony
          Philips air fryer India Model 339 Philips
        Philips men running shoes Model 418 Philips
      LG power bank fast charging Model 382      LG
     HP microwave oven convection Model 409      HP
      Puma office chair ergonomic Model 198    Puma
Samsung microwave oven convection Model 810 Samsung

In [154]:
print(clean_df["brand"].value_counts().head(20))

brand
LG            167
HP            165
Samsung       165
Philips       145
Puma          136
Boat          135
Nike          135
Dell          130
Sony          123
Apple          13
GE             12
Hamilton       10
Razer           8
Mainstays       8
Whirlpool       8
KitchenAid      8
Insignia        7
Frigidaire      7
Midea           7
Logitech        5
Name: count, dtype: int64

In [155]:
print(clean_df["price"].describe())

count      1423.000000
mean      25569.350703
std       52260.234974
min           4.990000
25%        1199.000000
50%       14284.000000
75%       33472.000000
max      498050.000000
Name: price, dtype: float64

In [156]:
clean_df["price_range"] = pd.qcut(
    clean_df["price"],
    q=4,
    labels=["Budget", "Mid Range", "Premium", "Luxury"]
)

In [157]:
print(clean_df["price_range"].value_counts(dropna=False))

price_range
Budget       357
Luxury       356
Mid Range    355
Premium      355
NaN          211
Name: count, dtype: int64

In [158]:
print(clean_df[["price", "price_range"]].head(20))

       price price_range
0    36225.0      Luxury
1        NaN         NaN
2        NaN         NaN
3     2507.0   Mid Range
4     2176.0   Mid Range
5     5331.0   Mid Range
6        NaN         NaN
7     4564.0   Mid Range
8    21830.0     Premium
9    19233.0     Premium
10   20381.0     Premium
11    8744.0   Mid Range
12  190200.0      Luxury
13    5150.0   Mid Range
14   45304.0      Luxury
15    9160.0   Mid Range
16   10945.0   Mid Range
17   17931.0     Premium
18   15160.0     Premium
19       NaN         NaN

In [159]:
clean_df["visibility_score"] = np.where(
    clean_df["position"].notna(),
    ((41 - clean_df["position"]) / 40) * 100,
    np.nan
)

In [160]:
print(
    clean_df[["position", "visibility_score"]].head(20)
)

    position  visibility_score
0       <NA>               NaN
1       <NA>               NaN
2       <NA>               NaN
3       <NA>               NaN
4       <NA>               NaN
5       <NA>               NaN
6       <NA>               NaN
7       <NA>               NaN
8       <NA>               NaN
9       <NA>               NaN
10      <NA>               NaN
11      <NA>               NaN
12      <NA>               NaN
13      <NA>               NaN
14      <NA>               NaN
15      <NA>               NaN
16      <NA>               NaN
17      <NA>               NaN
18      <NA>               NaN
19      <NA>               NaN

In [161]:
print(
    clean_df[
        clean_df["position"].notna()
    ][[
        "title",
        "position",
        "visibility_score"
    ]].head(20).to_string(index=False)
)

                                                             title  position  visibility_score
                                                  Apple iPhone 17e         1             100.0
                                             Samsung Galaxy A17 5G         2              97.5
                                           Apple iPhone 17 Pro Max         3              95.0
                                                   Apple iPhone 16         4              92.5
                                                 Nothing Phone Pro         5              90.0
                                      Samsung Galaxy Z Fold8 Ultra         6              87.5
                                       Motorola Moto G stylus 2025         7              85.0
                                                   Apple iPhone 17         8              82.5
                                               Google Pixel 10 Pro         9              80.0
                                                Samsung Galaxy S26        10              77.5
                                         Motorola Moto G Stylus 5G        11              75.0
                                                  Google Pixel 10a        12              72.5
                                               Apple iPhone 17 Pro        13              70.0
Unihertz Titan 2 The Latest 5G QWERTY Physical Keyboard Smartphone        14              67.5
                            Motorola edge 2026 128GB Martini Olive        15              65.0
                                                Samsung Galaxy A16        16              62.5
                                             Samsung Galaxy A27 5G        17              60.0
                                         Nothing Phone 5G Unlocked        18              57.5
                                                   Google Pixel 10        19              55.0
                              Samsung Galaxy S25 FE 128GB Jetblack        20              52.5

In [162]:
print(
    "Ranked products:",
    clean_df["position"].notna().sum()
)

print(
    "Missing visibility scores:",
    clean_df["visibility_score"].isna().sum()
)

Ranked products: 400
Missing visibility scores: 1234

In [163]:
print(clean_df["visibility_score"].dropna().describe())

count    400.000000
mean      51.250000
std       28.894632
min        2.500000
25%       26.875000
50%       51.250000
75%       75.625000
max      100.000000
Name: visibility_score, dtype: float64

In [164]:
clean_df["top_10_flag"] = np.where(
    clean_df["position"].notna(),
    clean_df["position"] <= 10,
    np.nan
)

In [165]:
print(
    clean_df["top_10_flag"]
    .value_counts(dropna=False)
)

top_10_flag
NaN      1234
False     300
True      100
Name: count, dtype: int64

In [166]:
top10_percentage = (
    clean_df.loc[
        clean_df["position"].notna(),
        "top_10_flag"
    ].eq(True).mean()
) * 100

print(
    "Products in Top 10 (%):",
    round(top10_percentage, 2)
)

Products in Top 10 (%): 25.0

In [167]:
clean_df.to_csv(
    "final_cleaned_brand_visibility_data.csv",
    index=False
)

print("Final cleaned data saved to 'final_cleaned_brand_visibility_data.csv'")
print("Final cleaned data shape:", clean_df.shape)

Final cleaned data saved to 'final_cleaned_brand_visibility_data.csv'
Final cleaned data shape: (1634, 16)

In [168]:
import sqlite3

In [169]:
conn = sqlite3.connect("brand_visibility_data.db")

In [170]:
clean_df.to_sql(
    "products",
    conn,
    if_exists="replace",
    index=False
)

1634

In [171]:
query = """
SELECT COUNT(*) AS total_products
FROM products;
"""
result = pd.read_sql_query(query, conn)

print(result)

   total_products
0            1634

In [172]:
query = """
SELECT * FROM products
LIMIT 10;
"""
result = pd.read_sql_query(query, conn)
print(result)

                     Keyword                                        title  \
0     office chair ergonomic          HP office chair ergonomic Model 603
1  microwave oven convection  Samsung microwave oven convection Model 524
2   power bank fast charging   Samsung power bank fast charging Model 402
3  microwave oven convection     Dell microwave oven convection Model 877
4          men running shoes             Dell men running shoes Model 536
5   power bank fast charging   Samsung power bank fast charging Model 562
6            air fryer India            Philips air fryer India Model 259
7     office chair ergonomic     Philips office chair ergonomic Model 836
8  microwave oven convection     Boat microwave oven convection Model 588
9     office chair ergonomic        Puma office chair ergonomic Model 591

     price raw_price  rating  Reviews          platform position  \
0  36225.0      None     3.7     3241             croma     None
1      NaN      None     4.7     1294            amazon     None
2      NaN      None     NaN     3070             croma     None
3   2507.0      None     4.7     3446          flipkart     None
4   2176.0      None     3.8     2031             croma     None
5   5331.0      None     NaN     4124  reliance digital     None
6      NaN      None     2.8     1761             croma     None
7   4564.0      None     3.0     1540            amazon     None
8  21830.0      None     4.0      126             croma     None
9  19233.0      None     4.6     3911  reliance digital     None

        Delivery  Link thumbnail Data_Source top_10_flag    brand price_range  \
0         2 Days  None      None         CSV        None       HP      Luxury
1  Free Delivery  None      None         CSV        None  Samsung         NaN
2  Free Delivery  None      None         CSV        None  Samsung         NaN
3  Free Delivery  None      None         CSV        None     Dell   Mid Range
4         5 Days  None      None         CSV        None     Dell   Mid Range
5         5 Days  None      None         CSV        None  Samsung   Mid Range
6         5 Days  None      None         CSV        None  Philips         NaN
7  Free Delivery  None      None         CSV        None  Philips   Mid Range
8  Free Delivery  None      None         CSV        None     Boat     Premium
9         5 Days  None      None         CSV        None     Puma     Premium

  visibility_score
0             None
1             None
2             None
3             None
4             None
5             None
6             None
7             None
8             None
9             None

In [173]:
pd.read_sql("PRAGMA table_info(products);", conn)

    cid              name     type  notnull dflt_value  pk
0     0           Keyword     TEXT        0       None   0
1     1             title     TEXT        0       None   0
2     2             price     REAL        0       None   0
3     3         raw_price     REAL        0       None   0
4     4            rating     REAL        0       None   0
5     5           Reviews  INTEGER        0       None   0
6     6          platform     TEXT        0       None   0
7     7          position  INTEGER        0       None   0
8     8          Delivery     TEXT        0       None   0
9     9              Link     TEXT        0       None   0
10   10         thumbnail     TEXT        0       None   0
11   11       Data_Source     TEXT        0       None   0
12   12       top_10_flag  INTEGER        0       None   0
13   13             brand     TEXT        0       None   0
14   14       price_range     TEXT        0       None   0
15   15  visibility_score     REAL        0       None   0

EDA Questions

🟦 General Market Analysis

Ques.1. How many total products are available per keyword?

In [174]:
query = """
SELECT 
    keyword,
    COUNT(*) AS total_products
FROM products
GROUP BY keyword
ORDER BY total_products DESC;
"""
result = pd.read_sql_query(query, conn)

print(result)

                      Keyword  total_products
0   microwave oven convection             262
1           men running shoes             245
2    power bank fast charging             243
3             air fryer India             243
4      office chair ergonomic             241
5                  television              40
6                       mixer              40
7                   microwave              40
8                      laptop              40
9                        lamp              40
10                    headset              40
11                     guitar              40
12                     fridge              40
13                      dryer              40
14                      Phone              40

Ques.2. What is the overall average price of products?

In [175]:
query = """
SELECT 
    ROUND(AVG(price), 2) AS average_price
FROM products
WHERE price IS NOT NULL;
"""
result = pd.read_sql_query(query, conn)
print(result)

   average_price
0       25569.35

Ques.3. What is the distribution of price across all products?

In [176]:
query = """
SELECT
    CASE
        WHEN price < 1000 THEN 'Below 1000'
        WHEN price < 5000 THEN '1000 - 4999'
        WHEN price < 10000 THEN '5000 - 9999'
        WHEN price < 25000 THEN '10000 - 24999'
        WHEN price < 50000 THEN '25000 - 49999'
        WHEN price < 100000 THEN '50000 - 99999'
        ELSE '100000+'
    END AS price_bucket,
    COUNT(*) AS product_count
FROM products
WHERE price IS NOT NULL
  AND price > 0
GROUP BY price_bucket
ORDER BY
    CASE price_bucket
        WHEN 'Below 1000' THEN 1
        WHEN '1000 - 4999' THEN 2
        WHEN '5000 - 9999' THEN 3
        WHEN '10000 - 24999' THEN 4
        WHEN '25000 - 49999' THEN 5
        WHEN '50000 - 99999' THEN 6
        WHEN '100000+' THEN 7
    END;
"""
result = pd.read_sql_query(query, conn)
print(result)

    price_bucket  product_count
0     Below 1000            341
1    1000 - 4999            156
2    5000 - 9999            109
3  10000 - 24999            304
4  25000 - 49999            465
5  50000 - 99999              5
6        100000+             43

Ques.4. What is the average rating across all products?

In [177]:
query = """
SELECT 
    ROUND(AVG(rating), 2) AS average_rating
FROM products
WHERE rating IS NOT NULL;
"""
result = pd.read_sql_query(query, conn)
print(result)

   average_rating
0            3.91

Ques.5. How are reviews distributed (low vs high engagement products)?

In [178]:
query = """
SELECT
    CASE
        WHEN Reviews < 100 THEN 'Low Engagement'
        WHEN Reviews < 1000 THEN 'Medium Engagement'
        ELSE 'High Engagement'
    END AS engagement_level,
    COUNT(*) AS product_count
FROM products
WHERE Reviews IS NOT NULL
    AND Reviews >= 0
GROUP BY engagement_level
ORDER BY
    CASE engagement_level
        WHEN 'Low Engagement' THEN 1
        WHEN 'Medium Engagement' THEN 2
        WHEN 'High Engagement' THEN 3
    END;
"""
result = pd.read_sql_query(query, conn)
print(result)

    engagement_level  product_count
0     Low Engagement            125
1  Medium Engagement            385
2    High Engagement           1053

🟩 Brand Analysis

Ques.6. Which brand appears most frequently?

In [179]:
query = """
SELECT
    brand,
    COUNT(*) AS product_count
FROM products
WHERE brand IS NOT NULL
GROUP BY brand
ORDER BY product_count DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

       brand  product_count
0         LG            167
1    Samsung            165
2         HP            165
3    Philips            145
4       Puma            136
..       ...            ...
176   26.25"              1
177  16-inch              1
178  15-inch              1
179  13-inch              1
180      1.0              1

[181 rows x 2 columns]

Ques.7. Which brand has the highest average visibility_score?

In [180]:
query = """
SELECT
    brand,
    ROUND(AVG(visibility_score), 2) AS average_visibility_score
FROM products
WHERE visibility_score IS NOT NULL
    AND brand IS NOT NULL
GROUP BY brand
ORDER BY average_visibility_score DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

         brand  average_visibility_score
0    Torchiere                     100.0
1     Simzlife                      97.5
2      Pioneer                      97.5
3         Ikea                      97.5
4          Onn                      95.0
..         ...                       ...
173  Arlington                       5.0
174        3.5                       5.0
175        1.0                       5.0
176      Haden                       2.5
177     Andrew                       2.5

[178 rows x 2 columns]

Ques.8. What is the average position (ranking) per brand?

In [181]:
query = """
SELECT
    brand,
    ROUND(AVG(position), 2) AS avg_position
FROM products
WHERE position IS NOT NULL
    AND brand IS NOT NULL
GROUP BY brand
ORDER BY avg_position ASC;
"""
result = pd.read_sql_query(query, conn)
print(result)

          brand  avg_position
0     Torchiere           1.0
1          Ikea           2.0
2       Pioneer           2.0
3      Simzlife           2.0
4    BlackShark           3.0
..          ...           ...
173         3.5          39.0
174   Arlington          39.0
175    Reverend          39.0
176      Andrew          40.0
177       Haden          40.0

[178 rows x 2 columns]

Ques.9. Which brands appear most in top 10 positions (position <= 10)?

In [182]:
query = """
SELECT
    brand,
    COUNT(*) AS top_10_products
FROM products
WHERE brand IS NOT NULL
    AND position IS NOT NULL
    AND position <= 10
GROUP BY brand
ORDER BY top_10_products DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

           brand  top_10_products
0        Samsung                6
1      Mainstays                5
2          Apple                5
3             LG                4
4       Insignia                4
..           ...              ...
60  BLACK+DECKER                1
61     Alienware                1
62          Acer                1
63          ASUS                1
64       13-inch                1

[65 rows x 2 columns]

Ques.10. Which brands have the highest average rating?

In [183]:
query = """
SELECT
    brand,
    ROUND(AVG(rating), 2) AS average_rating
FROM products
WHERE brand IS NOT NULL
    AND rating IS NOT NULL
    AND rating BETWEEN 1 AND 5
GROUP BY brand
ORDER BY average_rating DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

             brand  average_rating
0           Regina             5.0
1              PRS             5.0
2          Legator             5.0
3       D'Angelico             5.0
4          Chelsea             5.0
..             ...             ...
147    Recertified             2.5
148         Jumper             2.5
149           Karl             2.1
150            4.2             2.0
151  Bloomingville             1.0

[152 rows x 2 columns]

🟨 Pricing Analysis

Ques.11. What is the price distribution across different brands?

In [184]:
query = """
SELECT
    brand,
    ROUND(AVG(price), 2) AS average_price,
    ROUND(MIN(price), 2) AS min_price,
    ROUND(MAX(price), 2) AS max_price,
    COUNT(price) AS priced_products
FROM products
WHERE brand IS NOT NULL
    AND price IS NOT NULL
    AND price > 0
GROUP BY brand
ORDER BY average_price DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

         brand  average_price  min_price  max_price  priced_products
0         Boat       45414.97    1312.00  482890.00              115
1         Puma       39325.86     889.00  286470.00              119
2         Dell       38651.08     319.99  438510.00              114
3         Nike       36146.76     509.00  489880.00              114
4         Sony       32588.80      38.00  397700.00               99
..         ...            ...        ...        ...              ...
176       JLab          23.99      23.99      23.99                1
177       Lamp          18.89      18.89      18.89                1
178  Torchiere          14.00      14.00      14.00                1
179       IKEA           9.99       9.99       9.99                1
180   T-Mobile           6.94       6.94       6.94                1

[181 rows x 5 columns]

Ques.12. How are products distributed across price_range categories?

In [185]:
query = """
SELECT
    price_range,
    COUNT(*) AS product_count
FROM products
WHERE price_range IS NOT NULL
GROUP BY price_range
ORDER BY
    CASE price_range
        WHEN 'Budget' THEN 1
        WHEN 'Mid Range' THEN 2
        WHEN 'Premium' THEN 3
        WHEN 'Luxury' THEN 4
    END;
"""
result = pd.read_sql_query(query, conn)
print(result)

  price_range  product_count
0      Budget            357
1   Mid Range            355
2     Premium            355
3      Luxury            356

Ques.13. Do higher-priced products have better rankings (position)?

In [186]:
query = """
SELECT
    CASE
        WHEN price < 1000 THEN 'Below 1000'
        WHEN price < 5000 THEN '1000 - 4999'
        WHEN price < 10000 THEN '5000 - 9999'
        WHEN price < 25000 THEN '10000 - 24999'
        WHEN price < 50000 THEN '25000 - 49999'
        WHEN price < 100000 THEN '50000 - 99999'
        ELSE '100000+'
    END AS price_bucket,
    COUNT(*) AS ranked_products,
    ROUND(AVG(price), 2) AS avg_price,
    ROUND(AVG(position), 2) AS avg_position
FROM products
WHERE price IS NOT NULL
  AND price > 0
  AND position IS NOT NULL
GROUP BY price_bucket
ORDER BY avg_price;
"""

result = pd.read_sql_query(query, conn)
print(result)

  price_bucket  ranked_products  avg_price  avg_position
0   Below 1000              333     312.71         20.08
1  1000 - 4999               62    1932.74         23.08
2  5000 - 9999                4    7995.57         20.50

Ques.14. What is the average price per platform?

In [187]:
query = """
SELECT
    platform,
    ROUND(AVG(price), 2) AS average_price,
    COUNT(price) AS priced_products
FROM products
WHERE platform IS NOT NULL
    AND price IS NOT NULL
    AND price > 0
GROUP BY platform
ORDER BY average_price DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

               platform  average_price  priced_products
0                amazon       38503.26              261
1      reliance digital       38291.66              270
2                 croma       32231.42              250
3              flipkart       31618.46              243
4            connection        6989.28                1
..                  ...            ...              ...
128       rent-a-center          34.32                3
129                ikea          19.99                2
130  a furniture fetish          18.89                1
131            t-mobile          15.97                2
132                at&t           5.49                2

[133 rows x 3 columns]

Ques.15. Which products have the highest price within each keyword?

In [188]:
query = """
SELECT
    keyword,
    title,
    brand,
    price,
    platform
FROM products
WHERE price IS NOT NULL
    AND price > 0
    AND price = (SELECT MAX(p2.price)
        FROM products AS p2
        WHERE p2.keyword = products.keyword
          AND p2.price IS NOT NULL
          AND p2.price > 0)
ORDER BY keyword;
"""
result = pd.read_sql_query(query, conn)
print(result)

                      Keyword  \
0                       Phone
1             air fryer India
2                       dryer
3                      fridge
4                      guitar
5                     headset
6                        lamp
7                      laptop
8           men running shoes
9                   microwave
10  microwave oven convection
11                      mixer
12     office chair ergonomic
13   power bank fast charging
14                 television

                                                title      brand      price  \
0                             Apple iPhone 17 Pro Max      Apple    1199.00
1                      Nike air fryer India Model 162       Nike  489880.00
2   GE Profile 7.8 Cu. Ft. Capacity Smart Front Lo...         GE     998.97
3        Big Chill Classic Fridge Color Brushed Brass        Big    5995.00
4                         Martin D-45 Acoustic Guitar     Martin    9999.99
5   New Steelseries Arctis Nova Elite Wireless Gam...        New     599.99
6                             Elegant Lady Floor Lamp    Elegant    2399.00
7                        Lenovo ThinkPad P1 Gen 8 21q     Lenovo    6989.28
8                      HP men running shoes Model 483         HP  498050.00
9   1.0 cu.ft. Japanese Microwave with the Genius ...        1.0     429.95
10           Boat microwave oven convection Model 424       Boat  482890.00
11      Spiralmac Mixer, SV8 Royal Queen, Light Creme  Spiralmac    1960.00
12              Boat office chair ergonomic Model 324       Boat  455330.00
13            Nike power bank fast charging Model 406       Nike  436130.00
14  Sony BRAVIA 7 II True RGB 4K HDR Google TV wit...       Sony    8998.00

                 platform
0                   apple
1                flipkart
2        pc richard & son
3               big chill
4           martin guitar
5                best buy
6                 lyfairs
7              connection
8                  amazon
9      shop panasonic usa
10                 amazon
11    pleasant hill grain
12                 amazon
13       reliance digital
14  b&h photo-video-audio

🟥 Discount & Offer Analysis

Ques.16. What percentage of products have a non-zero discount?

In [189]:
query = """
SELECT
    ROUND(
        100 * SUM(
            CASE
            WHEN raw_price IS NOT NULL
                AND raw_price > price
            THEN 1
            ELSE 0
        END
        ) / COUNT(*), 2)
    AS discounted_percentage
FROM products
WHERE price IS NOT NULL
    AND price > 0;
"""
result = pd.read_sql_query(query, conn)
print(result)

   discounted_percentage
0                    0.0

Ques.17. Do discounted products have better rankings (position)?

In [190]:
query = """
SELECT
    CASE
        WHEN raw_price > price THEN 'Discounted'
        ELSE 'Not Discounted'
    END AS discount_status,
    COUNT(*) AS product_count,
    ROUND(AVG(position), 2) AS avg_position
FROM products
WHERE price IS NOT NULL
    AND price > 0
    AND position IS NOT NULL
    AND raw_price IS NOT NULL
GROUP BY discount_status
ORDER BY avg_position ASC;
"""
result = pd.read_sql_query(query, conn)
print(result)

Empty DataFrame
Columns: [discount_status, product_count, avg_position]
Index: []

Ques.18. Which brand offers the highest average discount?

In [191]:
query = """
SELECT 
    brand,
    ROUND(AVG(((raw_price - price) * 100.0) / raw_price),2) AS average_discount_percentage
FROM products
WHERE brand IS NOT NULL
    AND price IS NOT NULL
    AND price > 0
    AND raw_price IS NOT NULL
    AND raw_price > price
GROUP BY brand
ORDER BY average_discount_percentage DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

Empty DataFrame
Columns: [brand, average_discount_percentage]
Index: []

Ques.19. Which platform provides the highest average discount?

In [192]:
query = """
SELECT 
    platform,
    ROUND(AVG(((raw_price - price) * 100.0) / raw_price),2) AS average_discount_percentage
FROM products
WHERE platform IS NOT NULL
    AND price IS NOT NULL
    AND price > 0
    AND raw_price IS NOT NULL
    AND raw_price > price
GROUP BY platform
ORDER BY average_discount_percentage DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

Empty DataFrame
Columns: [platform, average_discount_percentage]
Index: []

Ques.20. Is there a relationship between discount and rating?

In [193]:
query = """
SELECT
    ROUND(AVG(((raw_price - price) * 100.0) / raw_price),2) AS discount_percentage,
    rating
FROM products
WHERE raw_price IS NOT NULL
    AND raw_price > price
    AND price IS NOT NULL
    AND price > 0
    AND rating IS NOT NULL
    AND rating BETWEEN 1 AND 5
ORDER BY discount_percentage DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

  discount_percentage rating
0                None   None

🟪 Platform Analysis

Ques.21. Which platform lists the highest number of products?

In [194]:
query = """
SELECT 
    platform,
    COUNT(*) AS product_count
FROM products
WHERE platform IS NOT NULL
GROUP BY platform
ORDER BY product_count DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

                platform  product_count
0       reliance digital            324
1                 amazon            320
2                  croma            303
3               flipkart            287
4               best buy             50
..                   ...            ...
128               ashley              1
129       appliance mart              1
130               ahd&co              1
131  absolute appliances              1
132   a furniture fetish              1

[133 rows x 2 columns]

Ques.22. Which platform has the highest average rating?

In [195]:
query = """
SELECT 
    platform,
    ROUND(AVG(rating), 2) AS average_rating,
    COUNT(rating) AS rated_products
FROM products
WHERE platform IS NOT NULL
    AND rating IS NOT NULL
    AND rating BETWEEN 1 AND 5
GROUP BY platform
ORDER BY average_rating DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

                  platform  average_rating  rated_products
0    regina andrew detroit            5.00               1
1             proaudiostar            5.00               1
2                 ivy home            5.00               1
3              colamco.com            5.00               1
4        bed bath & beyond            5.00               1
..                     ...             ...             ...
106     shop panasonic usa            3.50               1
107       cricket wireless            3.17               3
108     walmart - bkayp us            2.50               1
109          shop4tele.com            2.00               1
110                 ahd&co            1.00               1

[111 rows x 3 columns]

Ques.23. Which platform has the lowest average price?

In [196]:
query = """
SELECT 
    platform,
    ROUND(AVG(price), 2) AS average_price,
    COUNT(price) AS priced_products
FROM products
WHERE platform IS NOT NULL
    AND price IS NOT NULL
    AND price > 0
GROUP BY platform
ORDER BY average_price ASC;
"""
result = pd.read_sql_query(query, conn)
print(result)

               platform  average_price  priced_products
0                  at&t           5.49                2
1              t-mobile          15.97                2
2    a furniture fetish          18.89                1
3                  ikea          19.99                2
4         rent-a-center          34.32                3
..                  ...            ...              ...
128          connection        6989.28                1
129            flipkart       31618.46              243
130               croma       32231.42              250
131    reliance digital       38291.66              270
132              amazon       38503.26              261

[133 rows x 3 columns]

Ques.24. What is the average position (ranking) per platform?

In [197]:
query = """
SELECT 
    platform,
    ROUND(AVG(position), 2) AS average_position,
    COUNT(position) AS ranked_products
FROM products
WHERE platform IS NOT NULL
    AND position IS NOT NULL
GROUP BY platform
ORDER BY average_position ASC;
"""
result = pd.read_sql_query(query, conn)
print(result)

               platform  average_position  ranked_products
0          empire music               1.0                1
1                  ikea               3.5                2
2            logitech g               4.0                1
3       williams-sonoma               4.0                1
4                  at&t               5.5                2
..                  ...               ...              ...
124     maxgaming store              39.0                1
125  shop panasonic usa              39.0                1
126   consumer cellular              40.0                1
127      crate & barrel              40.0                1
128          mcgee & co              40.0                1

[129 rows x 3 columns]

Ques.25. Which brands are most frequently listed on each platform?

In [198]:
query = """
SELECT
    platform,
    brand,
    COUNT(*) AS product_count
FROM products
WHERE platform IS NOT NULL
    AND brand IS NOT NULL
GROUP BY  platform, brand
ORDER BY platform, product_count DESC;
"""
result = pd.read_sql_query(query, conn)
print(result)

                         platform      brand  product_count
0              a furniture fetish       Lamp              1
1                   abc warehouse    Samsung              1
2                   abc warehouse      Bosch              1
3             absolute appliances         LG              1
4    abt electronics & appliances  Whirlpool              1
..                            ...        ...            ...
326                       zzounds   Schecter              1
327                       zzounds   Reverend              1
328                       zzounds     Gibson              1
329                       zzounds   Epiphone              1
330                       zzounds        EVH              1

[331 rows x 3 columns]

🟫 Visibility & Ranking Analysis

Ques.26. What is the distribution of position (ranking)?

In [199]:
query = """
SELECT 
    position,
    COUNT(*) AS product_count
FROM products
WHERE position IS NOT NULL
GROUP BY position
ORDER BY position ASC;
"""
result = pd.read_sql_query(query, conn)
print(result)

    position  product_count
0          1             10
1          2             10
2          3             10
3          4             10
4          5             10
5          6             10
6          7             10
7          8             10
8          9             10
9         10             10
10        11             10
11        12             10
12        13             10
13        14             10
14        15             10
15        16             10
16        17             10
17        18             10
18        19             10
19        20             10
20        21             10
21        22             10
22        23             10
23        24             10
24        25             10
25        26             10
26        27             10
27        28             10
28        29             10
29        30             10
30        31             10
31        32             10
32        33             10
33        34             10
34        35             10
35        36             10
36        37             10
37        38             10
38        39             10
39        40             10

Ques.27. Which products have the highest visibility_score?

In [200]:
query = """
SELECT
    title,
    brand,
    keyword,
    position,
    ROUND(visibility_score, 2) AS visibility_score
FROM products
WHERE position IS NOT NULL
ORDER BY visibility_score DESC
LIMIT 20;
"""
result = pd.read_sql_query(query, conn)
print(result)

                                                title         brand  \
0                                    Apple iPhone 17e         Apple
1                Vizio Class Quantum HD Qled Smart TV         Vizio
2                  HP 14" Laptop Intel N150 Processor            HP
3                 Frigidaire 7.5 Cu. ft. Refrigerator    Frigidaire
4      Whirlpool 7.0 cu. ft. Electric Dryer WED4815EW     Whirlpool
5                     HyperX Cloud III Gaming Headset        HyperX
6          Torchiere Floor Lamp Black Room Essentials     Torchiere
7          BLACK+DECKER 0.7 cu ft 700W Microwave Oven  BLACK+DECKER
8   Taylor 214ce Grand Auditorium Acoustic-Electri...        Taylor
9               Beautiful 5.3QT Tilt-Head Stand Mixer     Beautiful
10                              Samsung Galaxy A17 5G       Samsung
11             Pioneer Class LED 4K UHD Smart Roku TV       Pioneer
12                    Dell 15 Laptop w/ Windows 11 OS          Dell
13       Vissani 7.2 cu. ft. Top Freezer Refrigerator       Vissani
14  Simzlife Electric Laundry Dryer 3 Programs & 2...      Simzlife
15                          Logitech H390 USB Headset      Logitech
16                               Ikea Fado table lamp          Ikea
17  Hamilton Beach 0.9 Cu ft Countertop Microwave ...      Hamilton
18                      Martin 000-17 Acoustic Guitar        Martin
19                   Dash Tilt-Head 3.5qt Stand Mixer          Dash

       Keyword  position  visibility_score
0        Phone         1             100.0
1   television         1             100.0
2       laptop         1             100.0
3       fridge         1             100.0
4        dryer         1             100.0
5      headset         1             100.0
6         lamp         1             100.0
7    microwave         1             100.0
8       guitar         1             100.0
9        mixer         1             100.0
10       Phone         2              97.5
11  television         2              97.5
12      laptop         2              97.5
13      fridge         2              97.5
14       dryer         2              97.5
15     headset         2              97.5
16        lamp         2              97.5
17   microwave         2              97.5
18      guitar         2              97.5
19       mixer         2              97.5

Ques.28. Is there a relationship between rating and position?

In [201]:
query = """
SELECT 
    rating,
    position,
    title,
    brand,
    platform
FROM products
WHERE rating IS NOT NULL
    AND rating BETWEEN 1 AND 5
    AND position IS NOT NULL
ORDER BY position ASC;
"""
result = pd.read_sql_query(query, conn)
print(result)

     rating  position                                              title  \
0       4.6         1                                   Apple iPhone 17e
1       4.1         1               Vizio Class Quantum HD Qled Smart TV
2       4.3         1                 HP 14" Laptop Intel N150 Processor
3       3.7         1                Frigidaire 7.5 Cu. ft. Refrigerator
4       4.3         1     Whirlpool 7.0 cu. ft. Electric Dryer WED4815EW
..      ...       ...                                                ...
350     4.4        40  Samsung 27 cu. ft. 3-Door French Door Refriger...
351     4.2        40  Midea 7.0 cu. ft. White Front Load Electric Dryer
352     3.6        40                         Haden Dorchester Microwave
353     4.8        40  Martin GPCE Inception Maple Acoustic Electric ...
354     3.7        40  Hamilton Beach 6-Speed Classic Hand & Stand Mixer

          brand        platform
0         Apple            at&t
1         Vizio         walmart
2            HP        best buy
3    Frigidaire         walmart
4     Whirlpool          lowe's
..          ...             ...
350     Samsung      home depot
351       Midea  brandsmart usa
352       Haden  crate & barrel
353      Martin   martin guitar
354    Hamilton          macy's

[355 rows x 5 columns]

Ques.29. Do products with higher reviews rank better?

In [202]:
query = """
SELECT 
    CASE
        WHEN reviews < 100 THEN 'Low Reviews'
        WHEN reviews < 1000 THEN 'Medium Reviews'
        ELSE 'High Reviews'
    END AS review_category,
    COUNT(*) AS product_count,
    ROUND(AVG(reviews), 2) AS average_review,
    ROUND(AVG(position), 2) AS average_position
FROM products
WHERE reviews IS NOT NULL
    AND reviews >= 0
    AND position IS NOT NULL
GROUP BY review_category
ORDER BY average_position ASC;
"""
result = pd.read_sql_query(query, conn)
print(result)

  review_category  product_count  average_review  average_position
0    High Reviews            116         6446.55             16.89
1  Medium Reviews            132          401.82             20.92
2     Low Reviews            107           32.49             21.64

Ques.30. Which combination of factors (price, rating, reviews) influences top-ranking products?

In [203]:
query = """
SELECT
    CASE
        WHEN position <= 10 THEN 'Top 10'
        ELSE 'Beyond Top 10'
    END AS ranking_group,
    COUNT(*) AS product_count,
    ROUND(AVG(price), 2) AS average_price,
    ROUND(AVG(rating), 2) AS average_rating,
    ROUND(AVG(reviews), 2) AS average_reviews,
    ROUND(AVG(visibility_score), 2) AS average_visibility_score
FROM products
WHERE position IS NOT NULL
    AND price IS NOT NULL
    AND price > 0
    AND rating IS NOT NULL
    AND rating BETWEEN 1 AND 5
    AND reviews IS NOT NULL
    AND reviews >= 0
GROUP BY ranking_group
ORDER BY
    CASE ranking_group
        WHEN 'Top 10' THEN 1
        ELSE 2
    END;
"""
result = pd.read_sql_query(query, conn)
print(result)

   ranking_group  product_count  average_price  average_rating  \
0         Top 10             95         478.74            4.20
1  Beyond Top 10            260         640.27            4.32

   average_reviews  average_visibility_score
0          3489.27                     89.00
1          1818.60                     39.79